### ISSUE TITLE
Alpha Vantage [APP]

### ISSUE THREAD

**Issue by stepharo** [PipedreamHQ/pipedream#10328]
Why doesnt Alpha Vantage appear when i search for it? It only appears in the workflows. But how should i then provied the preset api-key without app? I have build a workaround with an env but that is not what i expected..

**Comment by sergio-eliot-rodriguez** [comment]
Hi @stepharo 

I think you are searching in the wrong place.

Look, Alpha Vantage has a base integration: https://pipedream.com/apps/alpha-vantage?via=go

Therefore, it appears if you search for it at the [app store](https://pipedream.com/explore?via=go)

If you try to connect an account, via the account menu option, it will appear too:

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/d6021f2b-6e07-46d3-86a2-ac3feba6638d)


I suspect you are looking for actions or sources within workflows.
e.g. when I go to the workflow editor and I look for apps, I am able to find ALpha Vantanga but is only available to work with code steps (no prebuilt actions).

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/1f6d15cc-7ec4-4f4c-907f-fbd74deda8a2)


Can you please let me know where are you searching for Alpha Vantage within the workflow UI so that I can help?
Please add details explaining and an screenshot would be useful.

**Comment by sergio-eliot-rodriguez** [comment]
Without more details, we need to close this issue.
