### ISSUE TITLE
Monday.com

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10439]
### App
Monday.com

### Summary:
Error in existing and previously working workflow

### Details:
After working correctly for some time, the workflow started throwing errors (see below). 
I can't figure out why it stopped working, the problem doesn't seem to be on my side, everything was set up correctly. 
Is it possible that there is a problem with the Monday.com integration on your side? 
Please help ASAP. 
Thank you! 

Error
Failed to create item: Nullability mismatch on variable $itemName and argument item_name (String / String!) 
    at Object.run (file:///pipedream/dist/code/31165f13f5a9288af42adbc889a4f603304300960365769bb622a1d685591aff/code/actions/create-item/create-item.mjs:117:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.executeComponent (/var/task/launch_worker.js:286:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:783:28)
(create_item_in_applications)

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-02-16-142810.png?id=klq60e&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImtscTYwZSIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcwODA5MDE0OX0.rrGkDqqL8vgMCkT423ci2ciQEVp-BjoGrE0UjqD5yGE&signature=d3f9a046c6dea9c530868d5da168652274fde6ffd84bd1d7452070d26fb40ab2)

**Comment by andrewjschuang** [comment]
Hi,

[Monday.com](http://monday.com/) recently announced breaking changes to their API. See their [migration docs here](https://developer.monday.com/api-reference/docs/migrating-to-v-2023-10).

We already updated our components in order to comply to their new API standards.

In order for this to take effect, you will need to manually update the actions in your workflows:
Visit your workflow and click on Edit to go to the builder
Scroll to each of your Monday.com actions
Click on the Red Update button in the top right of the step
Deploy the workflow

For sources, we do not have an Update option. Rather, you have to [create a new trigger](https://pipedream.com/sources/new) and connect it to your workflow.

If you are sending API requests to [Monday.com](http://monday.com/) in custom code steps, please follow the migration guide and modify your code as needed.

Let me know if this helps,

**Comment by shtyrmer** [comment]
Hi Andrew, 

Thanks, this worked. The only thing, updating the step cleared all of the fields (and there were many), so I had to redo and retest, but except that it worked. 
BTW: special thanks for incrieasing the hight of the Column field in the step, it was a mess without, because Monday.com doesn't allow you to change field ids, it's all text01 text37 and go figure what is what :)  A higher Column field allows you to see both the name and the ID of the field. In the future, I recommend to also replace field IDs with filed Names in the column list with value inputs.
