### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by soyebamd** [PipedreamHQ/pipedream#10594]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I AM GETTING ISSUE EVERY TIME HOW TO FIX IT?

**_ReferenceErrorclientNameColumnId is not defined
   at Object.module.exports (/steps/getClientId.js:6:25)_**

Thanks

**Comment by soyebamd** [comment]
Yes

It give me error of

**ReferenceErrorclientNameColumnId is not defined
at Object.module.exports (/steps/getClientId.js:6:25)**

Here is my pipedream login Plese test and fix or let me know how to fix it.



Pipedream
username - jordan@kingtide.com
pass - hello@pipedRt!!22

The issue is in "Next Day Delivery" workflow
![issue tracker](https://github.com/PipedreamHQ/pipedream/assets/7539237/5bce3951-fd67-4368-8340-57ffd8af2efd)


Thanks

**Comment by soyebamd** [comment]
Thank you for your help!

**Comment by malexanderlim** [comment]
@soyebamd I've deleted the password that you shared above - please do not share private credentials here as this is a publicly accessible repo! I would recommend changing your password just to be extra safe. 

If you can share a link to workflow and enable sharing with support, that should be enough to start troubleshooting.

**Comment by soyebamd** [comment]
Thank you

**Comment by soyebamd** [comment]
https://pipedream.com/@divine-persuasion/next-day-delivery-p_A2CvVko

**Comment by soyebamd** [comment]
Hi I really need help on this

![image](https://github.com/PipedreamHQ/pipedream/assets/7539237/ee98083e-d745-4fb5-bfe9-fed6b31a3698)

Thank  you

**Comment by soyebamd** [comment]
Monday.com has updated there API or app that gives us error how to fix it?

**Comment by malexanderlim** [comment]
Hi Soyeb,

monday.com recently released breaking changes to their API. We've updated our components in order to comply with their new API specifications.

In order for this to take effect, you'll need to manually update the monday.com triggers and actions in your workflow.

1. Visit your workflow and click on Edit to go to the builder
2. Scroll to each of your Monday.com Actions
3. Click on the Red Update button in the top right of the step
4. Deploy the workflow

If you’re using a monday.com trigger on a workflow, you’ll need to disable and remove the old trigger, then add a new one to use the new version.

**Comment by soyebamd** [comment]
Hi,

I can't fine thsi step can please send me a screenshot

3. Click on the Red Update button in the top right of the step

Thank you

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
