### ISSUE TITLE
[FEATURE] link $return_value to next step

### ISSUE THREAD

**Issue by KenMacD** [PipedreamHQ/pipedream#1094]
Linking data between steps seems a little clunky in what I would consider to be a common 'pipe' case.  I often want to use the output from the previous step in the next step. I might have a step that loads some data, then one to filter on that data, then one to generate some output. The UI shows this with each step linked to the previous one, but to access the return value of the previous step I have to find the value in `steps.name.$return_value`. Then if I later add another filtering step in between I have to change the references in the next step.

I'm think it would  be useful to have a mapping between the previous steps return value and the input to the next step.

**Comment by dylburger** [comment]
@KenMacD I completely hear you on the use case. I'm sharing with the team since we're working on some major modifications to the workflow UX right now.

**Comment by dylburger** [comment]
@KenMacD if you had a way to reference previous steps using relative indexing, using `steps[-1].$return_value`, would that help with the core use case?

**Comment by KenMacD** [comment]
Yes, that would certainly work for my use cases. This would allow me to chain steps together and later add processing in between.

In this case I would likely only see myself using `-1` though, as the problem I'm trying to solve is allowing the addition/subtraction of intermediate steps. Of course having other possible offsets wouldn't negatively affect anything either.

**Comment by dylburger** [comment]
We've decided not to implement this, and I'll explain why. If you’re using `steps[-1]` and then you move the step to a different place, `steps[-1]['the_property_you_expect']` may not exist, and that may be harder to troubleshoot than the issue with a reference to a bad step name since it would return `undefined / None` (no error). Currently we’ll throw e.g. a `TypeError` (JS) or `NameError` (Python) that says `steps.foo` is undefined and you can’t reference a property of that object, and you can quickly map that to the actual issue since you know you renamed the step. But in the relative reference case, you would get a silent error. We believe it's better to force users to use explicit step names and be loud with failures.
