### ISSUE TITLE
[BUG] Cloudinary Upload Media Asset action doesn't work

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#11084]
Not sure if I missed a prop that's actually required, but I configured the only required prop and got this error:
![Screenshot by Dropbox Capture](https://github.com/PipedreamHQ/pipedream/assets/20780753/cf0adc52-7b90-4d04-ab3a-40831f594e2c)

Here's my configuration:
![Screenshot by Dropbox Capture](https://github.com/PipedreamHQ/pipedream/assets/20780753/deb10cdc-e513-479b-9a10-63dd202c0a35)

That step reference maps to this URL in case you want to repro exactly:
https://slack-files.com/TD5JFTFRQ-F06QCKMHVPC-8de64c7c36

**Comment by michelle0927** [comment]
@dannyroosevelt The problem is that Slack's `permalink_public` isn't a link to the actual image file.

- `permalink_public` has this format: `https://slack-files.com/{team_id}-{file_id}-{pub_secret}`
- The direct link has this format: `https://files.slack.com/files-pri/{team_id}-{file_id}/{filename}?pub_secret={pub_secret}`

I couldn't figure out a way to get the direct link "directly" from the Slack API, but you can build it from `permalink` and `permalink_public` like so:

<img width="897" alt="Screenshot 2024-03-20 at 12 31 18 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/06221296-d5ea-4382-9979-58d1ff79f808">

**Comment by dannyroosevelt** [comment]
Ah I see, thank you Michelle! Hero
