### ISSUE TITLE
HubSpot - Create Contact (Upsert) not functioning as expected

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11236]
### App
HubSpot

### Summary:
Unable to update a contact when it already exist

### Details:
I want the workflow to update a contact when it already exists in HubSpot, otherwise just create it.
I actually requested this functionality a few months ago and thankfully you developed it. More details can be found here: https://github.com/PipedreamHQ/pipedream/issues/8749.

It worked well until a few days ago and you can find the error messages in my event history

Please let me know if you need more information.

Thanks,
Henry

### Screenshots:
No screenshots included

**Comment by malexanderlim** [comment]
**Component Dev, to reproduce, you can test with Component Dev Test Account 2. Please ping @malexanderlim for access.**

When Hubspot - Create Contact is used with Update If Exists = True, the expected behavior is that the contact is updated if it already exists. In this scenario, I am getting a 409 error that the contact exists, without the updating behavior.

Test email: bh@hubspot.com, I attempted to change the phone number.

```AxiosError - Request failed with status code 409
{"message":"Contact already exists. Existing ID: 51","identityProfile":{"vid":51,"identity":[{"value":"bh@hubspot.com","type":"EMAIL","timestamp":1696530378178,"isPrimary":true},{"value":"8a88f137-973f-4888-ba09-7053bb7bea1e","type":"LEAD_GUID","timestamp":1696530378632}],"linkedVid":[],"isContact":true,"savedAtTimestamp":1696530378635},"errors":[{"message":"A contact with email bh@hubspot.com already exists. Existing ID: 51","in":"email"}],"status":"error","correlationId":"c87a2e03-212b-42ec-bdb5-c38f952ad4b6","category":"OBJECT_ALREADY_EXISTS","error":"CONTACT_EXISTS"}```
