### ISSUE TITLE
[BUG] "Airtable : Update specific record" action has a default base id

### ISSUE THREAD

**Issue by zeshhaan** [PipedreamHQ/pipedream#1125]
**Describe the bug**
Airtable's Update specific record action has a default base id set in `code`. Would be great if we could have a field instead to insert our own base id.

**To Reproduce**
1. Go to '.actions'
2. Click on 'Airtable : Update specific record' action
3. Scroll down to the 'code part and expand it'
4. See error -> on line 3, the second param should be a hardcoded base id.

**Comment by dylburger** [comment]
@zeshhaan that action was created by a member of our community, and I've hidden it from the product because (for this reason and others) it doesn't meet the quality standards we set for actions. 

However, you can use the **Update Records** action - take a look at this [example workflow](https://pipedream.com/@dylburger/airtable-update-records-example-p_OKC87z/edit). We're planning to ship some major updates to actions soon (including more Airtable actions), as well.

Let me know if this works OK for you in the meantime.

**Comment by zeshhaan** [comment]
@dylburger Got it. Yeah, this works for me.

**Comment by dylburger** [comment]
Great thanks
