### ISSUE TITLE
[Components] frameio

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11389]
# frameio
## URLs
- https://developer.frame.io/api/reference/
#### URLs
- https://developer.frame.io/api/reference/operation/createWebhookForTeam/
#### Prompt
Emit new event when an asset is uploaded. Required props: asset ID.
#### URLs
- https://developer.frame.io/api/reference/operation/createWebhookForTeam/
#### Prompt
Emit new event when a new comment is left on an asset. Required props: asset ID, comment ID.
#### URLs
- https://developer.frame.io/api/reference/operation/createWebhookForTeam/
#### Prompt
Emit new event when a new project is created. Required props: project ID.
#### URLs
- https://developer.frame.io/api/reference/operation/createComment/
#### Prompt
Sends a comment to a certain asset in frameio. Requires 'asset_id' prop to specify the asset and 'message' prop to input the comment. Option to add 'timestamp' prop to note the time-stamp of the comment.
#### URLs
- https://developer.frame.io/api/reference/operation/createProject/
#### Prompt
Establishes a new project on frameio. Title of the project needs to be inputted in the 'name' prop. Can optionally specify 'team_id' prop to determine the team that the project should be assigned.
#### URLs
- https://developer.frame.io/api/reference/operation/updateAsset/
#### Prompt
Modifies an existing asset in frameio. Requires 'asset_id' prop to determine which asset to update and 'update_values' prop, composing of values that need to be updated.

**Comment by GTFalcao** [comment]
@vunguyenhung after some further digging, I've noticed that `Create Comment` requires the asset to be a `file`, while `Create Asset` requires the (parent) asset to be a `folder`. Attempting to create a comment on a folder, or to create an asset under a file, returns a 422 error.

The 'simple search' endpoint being used before only returned files - that's why Parent Asset ID was not using async options. I've changed the request to the 'advanced search' endpoint you suggested, and also applied filters so that each action only lists the correct asset type in the async options.

I've also added the Search Assets action you requested, with filtering files/folders as an additional option.
