### ISSUE TITLE
[APP] Ringba

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11654]
### App
ringba
https://developers.ringba.com/

**Comment by techexpert004** [comment]
I want to integrate Ringba and twillio with pipedream

My requirement is :

We do Pay Per Call marketing for home services in the US.
When people land on one of our websites, they are invited to call an 800 number to book a service.
Their calls are routed to a pool of service providers (call buyers) based on the callers locations and various other parameters.
Sometimes, calls are wasted because our buyers are unable to take the call or don't serve the caller's location area.
We have the callers' numbers.

We need your help to :
1. automatically send them a text message to invite them to call again.
2. callbacks, made by the receiver to the number that was used to send a text message, must be redirected to one of our website's numbers.

**Comment by sergio-eliot-rodriguez** [comment]
Reached out by mail.
Copied sergio@pk, michael@pd, integrations@pd

**Comment by sergio-eliot-rodriguez** [comment]
>  We are reviewing your offer and will let you know if we are interested.

**Comment by malexanderlim** [comment]
@techexpert004 , Ringba is currently integrated on Pipedream. If there are specific triggers or actions for Ringba that you're looking for, please request them at https://pipedream.com/support.
