### ISSUE TITLE
[Components] twenty

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11736]
# twenty
## URLs
- https://docs.twenty.com/
#### Prompt
Emit new event when a record is created, updated, or deleted. No required or optional props needed.
#### URLs
- https://docs.twenty.com/rest-api/core#/operations/createOneWebhook
#### Prompt
Create, update, or delete a single record in Twenty. Required props are 'recordId' for updating or deleting, and 'recordData' for the new or updated record information. An optional prop 'actionType' can specify whether to create, update or delete. The recordId prop is the schemas fields in components of the URL response 
#### URLs
- https://docs.twenty.com/rest-api/core#/operations/GetOpenApiSchema

**Comment by luancazarine** [comment]
Hi @vunguyenhung. The fields are created dynamically, so it is very difficult to deal with each case. in terms of Ids, there is no way to know which is which and create the asynchronous function, and in the case of attachments, I removed all props that are of the array type, since they are always some relationship that already exists an endpoint for it. at least to facilitate the release of the first version.

![image](https://github.com/PipedreamHQ/pipedream/assets/5638699/4de20b98-4ff6-4eff-b422-764e845be3f6)
