### ISSUE TITLE
[BUG] Cron syntax incorrect

### ISSUE THREAD

**Issue by oliviermills** [PipedreamHQ/pipedream#1213]
Its currently 10.38am yet it says it will run only at 11am. Is the english version of the syntax correct? I understand pipedream doesn't support seconds. The intention here is to have it run every minute between 6am and 11pm
![image](https://user-images.githubusercontent.com/6075303/117579960-b0189380-b0b2-11eb-93c4-40f5b721cdbb.png)

**Comment by dylburger** [comment]
@oliviermills thank you for the report, I have a fix that should go out tomorrow.

This should have only affected the display of the next run in the **Next Event** section - the job itself would have run. The library we used to display this next run — `cron-parser` — failed to correctly parse the `0/1` syntax in the version we were using. That's been corrected now. Technically, the `*/1` syntax is equivalent and should work:

```
*/1 6-22 * * *
```

I'll let you know when the fix is out.

**Comment by dylburger** [comment]
A fix for this is going out now.
