### ISSUE TITLE
mongobd integration 

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12152]
### App
mongobd integration 
https://cloud.mongodb.com/v2/63d4c13df03f9f021e6ab9ba#/metrics/replicaSet/6656a9eff8d0e167a0a8c65e/explorer/PizzaHub/pizzadatas/find

### Sources
i want to mongodb interagtion

**Comment by sergio-eliot-rodriguez** [comment]
MongoDB is integrated: https://pipedream.com/apps/mongodb

Note that this is a premium app

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/10af077d-047d-4094-9cd6-c1fff0133a54)


In order to be able to use a premium app, you need to be an Advanced plan Pipedream user:

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/cfbbdb43-bb2c-4b30-be2c-c39c6d8936da)


You can check details on pricing at:
https://pipedream.com/pricing
