### ISSUE TITLE
[FEATURE] Gmail & Gmail Developer App - Improve Send Email action to allow attachments from tmp dir

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#12339]
**Is your feature request related to a problem? Please describe.**
Currently, the Gmail and Gmail Developer App - Send Email action only accept attachment from public URL

![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/9a44e10b-2763-4722-b675-cfa6f90ba8dd)
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/d63a3920-bd59-4e77-ad0b-40a6f35703d9)

**Describe the solution you'd like**
Improve the attachments prop to accept paths from tmp dir

**Do you have a workaround?**
No

**Additional context**
Raised by a customer: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1717752091199239

**Comment by digbyk** [comment]
This would be really helpful. I've been trying various other ways to email a file I created, like uploading it to Google Drive and then attaching it, but there's always a problem with authentication and an auth html page gets emailed instead. I can't put the file onto a public URL because it contains sensitive data (this seems to be the requirement for the Google Mail attachment location).
(I raised this feature request on Slack earlier).
