### ISSUE TITLE
[Components] otter_waiver

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12539]
# otter_waiver
## URLs
- https://api.otterwaiver.com/docs/
#### Prompt
Emit new event when a participant checks into an event. Required props include event name. Optional props might include check-in time
#### URLs
- https://api.otterwaiver.com/docs/
- https://api.otterwaiver.com/docs/getting-started
- https://api.otterwaiver.com/docs/authentication
- https://api.otterwaiver.com/docs/waivers
- https://api.otterwaiver.com/docs/participants
- https://api.otterwaiver.com/docs/webhook
- https://api.otterwaiver.com/docs/references/waiver
- https://api.otterwaiver.com/docs/references/participants
#### Prompt
Emit new event when a new signee is created. Required props are signee details. Optional props could include signee preferences or subscriptions
#### URLs
- https://api.otterwaiver.com/docs/authentication
- https://api.otterwaiver.com/docs/waivers
- https://api.otterwaiver.com/docs/participants
- https://api.otterwaiver.com/docs/webhook
- https://api.otterwaiver.com/docs/references/waiver
- https://api.otterwaiver.com/docs/references/participants

**Comment by luancazarine** [comment]
> Hello everyone, I have tested this PR and there're some test cases failed or needed improvement.
> 
> Please check the test report below for more information https://vunguyenhung.notion.site/Components-otter_waiver-b3b9609fa9c74de3a7ed397f6ecb62dc

Hi @vunguyenhung, These errors occur because the profile was not completed.
![image](https://github.com/user-attachments/assets/2163d182-4e33-4a9c-a0ea-055a7c6dfd07)
![image](https://github.com/user-attachments/assets/63207810-20d6-4d73-8df1-55f1ef3b21bf)

I have another account with completed profile and the sources work fine!
![image](https://github.com/user-attachments/assets/6e26a15a-fb1a-41dc-b91e-26abe5721d94)
