### ISSUE TITLE
[APP] Railsr - Integrate using OAuth Client

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#13681]
**Name of app / service**
Railsr

**Link to developer documentation**
https://docs.railsr.com/docs/guides/ab1cd683b4a9b-creating-an-o-auth-client

**Is lack of support preventing you from building workflows, or do you have a workaround?**
API Key integration is deprecated, we need to integrate using OAuth instead
![image](https://github.com/user-attachments/assets/b73457f0-b2b9-41c6-a8c9-221ecb37a640)

The link to create API Key show Something went wrong error
![image](https://github.com/user-attachments/assets/77f3eca3-e9a4-403a-a4af-9590f98c3f50)

**Comment by malexanderlim** [comment]
@sergio-eliot-rodriguez , can you take a look at the feasibility of this?

**Comment by sergio-eliot-rodriguez** [comment]
Yes, I think this is feasible.
I started looking into it, and the oauth flow is failing with "invalid client_id". Since the OAuth Client page within Ralsr allows the user to select Play/Live environment, I suspect their guides are using the Live environment, but for our account the Live option is disabled, so the client_id was generated for the Play environment. I am reaching out to Railsr support to see if their oauth endpoints change depending the environment.

**Comment by sergio-eliot-rodriguez** [comment]
Just updating the status on this.

First reached out attempt via email bounced back. It suggested a support portal.
The support portal wouldn't allow me to login because it said no account existed.

What I did is, create a new Railsr account, and from there access the support portal. I have logged a request for support now about oauth endpoints.

**Comment by sergio-eliot-rodriguez** [comment]
They replied about 1 month ago said they were looking on this matter, but haven't heard back again. I followed up today on this.

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim railsr was resubmitted as an oauth app now, i used an app slug for repurposing `test_apps_for_switching_appslug_002`
i wasn't able to gen the json web token which is an auth cred in test request using the official guide from Railsr; instead, I used some code their support shared
