### ISSUE TITLE
Notion - updated page trigger fails to activate

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13773]
### App
Notion

### Summary:
80% of the time, the Notion updated page trigger fails to activate

### Details:
Dear Pipedream Support Team,

I am reaching out for assistance with a critical issue I am experiencing with the Notion updated page trigger in Pipedream, which I use daily for our workflow automations.

Currently, I have set up triggers to activate on updates to a specific database property, for example the "Submitted Time" property. Unfortunately, this trigger is highly inconsistent and often fails to fire, which has become a significant impediment to our operations.
In our company, we utilize Notion as both a CRM and a frontend interface. Our workflow automations are designed to function as follows:
	1.	A user uploads a document to a Notion page property.
	2.	The user then clicks a "Submit" button property.
	3.	This action switches a triggered checkbox property to true and updates the "Submitted Time" property.
These properties are intended to act as triggers for our workflows, but I have found that the updated page trigger does not work approximately 80% of the time. This unreliability is causing disruptions in our processes, especially since we have set up multiple triggers across various databases and workflows that rely on this Notion trigger.

Given the critical nature of these automations, I would greatly appreciate any insights or solutions you could provide to help resolve this issue. Thank you for your assistance.

### Screenshots:
No screenshots included

**Comment by freivokh** [comment]
I believe I’ve identified the problem: the trigger relies on the last_updated_time property from Notion instead of checking the differences in properties across polls. This approach causes issues because I think Notion batches multiple changes to a single last_updated_time, lacking precision and missing changes. Property values should be checked independently between polls rather than depending on last_updated_time as a filter.

Loom demonstrating the issue:
https://www.loom.com/share/61d538748e4e42b7b3a892ba4f737da0

Pipedream devs, please let me know if you need any more info as I was working on modifying the trigger with the help of chatGPT.
