### ISSUE TITLE
Increase invocation limit for public projects

### ISSUE THREAD

**Issue by anondev-sudo** [PipedreamHQ/pipedream#1413]
Hello, could you please increase invocation limit for public projects? For example github includes unlimited action minutes for free when your repository is public. 
Why you don't support users who make public integrations? 
I don't think that it should be unlimited but it may be increased. Or that first 100 daily invocations on public projects will be not counted to your account's invocation limit.

**Comment by dylburger** [comment]
@anondev-sudo can you tell me more about the specific project you maintain?

**Comment by anondev-sudo** [comment]
This should be for every public project (integration)

**Comment by anondev-sudo** [comment]
Even failed requests are counted to this limit, just successful invocations should be counted, for example if you use return in nodejs code, invocation should be not counted when your code hasn't finished to the last step

**Comment by dylburger** [comment]
Thanks. We do provide higher quota to teams running open-source projects, to non-profits, etc. Can you clarify what you mean by "public project (integration)"? 

Re: your second note, were you aware that we only count one invocation per workflow execution, regardless of the number of steps you run? Even if your workflow runs 10 steps, that only counts as a single invocation. If the workflow exits early and doesn't run the last step, it's still only a single invocation.

We also provide additional quota to users who develop [event sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/) or [actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/), or who write blog posts or other documentation. Would you be interested in that?

**Comment by anondev-sudo** [comment]
> If the workflow exits early and doesn't run the last step, it's still only a single invocation.

It should be counted as 0 invocations as the workflow was not successful.

And also is global error workflow counted to the limit?
And when workflow has error and email is sent is the original workflow counted?

**Comment by anondev-sudo** [comment]
Also when you have HTTP webhook invocation is counted for every request method, it should be counted just for POST, I also return it in nodejs code but its still counted 
```
if(steps.trigger.event.method !== "POST") return; // dont run next steps when its not POST request
```

Also why is invocation counted also for source and workflow, so one is counted as 2 invocations.

![image](https://user-images.githubusercontent.com/85408287/126297989-b7ac9b45-fb53-4ca7-813d-f0c42b7e0072.png)

![image](https://user-images.githubusercontent.com/85408287/126298075-15d0449a-896b-4858-acab-e8ae78e7a9a2.png)

**Comment by dylburger** [comment]
Thanks for all the feedback. It sounds like you're most interested in the ability to filter data prior to triggering your workflow, which we're tracking in #556 . I'd recommend following that issue for further updates.

To answer your other questions:

* Yes, if you're using an event source and a workflow together, we count two invocations, because the event source runs as a separate resource. 
* The global error workflow does trigger an invocation when run. We're also planning to improve this so that default errors aren't handled by a workflow (and we just send you an email without charging you an invocation).

**Comment by anondev-sudo** [comment]
It should be counted just as one invocation when you have event source and workflow.
Or how to make that it will be counted just as one invocation?

**Comment by dylburger** [comment]
We don't plan to change the invocation logic tied to sources at the moment, but we are planning a suite of improvements related to invocations:

- Improve the HTTP API trigger to support concurrency and throttling, removing the need to use the HTTP / Webhook sources in that context
- Improve filtering logic so sources / triggered aren't triggered in as many conditions
- Fix how error invocations are counted

Those are tracked separately in some of the issues I linked to above, so I'm closing this ticket since it duplicates those.
