### ISSUE TITLE
In-built Report Button that send the bug straight to both PipeDream team and Action Author

### ISSUE THREAD

**Issue by cuongtqtran** [PipedreamHQ/pipedream#142]
**Is your feature request related to a problem? Please describe.**
Some public actions may be outdated and invalid in some time because of many reasons (API change, host change,...). If having a bug report button below the step action, It is convenient for the Pipedream team and the author can prompt fix.

**Describe the solution you'd like**
Add a report button and the error below the step.

**Comment by dylburger** [comment]
@cuongtqtran since actions are now hosted in this GitHub repo, does that and the new "View code and contribute on Github" link attached to component actions address this use case for you? That allows us to centralize feedback / issues on actions in one place.

<img width="637" alt="Screen Shot 2021-05-18 at 10 34 18 PM" src="https://user-images.githubusercontent.com/242668/118761504-5e49d900-b829-11eb-9729-38ad09b5206d.png">
