### ISSUE TITLE
Wrike

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14292]
### App
Wrike

### Summary:
Error finding FolderID in Workflow Action Wrike New Task

### Details:
When i click the FolderID i get the following message:
{"errorDescription":"Access token is unknown or invalid","error":"not_authorized"}

Account is successful connected

After forwarding this error to Wrike i get the following answer:
"It appears that the error is due to an incorrect Wrike base URL being sent by Pipedream. Could you verify that all requests are made using the base URL https://app-eu.wrike.com/api/v4/?"

### Screenshots:
https://www.loom.com/share/f49d9d298f994d77835a6503a9ba8a83
![Screenshot](https://storage.tally.so/private/Screenshot-2024-10-14-154914.png?id=D7O6Pp&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkQ3TzZQcCIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcyODkxMzk2NH0.ZCccLAZFNBfS25xSKdTn0LpRtjO7e7ZQARZxewd55WA&signature=47817acc4544acc441a13a65f2d4155304bb178c0b5f55db2935f1a86bc54372)

**Comment by dannyroosevelt** [comment]
@vunguyenhung actually the app configuration already supports it, this is a bug in the component code:
https://github.com/PipedreamHQ/pipedream/blob/master/components/wrike/wrike.app.mjs#L75

We're currently extracting the host during the OAuth flow -- for example,
```
  "host": "app-us2.wrike.com",
```
So that value should be accessible to the components like this:
```
this.wrike.$auth.host
```
