### ISSUE TITLE
[ACTION / SOURCE] Github new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1430]
Is there a specific app this action is for?
Github

Please provide a link to the relevant API docs for the specific service / operation.
https://docs.github.com/en/rest/reference

### Triggers
- New Gist
- New Mention
- New Notification
- New Organization
- New Repository
- New Review Request
- New Security Alert
- New Team
- [Webhook Events](https://docs.github.com/pt/developers/webhooks-and-events/webhooks/webhook-events-and-payloads)

### Actions
- Create issue 
- Create issue comment
- Search issues and pull request
- Get repository
- Update issue

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by andrewjschuang** [comment]
@dannyroosevelt I think I accidentally moved this issue around and now I'm not sure where it's supposed to be?

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt I think I accidentally moved this issue around and now I'm not sure where it's supposed to be?

Were you working on this? I don't see any PR attached to it but it looks like it was in review at one point?

**Comment by sergioeliot2039** [comment]
> > @dannyroosevelt I think I accidentally moved this issue around and now I'm not sure where it's supposed to be?
> 
> Were you working on this? I don't see any PR attached to it but it looks like it was in review at one point?

Me, Sergio, I currently am not working on this issue ([ACTION] Github new actions(https://github.com/PipedreamHQ/pipedream/issues/1430#))
It was me who orked on the initial implementation of all the actions related to this issue, I created the [Pull Request 1715](https://github.com/PipedreamHQ/pipedream/pull/1715) which was reviewed by @js07 on Oct 7th 2021. 
This PR has the title "GitHub resolve conflics" because there was a conflict indicated by Github, I thought it was best, to create a new pr for solving these conflicts. My original branch at my fork is named "new-github-actions", and from this it was created off "github-resolve-conflics".
I haven't resumed work on Github actions since Oct. 21 mainly bcs of my assigment on the app store project, other app componets that i started first i.e. Mailchimp, Sendgrid.
![image](https://user-images.githubusercontent.com/25184117/158668798-f3998c9d-8b2b-4d7e-be68-8fa61b373d43.png)
Hope this input is helpful to situate on the status of Github actions component development.
To-Do looks as the right project card to be in 
JM2C,
SR

**Comment by lcaresia** [comment]
@Hassan-Abbas-SQA Yes, I removed some triggers and moved all to just one source.

**Comment by Hassan-Abbas-SQA** [comment]
@Hassan-Abbas-SQA testing

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia New Organization trigger is also not emitting when user is added to an organization

**Comment by lcaresia** [comment]
@Hassan-Abbas-SQA I made some updates, you can teste the New Mention trigger, about the `new-organization` trigger you can skip for now.

[More context here](https://github.com/PipedreamHQ/pipedream/pull/2938)

**Comment by dannyroosevelt** [comment]
This is ready for release!
