### ISSUE TITLE
Google Reviews Notifications

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14369]
### App
Google Reviews Notifications
https://developers.google.com/my-business/reference/notifications/rest

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim it turns out this issue about Google Reviews Notficiations points to Google My Business Notifications.
I started to look into this and it uses a different API & Service than plain Google My Business, so for a given GCP owner account of the OAUth 2.0 client accessing this APIs, different options under API & Services need to be enabled.

Service endpoint for Google My Business Notification is `https://mybusinessnotifications.googleapis.com`
where us Service endpoint for Google My Business is `https://mybusinessaccountmanagement.googleapis.com`

now when it comes to OAuth 2.0 scopes, they share the same scope

For [Googe My Business app at Pipedream](https://pipedream.com/apps/google-my-business)
> Pipedream securely stores and automatically refreshes the OAuth tokens so you can easily authenticate any Google My Business API.
> 
> Pipedream requests the following authorization scopes when you connect your account:
> 
> https://www.googleapis.com/auth/business.manage

For [Google My Business Notification in its documentation](https://developers.google.com/my-business/reference/notifications/rest/v1/accounts/getNotificationSetting)

> Authorization scopes
> Requires the following OAuth scope:
> 
> https://www.googleapis.com/auth/business.manage

So I think this shouldn't be an app but rather new components would need to be implement within existing Google My Business.

thoughts?

**Comment by sinklair** [comment]
Not sure if you are aware but Google recently moved review notifications to a Pubsub model where you need to create a pubsub service for real time notifications. https://developers.google.com/my-business/content/notification-setup

Not sure how this might work in Pipedream or if it's even an option.

**Comment by malexanderlim** [comment]
Hi @sinklair , I'm looking into this as an option, but in the meantime - we have a polling trigger that emits events when there are new reviews on a given business (https://pipedream.com/apps/google-my-business/triggers/new-review-created) - would this work for your use case, or do you have a specific use case in mind for realtime notification for reviews?

As a similar example, we recently implemented Pub/Sub notification for [Gmail - New Mail](https://pipedream.com/apps/gmail/triggers/new-email-received) realtime notifications which requires additional set up to configure. I can look into the feasibility of having something similar for Google Business notifications.

**Comment by sinklair** [comment]
That would work for our use case. We want to send notifications to a slack
channel whenever a review is added. Additionally, we want to send the
reviews to Postgres to allow us to feed them our main web app. Ideally, it
wouldn't be timer based since that has a high chance of using up all of our
credits but it's probably good enough for now if we schedule it
less frequently.

Thanks.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment]
I reopened thisone, it was closed automatically

**Comment by malexanderlim** [comment]
@sinklair , I wanted to check in to see if you were able to get the polling trigger for New Review working on your end - the Pub/Sub configuration for webhook notifications is more complex and requires additional setup, and I'd prefer to keep the polling trigger for simplicity for the end-user. If this will work for you, I'll close out this ticket for now unless there is a specific need for realtime webhooks on reviews.

**Comment by malexanderlim** [comment]
Awesome, thank you for confirming @sinklair ! I'm going to close this out for now, but if there is a strong requirement for webhook triggers for this in the future, we can revisit this ticket and prioritize accordingly.
