### ISSUE TITLE
[Components] gainsight_nxt

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14373]
# gainsight_nxt
## URLs
- https://support.gainsight.com/gainsight_nxt/API_and_Developer_Docs
#### Prompt
Create or update a company record. Users need to configure the 'All Fields' props with the relevant company information. If the company exists, this action updates the information; if not, it creates a new record.
#### Prompt
Create or modify a custom object. Configurable via 'All Fields' props, the user can specify the custom object elements. If it exists, the data gets updated; otherwise, a new custom object is created.
#### Prompt
Add or update a person's record. 'All Fields' props allow dynamic input of a person's data. In case of an existing profile, the data is updated. If not, a new person's profile is generated.

**Comment by GTFalcao** [comment]
Regarding the company optional fields, since it is not clear in the documentation and API behavior how they are supposed to be sent differently, I've replaced these props with an optional "additional fields" prop, for the user to enter additional fields if needed, in whichever format the business rule may require.

Regarding custom object creation, it seems some of the standard objects work with this action (e.g. company itself), but most do not. So I've restored the filter that lists only custom objects as options (since the action is meant for custom objects anyway). However, I'm unable to log into the platform to create any custom objects to test this - the credentials in 1PW don't seem to work for me. Have you had success logging into the platform? @vunguyenhung

**Comment by GTFalcao** [comment]
The field name provided is probably wrong - for my custom object fields the suffix `__gc` was always present.

I will add an alert prop to remind the user to check this, as well.
![image](https://github.com/user-attachments/assets/39ed8972-616a-41d2-84e5-8d841ab0f0a5)
