### ISSUE TITLE
Plivo

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14478]
### App
Plivo
https://developer.signalwire.com/guides/fax-to-email/

### Sources
webhook

### Actions
send email

**Comment by sergio-eliot-rodriguez** [comment]
Can the user elabore more on the user case?
I'm confused here, because the link provided doesn't point to a "Plivo" app, but to documentation within SignalWire, for which we have a base integration: https://pipedream.com/apps/signalwire

As of the "send mail" piece, the example from the link is  about the send mail action fro Mailbox, which is supported: https://pipedream.com/apps/mailgun/actions/send-email

**Comment by sergio-eliot-rodriguez** [comment]
There is a Pilvo app in the app store too: https://pipedream.com/apps/plivo

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
