### ISSUE TITLE
[ACTION] AWS new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1458]
**Is there a specific app this action is for?**
AWS

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.aws.amazon.com/sdk-for-javascript/

**Run Code** | Write javascript code and execute it in a Lambda function that we provide the source for
**Invoke Function** | Invokes a prebuilt function asynchronously providing only data
**Create Bucket** | Creates a new bucket
**Get File** | Gets a file from a bucket
**Upload File** | Uploads a file to a bucket
**List Files** | List all files in the specified path
**List Folders** | List all folders in the specified path

**Comment by dylburger** [comment]
@andrewjschuang Can you tackle #2150 along with these actions?

**Comment by andrewjschuang** [comment]
> @andrewjschuang Can you tackle #2150 along with these actions?
Yep, np

**Comment by DilanAthukorala** [comment]
@andrewjschuang 
Observing error when trying to deploy app into Pipedream
![image](https://user-images.githubusercontent.com/102980146/163761794-9780c837-aae3-4df1-ae96-47b43a3ef009.png)

**Comment by andrewjschuang** [comment]
> @andrewjschuang Observing error when trying to deploy app into Pipedream

Hey Dilan, this happens because all the imports summed up goes beyond Pipedream's size limit. Hadn't been able to think of a solution until now, but it will take some heavy refactoring of the directory files/structure

**Comment by andrewjschuang** [comment]
@DilanAthukorala fixed the issues!

**Comment by vunguyenhung** [comment]
Hi @andrewjschuang and everyone, all test cases has passed! Ready for release!

Please note that the test exclude the expression and curly brace issue on JSON string input described [here](https://pipedream-users.slack.com/archives/C01E5KCTR16/p1652115042492479). The issue will be fixed in another ticket!

Refer to the test report here for more information
[AWS_Test_Report_9_May_0028.pdf](https://github.com/PipedreamHQ/pipedream/files/8653887/AWS_Test_Report_9_May_0028.pdf)
