### ISSUE TITLE
[ACTION] Digital Ocean new actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#1535]
**Is there a specific app this action is for?**
Digital Ocean

**Please provide a link to the relevant API docs for the specific service / operation.**
https://docs.digitalocean.com/reference/api/api-reference/

Add SSH Key: Adds a new SSH key to your account
Create Domain: Creates a new domain with a name and IP address.
Create Droplet: Creates a new Droplet in your account.

**Comment by alysonturing** [comment]
**Digital Ocean** requires other authentication method for **Spaces** different from the rest of their environment.
Because they use the same protocol as S3, 
They're asking for `accessKey` and  `secretKey` instead of `oauth_access_token`

<img width="612" alt="image" src="https://user-images.githubusercontent.com/103650302/166485093-da1eba2b-97e8-4a1f-91b2-8bf90443a602.png">

**Comment by dannyroosevelt** [comment]
This is ready for release!
