### ISSUE TITLE
[QUESTION] Cancel a workflow from another workflow

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#1571]
**Is there a way to cancel a workflow from an other workflow ?**

I've setup a flow that send an email when a new message is sent on a slack channel.
I want this email to be delayed so that if the user remove/update the message from slack, the email won't be sent.

My idea is to have a second workflow triggered on message remove/update that kills the other workflow. If this is not possible, is there a way to share data between workflow without using a third party app like google sheet or airtable ?

**Comment by dylburger** [comment]
@LucBerge we operate a [task scheduler](https://github.com/PipedreamHQ/pipedream/issues/404) event source that allows you to schedule the execution of events. That doesn't support task cancellation today, but I'd recommend following that issue since it'll be the best way to solve this once we do.

In the meantime I have two suggestions:

* I wrote an event source that [exposes a task scheduling API on top of AWS](https://github.com/PipedreamHQ/pipedream/tree/master/components/aws/sources/new-scheduled-tasks). This requires an AWS account to run, but it creates all the resources for you, and you simply interact with the task scheduler via HTTP API. It supports task cancellation. If you're familiar with AWS, that would be my recommendation.
* You can use [workflow state](https://pipedream.com/docs/workflows/steps/code/state/) to store any JSON-serializable data within a workflow. You can't share that directly with another workflow, but I'll often create an HTTP-triggered workflow that can store / retrieve data from `$checkpoint`, effectively acting as a REST API on top of workflow state.

Let me know if that's helpful.

**Comment by LucBerge** [comment]
@dylburger Yes, it help. Thanks for the answer. 

Since I'm already using airtable and I don't want to use AWS, I'm gonna creat a table of message id to be sent. If the id is still in the table after 5 min, the message will be sent. A 2nd workflow triggered on update/remove will remove the id from the table. Easy trick to share data between workflows
