### ISSUE TITLE
[ACTION] Create new Trello card

### ISSUE THREAD

**Issue by eeemptyy** [PipedreamHQ/pipedream#1700]
**Is there a specific app this action is for?**
Trello https://trello.com

**Please provide a link to the relevant API docs for the specific service / operation.**
To create a new card in trello board
> https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-cards-post

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
Actually @eeemptyy , I realized we have [a PR that includes this action](https://github.com/PipedreamHQ/pipedream/pull/1639), which we'll be reviewing and publishing soon.

I'm closing this specific issue since we're tracking there. Please follow that PR if you don't mind, and you'll get notified when it's merged to `master` and published to Pipedream!
