### ISSUE TITLE
[FEATURE] Dockerfile for easy deployment

### ISSUE THREAD

**Issue by nileshtrivedi** [PipedreamHQ/pipedream#1889]
I'd like to self-host Pipedream. For many PaaS (like CapRover or Amazon ECS), it will be very helpful if Pipedream comes with a Dockerfile that builds the image and runs all necessary processes in a consistent manner.

This will also help the development by providing a consistent environment with all the dependencies.

Edit: It looks https://github.com/PipedreamHQ/pipedream/issues/954 needs to be fixed either before or in conjunction with this.

**Comment by dylburger** [comment]
@nileshtrivedi if you don't mind, I'm going to close this and merge it with #954. Since that work is some time out, I'd like to track all the requests re: self-hosting in a single issue. But since this issue is linked to that one, we'll note the feedback re: being able to run Pipedream from a `Dockerfile`.
