### ISSUE TITLE
Investigate ERPNext integration

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1901]
This is issue was raised from the community [forum](https://pipedream.com/community/t/erpnext-step-does-not-authenticate-correctly/1566)

**Comment by jcortes** [comment]
These are my observations:
1. I installed the framework using docker as per [documentation](https://github.com/frappe/frappe_docker) using docker in the cloud.
2. I've created my own `api-key/api-secret` using the docker through the Web Site that docker publishes using [Play With Docker](play-with-docker.com) according to the docs
3. I've connected to `ERPNext` Pipedream's app setting all variables as they are
4. I've created a Workflow with an HTTP API Trigger followed by a Node.js code with ERPNext
5. Wrote the following code in Node.js

```javascript
async (events, steps, auth) => {
 return require("@pipedream/platform").axios(this, {
    url: `${auths.erpnext.base_url}/api/method/frappe.auth.get_logged_user`,
    headers: {
      Authorization: `token ${auths.erpnext.api_key}:${auths.erpnext.api_secret}`
    }
  }
});
```
6. It returned the expected value successfully 


As an improvement in the initial connection setup with ERPNext this is what I would suggest in order to be more clear with how to use the initial values

Your Frappe Base URL is `https://{your frappe instance}` -- such as `https://demo.erpnext.com`.
Please also see the docs on how to generate a token [here](https://frappeframework.com/docs/v13/user/en/guides/integration/how_to_setup_token_based_auth) and how to make a request using [Token Based Authentication](https://frappeframework.com/docs/v13/user/en/guides/integration/rest_api/token_based_authentication).
