### ISSUE TITLE
[BUG] Viewing a specific workflow in Chrome on MacOS (M1 Pro) crashes the tab after consuming a ton of memory

### ISSUE THREAD

**Issue by kyen99** [PipedreamHQ/pipedream#1908]
**Describe the bug**
When I view the workflow detail page for a specific workflow in my account, if there is any history, the page eventually uses up all system memory until the Chrome tab crashes. If I immediately clear the workflow history and reload the page, the problem seems to be avoided.

**To Reproduce**
1. Go to this specific workflow: https://pipedream.com/@employbridge/employgig-voila-analytics-p_2gCgY5g/edit
2. Wait for only a minute. You'll notice the UI responsiveness slows as the workflow history is loaded
3. Watch Chrome memory. On my M1 Pro Macbook Pro with 32gb the chrome tab eventually used up 15gb before Chrome reported the tab as unresponsive.
4. Tab will eventually go blank and then crash with the "Aw Snap!" screen.

**Expected behavior**
I expect the workflow detail page to remain responsive regardless of whether there is any workflow history or not. All other workflows in my account behave normally.

**Screenshots**
These aren't super helpful, but illustrate what happens
![image](https://user-images.githubusercontent.com/686005/142738292-d8d2d42d-35a5-41f3-a864-44e1c5ce6060.png)
![image](https://user-images.githubusercontent.com/686005/142738403-501d2013-3abc-466f-a2c0-d4e3a2fd259b.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey (Macbook Pro M1 Pro 32gb)
 - Chrome (Silicon)
 - Version 96.0.4664.55 (Official Build) (arm64)

**Additional context**
Immediately clearing the workflow history seems to eliminate the problem, so I assume it may have something to do with loading the workflow history.

**Comment by dylburger** [comment]
@kyen99 Thanks for reporting. Would you mind clicking the **Share** button at the top-right of the workflow and share it with dylan@pipedream.com?

**Comment by kyen99** [comment]
> dylan@pipedream.com

Done!

**Comment by dylburger** [comment]
@kyen99 Thank you. We looked into this more. A couple of things combined to cause this issue.

First, it looks like you're returning a large set of data from the `getEvents` step and others. Normally the total size of all return values (step exports) is limited to 6MB, but we compress response data to maximize what your workflow can store. That's the second issue: in your case, we were able to compress 2GB of total data. This is why events load so slowly, and why the browser has trouble handing the response.

In this case, are you able to add a new Node.js code step and combine the logic for that last few steps into a single code step? That way, you can store data in variables _within_ steps instead of passing them _between_ steps, which should reduce the data the browser has to render.

Our new workflow builder improves part of the performance issue here (we load step exports lazily, instead of when the page first loads), but rendering 2GB of data in the browser will always pose a performance challenge, so limiting what you return is the best path forward here.

Let me know if that helps.

**Comment by kyen99** [comment]
Thanks for taking a look. I'll try those suggestions!

**Comment by dylburger** [comment]
@kyen99 did reducing the size of step exports fix this problem for you?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
