### ISSUE TITLE
[APP] - spreadsheet.com

### ISSUE THREAD

**Issue by RayMeeks** [PipedreamHQ/pipedream#1929]
**Name of app / service**
https://spreadsheet.com

**Link to developer documentation**
https://support.spreadsheet.com/hc/en-us

**Is lack of support preventing you from building workflows, or do you have a workaround?**
no workaround found they only have zapier integration as of right now so your team will probably
have to reach out to get integrated

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

any action they can support. basically every type of action google sheets has plus whatever other features
spreadsheet.com offers please

**Comment by dannyroosevelt** [comment]
@RayMeeks I don't see any public API or webhook documentation on their site, so I sent their team an email. If you have a contact there who you can put me in touch with, feel free! My email is `danny@pipedream.com`.

**Comment by dannyroosevelt** [comment]
@RayMeeks unfortunately the team at spreadsheet.com informed me they do not have an API we can access and they do not have plans to enable one in the near term. I encourage you to submit a request to their team asking for them to support an integration with us, in order to help inform their prioritization.
