### ISSUE TITLE
[APP] Amazon Selling Partner

### ISSUE THREAD

**Issue by mshiner** [PipedreamHQ/pipedream#1938]
Amazon Selling Partner

[**Link to developer documentation**](https://github.com/amzn/selling-partner-api-docs)
New SP-API documentation site at https://developer-docs.amazon.com/sp-api
OAuth flows documentation: [Authorizing Selling Partner API applications](https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications)

We  have an open project to pull Amazon Vendor Central orders into our open source ERP system. Pipedream seems like a good solution but there doesn't seem to be an integration for this (unless I'm missing something). This page https://vendorcentral.amazon.co.uk/integration/getting-started?ref_=vc_xx_subNav shows what is available from the API.

We would specifically like to deal with:
* Purchase Order Management
* Shipment Confirmations

both of which are available.

Cheers
Martyn

**Comment by dannyroosevelt** [comment]
We've started the process for this, but no ETA currently.

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim i was looking into amazon selling partner. looks like it is better to sign up to Amazon as a business, because individuals they operate on a private context:

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/8e4c6353-1c69-424f-b3de-4eded2123c5f)

you need the Amazon account to start using Amazon Seller Central., from there you sign up as a developer, which can create the following type of apps:

> All public applications and private seller applications. These are: (1) Applications that are publicly available and are authorized by a seller or by a vendor, and (2) seller applications that are available only to your organization, and are self-authorized.
> 
> Private vendor applications. Vendor applications that are available only to your organization, and are self-authorized.

so, better to create a developer as business. I'd assume this is part of the process started by @dannyroosevelt please reach out to him for more context.

finally, I enhanced the issue description to include api reference at the developer portal, and link to the oauth authorization flows.

**Comment by sergio-eliot-rodriguez** [comment]
I checked again this time because it's prioritized in the apps by Michael, where it appears as Amazon Seller Central. But the API apparently is named Amazon Seller Partner, anyway.

This time I went the other way. I tried to create an account in Amazon Seller Central registering as an individual. I had all the documentation (dov id, phone, credit card, bank statement)

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/e1873d09-8454-4baf-9fda-ebc38eec1029)

**Comment by dannyroosevelt** [comment]
FYI this is largely done, I think it's blocked on a functioning test request? @malexanderlim might know the latest, but @sergio-eliot-rodriguez I don't believe there's action required from you.

**Comment by sergio-eliot-rodriguez** [comment]
Noted, probably a confusion, Amazon Seller Central in the Project App Store sheet vs Amazon Seller Partner in the issue.

**Comment by sergio-eliot-rodriguez** [comment]
This has been integrated: https://pipedream.com/apps/amazon-selling-partner
