### ISSUE TITLE
[APP] Rudderstack

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1972]
https://rudderstack.com/docs/rudderstack-api/http-api/

**Comment by fev4** [comment]
Would like to pile on on this one.

**Link to developer documentation**
https://www.rudderstack.com/docs/
https://www.rudderstack.com/docs/api/http-api/
https://www.rudderstack.com/docs/destinations/webhooks/
https://www.rudderstack.com/docs/api/transformation-api/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
It's not preventing me. I can find a workaround with their webhooks as a destination or as a source via their HTTP API. Would just love a deeper integration.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

I think the biggest power move here would be being able to use the Transformation API inside Pipedream to transform events captured through Rudderstack. I would love to see that!

**Comment by dylburger** [comment]
Thanks for the note @fev4! We're working on the basic integration now. 

Re: the Transformation API, could you tell me more about how you'd like to use that on Pipedream? Would you create transformations that would route data from Rudderstack to Pipedream, or would you want to programmatically create new transformations within a Pipedream code step? i.e. should we create Pipedream actions for the [create a transformation](https://www.rudderstack.com/docs/api/transformation-api/#create-a-transformation) endpoint?

Would you also want us to support the HTTP API so you can easily send data to Rudderstack from Pipedream?

**Comment by ericdodds** [comment]
Jumping in here - this seems really cool. 

It seems like an easy initial win would be adding Pipedream as a destination (excited you're working on that @dylburger). I think adding Pipedream as a source makes total sense and, in fact, would probably enable all of the use cases you'd want to build without integrating with the Transformations API. 

Excited to learn more about the Transformations use case. Also, cc @maximum-pixels on this - he's a RudderStack / Pipedream fiend!

**Comment by dannyroosevelt** [comment]
Here is a basic scaffolding for the HTTP API:
https://pipedream.com/apps/rudderstack/

And for the Transformation API:
https://pipedream.com/apps/rudderstack-transformation/

Please let me know if these both work for you @fev4 and @ericdodds 🙏 

@ericdodds would your team be interested in developing some pre-built triggers and actions for some of the RudderStack functions in each of the APIs? Our team is happy to help and provide guidance if so, and we have [great docs](https://pipedream.com/docs/components/guidelines/#getting-started) to help you get started.

**Comment by maximum-pixels** [comment]
@fev4 you can use pipedream for RS transformations. You can send an incoming Rudderstack event to a webhook destination where the webhook URL is the Pipedream starting point. You can then do whatever you need to there and pass the finished payload back to RS, either just to the HTTP endpoint API or to their webhook source type (depending on how much you're changing the event structure).

If you're passing it back to the HTTP API endpoint, just make sure to change the `messageId` property otherwise RS will ignore the returned event as a duplicate :) 

While this approach will let you transform your data lot more, it does have the downside of "costing" you 2 events for every event you process. Depending on what sources and volumes you're planning on using this for, this may or may not be a concern.

There are some other considerations around data security and potentially legislation as you'd of course be involving another processor to your potentially sensitive data!

Lastly the libraries link you posted above are not one's RS gives you by default, so you cannot just import them. That part of the repo describes how in RS transformations you can make your own libraries for commonly reused code that you can them import in actual destination transformations.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by fev4** [comment]
@maximum-pixels totally missed your comment when posted! thanks a ton for the context, I understand how it can be used! It's shame we'd have to spend two events instead of just one, maybe something to improve on for the future, for a deep integration (perhaps?)

@dylburger thanks for creating the issue on Ruderstack's side!
