### ISSUE TITLE
Logically group workflows in the UI

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#203]
I'd like a way to group related workflows in the Pipedream UI, for example by adding a tag to workflows or putting them into folders.

**Comment by DAVE4547** [comment]
Love to see this implemented

**Comment by samilkahraman** [comment]
I was about to open this feature request. You can check jotform's folder structure.

![image](https://user-images.githubusercontent.com/36473276/91637475-6353c780-ea11-11ea-9983-21d3b03c528a.png)

**Comment by KAZIMDZUBER** [comment]
what is this and what going on . can someone please tell?

**Comment by digiproductmarketer** [comment]
Yes, would be great to have additional levels of organization to the workflows.

**Comment by calpa** [comment]
Any updates?

**Comment by dylburger** [comment]
@calpa not yet but this is still on our radar. We'll update this ticket as soon as we have updates.

**Comment by frankbreckner** [comment]
Would love this too!

**Comment by gehtalles-de** [comment]
Hi! I need this too. The workflow section gets overloaded very quickly..

**Comment by juth** [comment]
I'm also in need of this.  It would be really helpful to have!

**Comment by camcodirect** [comment]
I would love to have this. Having to name things in a certain order is okay, does the job... but it would be AWESOME to have a folder structure

**Comment by tmchow** [comment]
Love this idea.  Folders would be preferably over tags.

**Comment by zalmanlew** [comment]
Any news on this? It's becoming increasingly important in my use case. Especially as I add more and more workflows, for many different projects.
I agree that folders is the way to handle it.
I was pretty happy with the way Zapier did it (it was basically the only thing they did right 😉)

**Comment by dylburger** [comment]
No immediate news, but this is still on the backlog for 2022. We just hired a few more engineers, so I believe the pace of releases is likely to increase!

**Comment by ngr900** [comment]
I see Pipedream as a potential godsend for prototypes & some MVPs, but this is a crucial prerequisite before I could actually use it in commercial work for anything that requires more than a few workflows, especially when working in a team. To me that effectively relegates it to pre-prototype, internal and personal use, so I'm really glad this issue is in the works!

Have you settled on any details for the grouping functionality yet?

I hope it's never too late for suggestions so here's mine: since Pipedream is powerful enough to power complex applications (in a very broad sense), allow the users to create equally complex groupings. To me that would include nested folders (for organizing functionalities) and, ideally, a separate tag layer (for organizing work on the functionalities at a basic level).

**Comment by DataGoblin** [comment]
Would love to see this feature! Even with around 10 workflow it does cause my brain to get jumbled without some nice folders to put them in.

**Comment by geopopos** [comment]
I don't know if there is a way to upvote features, but this is me throwing my hat in

**Comment by vico93** [comment]
Really looking forward for this!

**Comment by TomFrankly** [comment]
+1

**Comment by ptstevens** [comment]
@dylburger Is there any line of sight on this? The more workflows you create the more apparent this is a MUST have feature. Has it even been scoped?

**Comment by AtFy** [comment]
Hey!

In addition to this, I'd like to mention that it would've been great to store external links inside the folder, so that it will be possible to store the webhook sender's link (Intercom event, or intercom custom app, for instance) and the linked WF at the same place (folder).

It might've been really useful for the companies using CRM + ChatManagemet System + backend admin panel integration + Pipedream in a chain.

Thanks!

**Comment by dylburger** [comment]
This is out! [See the project docs](https://pipedream.com/docs/projects/) for more detail.
