### ISSUE TITLE
[FEATURE] Pipedream should support 2FA / multi-factor auth for logins

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2037]
Today, I can sign up with a Google or GitHub account on Pipedream and configure two-factor auth in my identity provider, but if I sign up for a Pipedream account using a Pipedream username + password, I can't enable two-factor auth.

**Comment by tekacs** [comment]
Would love to see this. For any serious production use, this is a necessity.

A stopgap would be to disable the ability to reset or set password on my account, since I'm authenticated in using Github which has 2FA.

If I could 'turn off' password authentication, then Github's 2FA would adequately protect my account. As it stands, I suspect that someone could reset password to get around this and then log in with just that one factor.

Nonetheless, having no password set and using Github seems to be the current best workaround for the lack of 2FA, since someone would need to compromise your e-mail / reset password process to get in.

**Comment by TomFrankly** [comment]
Adding my +1 to this; configuring 2FA at each provider in a workflow isn't enough, as it leaves Pipedream itself open as a 1-factor potential attack vector.

**Comment by ctrlaltdylan** [comment]
Hi @TomFrankly, just laying out the authentication scenarios.

### Registering a Pipedream account with Gmail

If you initially register a Pipedream with Gmail for example, you can configure your Gmail Workspace account to require 2FA to login to Gmail.

Therefore, 2FA would be required to login to Pipedream as well.

### Registering a Pipedream account with Github

Same story as above. Registering a Github account and enabling 2FA on your Github account will require anyone to 2FA into Github before they can access your Pipedream account.

### Registering with an email address + password combo, then signing in with Github or Gmail _later_

The is the scenario where the problem lies. Registering with a email + password _first_ means that you have one authentication method that is one factor.

We recommend registering with Gmail and Github since with those services you can require 2FA initially and Pipedream is "downstream".

Or are you referring to something else?

**Comment by tdnzr** [comment]
+1 on the 2FA request: automation services desperately require security features like 2FA, because they are linked to other services whose security they can compromise.

**Comment by tdnzr** [comment]
That said, I had the same problem, and I've found a potentially acceptable workaround for those who would be satisfied with the Google or Github login (2FA account) but are currently stuck with an Email account which lacks 2FA. The workaround consists of creating a new 2FA account, then transferring the workspace over.

Caveats: Follow at your own risk. I've only done this with my own account, a free account which only has one active Pipedream workflow. Also, I think billing status is tied to the user account, and hence not transferred. And if you used your user account's Pipedream API key for anything, that's also not transferred.

1. Register a new 2FA account, linked to Google or Github.
(At this point you’ll either want to use a second browser, or might have to awkwardly switch between accounts by logging in & out a bunch of times.)
2. Login to your original Email account, e.g. in a second browser.
3. In your Email account, navigate to your [workspace membership settings](https://pipedream.com/settings/users). Invite your new 2FA account via the invite link.
4. Accept the invitation in your 2FA account.
5. In your Email account, still in workspace membership settings, set the new 2FA account as workspace owner and admin.
6. In your 2FA account, select your original workspace, the one you've just transferred over, then navigate to _its_ [workspace membership settings](https://pipedream.com/settings/users). In the Members section, remove the Email account (the menu option is called something like "Delete User").
7. In Workspace Settings -> [General](https://pipedream.com/settings/account), change the notification email, if necessary.

-> Now the original Email account still exists (though you could delete it after transferring all your workspaces over and confirming that everything still works in your new 2FA account), but the workspace has been transferred to your 2FA account.

**Comment by dannyroosevelt** [comment]
We’re very excited to announce that **Pipedream now supports 2-factor authentication (2FA)** as an additional layer of security to protect your account 🙌 🔐 

- 2FA is available to all users on all plans right now
- We currently support 2FA with authenticator apps like Google Authenticator, 1Password, etc. (let us know if you’d like to see a different form of MFA)
- **Workspace admins will soon be able to require 2FA** for all their workspace members, and we expect to ship this in the coming weeks
- **Configure 2FA in your [account settings](https://pipedream.com/user)**
- [Check out the docs](https://pipedream.com/docs/user-settings/#two-factor-authentication) for more info

Let us know if you run into any issues or have any feedback!
