### ISSUE TITLE
[APP] Storj

### ISSUE THREAD

**Issue by davetapley** [PipedreamHQ/pipedream#2132]
**Name of app / service**
Storj

**Link to developer documentation**
https://docs.storj.io/dcs/

Also: https://forum.storj.io/t/pipedream-integration/16945

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Yes, see:
- #2127

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

An action analogous to [`$send.s3`](https://pipedream.com/docs/destinations/s3/#using-send-s3-in-workflows) would be a good starting point, e.g. `$send.storj`, [see docs here](https://docs.storj.io/dcs/getting-started/quickstart-uplink-cli/uploading-your-first-object).

**Comment by ctrlaltdylan** [comment]
Hi @davetapley, thanks for opening up an app request.

Unfortunately the same constraint that we spoke about in the prior issue you opened https://github.com/PipedreamHQ/pipedream/issues/2127 applies here as well.

Apps are code templates that can be used in steps. So the same run time constraints apply meaning that the NPM packages to use can't rely on Go or build from source.

Is there another npm package that can integrate with this service without a dependency on any other language besides Node.js?

**Comment by davetapley** [comment]
@ctrlaltdylan d'oh, I'd hoped apps were developed internally in a different way 😞 

Looks like there was a pure JS version, but it's not supported anymore.

I'll bring it up on [their forum](https://forum.storj.io/t/pipedream-integration/16945), you're welcome to close this or leave it open in case a JS library magically appears 🤞🏻

**Comment by ctrlaltdylan** [comment]
@davetapley No worries! Yea it's not immediately apparent that apps run on the same pipelines as actions. This allows apps be reused across many workflows.

Since we don't have plans to support multiple languages within app components I'm going to go ahead an close it.

_But_ I will say, if you elect to host your own server running a small Node HTTP server that has this NPM package installed to interact with Stroj - then you could interact with this server using Pipedream workflows.

It's a proxy you'd have to maintain, but it would give you the flexibility to let your "business logic" live in Pipedream where it's easy to make changes rather than ship code to a remote server.

Best of luck, and do let us know if you come across a pure JS version we can support.
