### ISSUE TITLE
[ACTION] Send a message to an AWS SNS topic

### ISSUE THREAD

**Issue by marier-nico** [PipedreamHQ/pipedream#2150]
**Is there a specific app this action is for?**

AWS

**Please provide a link to the relevant API docs for the specific service / operation.**

https://docs.aws.amazon.com/sns/latest/dg/sns-publishing.html#publish-to-topic-aws-sdks

**Note**
I do know that I can send to EventBridge, which can then send to SNS. It's just that it seems a bit unnecessary for simple workflows that might not require all the features of EventBridge. So sending directly to SNS would be pretty useful.

**Comment by marier-nico** [comment]
This might actually be a bit useless given that you can also create your own clients and use any service you want. I'll leave it open so maintainers can decide what to do, but I suppose I wouldn't really need this after all (though someone else might find it helpful)!

In any case, apologies for this pretty basic issue, I'm still fairly new to pipedream 😅

**Comment by dylburger** [comment]
@marier-nico This is not useless at all and I think it would be a great action!

Yes, you can write any Node.js / Python / Go code on Pipedream, so you can always use the AWS SDKs to send this message. But even those of us who love writing code like using Pipedream actions, since:

1. You don't have to write the code, and
2. Actions can lists of values that you can select from a form. You'd typically have to go find these yourself and copy-and-paste them into code, e.g. the SNS topic name / ARN.

If you're interested: all actions are open source and you can develop any yourself and publish them to the community for anyone to use. I listed a few resources below. If you're interested, we are always happy to help (we chat in the #contribute channel of our [Slack workspace](https://join.slack.com/t/pipedream-users/shared_invite/zt-11sazmsg0-oS2VW~mZfhtk3XfEEvb~JA)).

* [Tutorial for developing your own action](https://pipedream.com/docs/components/quickstart/nodejs/actions/)
* Check out our existing [AWS components](https://github.com/PipedreamHQ/pipedream/tree/master/components/aws). That code is likely to be helpful. You can see [we already have an "event source" (a workflow trigger) for SNS](https://github.com/PipedreamHQ/pipedream/tree/master/components/aws/sources/new-sns-messages). This does the opposite of what you want: it triggers a workflow every time a message is published to a specific SNS topic. But that code is likely to be helpful.

Let me know if that helps.

**Comment by marier-nico** [comment]
Thanks a lot for the helpful response! I'd be interested in making the action, however I don't know when I would be able to start working on it. So if someone else comes across this and wants to work on it, go ahead! Otherwise, I'll hopefully get around to it eventually. 😄
