### ISSUE TITLE
Notion [APP]

### ISSUE THREAD

**Issue by ankitdas123** [PipedreamHQ/pipedream#2179]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dannyroosevelt** [comment]
Hi @ankitdas123, we have a basic integration in place with Notion today: https://pipedream.com/apps/notion

And we have the addition of pre-built [triggers](https://github.com/PipedreamHQ/pipedream/issues/1229) and [actions](https://github.com/PipedreamHQ/pipedream/issues/1229) on the backlog (feel free to subscribe to either of those issues to follow along with their progress).

**Comment by ankitdas123** [comment]
What actions are possible through this integration as of now?

**Comment by dannyroosevelt** [comment]
Since we don't yet have pre-built actions or triggers for Notion, right now we provide the code scaffolding so that you can make authenticated requests to their API, but this will require modifying the code snippet you'll see when you add Notion to your workflow. For example:
https://pipedream.com/@danny/notion-api-p_BjCD968

From here you can reference Notion's API docs to build out whatever custom actions you'd like to use: https://developers.notion.com/reference/intro

Does that help answer your question and point you in the right direction?

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
