### ISSUE TITLE
[FEATURE] Can't look at a step's output and code

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2295]
**Is your feature request related to a problem? Please describe.**
So I'm working on a step and it has an error. I click in Results to see the error, but it closes the Code portion. I click to re-open it, and it closes Results. So I can't look at both to help me diagnose the issue.

**Describe the solution you'd like**
As I described in my other ER, I should be able to expand/collapse what I need to.

**Comment by dylburger** [comment]
@cfjedimaster This should be fixed in the newest version of the v2 workflow builder! You can expand all sections of a single step, of all steps, pin specific sections (e.g. just the code for a specific step), etc. 

<img width="254" alt="Screen Shot 2022-03-29 at 11 48 09 AM" src="https://user-images.githubusercontent.com/242668/160683591-b68d1b71-1897-4813-9654-f574faf80c99.png">

<img width="226" alt="Screen Shot 2022-03-29 at 11 48 14 AM" src="https://user-images.githubusercontent.com/242668/160683614-4b818b34-41dd-4bb6-8e41-815eaf9a6fa9.png">

<img width="266" alt="Screen Shot 2022-03-29 at 11 49 24 AM" src="https://user-images.githubusercontent.com/242668/160683681-90a93321-4f5d-402b-8128-142bd494ae3e.png">

Let us know if you have any other feedback on this.
