### ISSUE TITLE
[BUG] If you hit enter when searching, you go to a 404. 

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#2296]
**Describe the bug**
I'm here, https://pipedream.com/docs/migrate-from-v1/, and in the search box I entered some text (email), hit enter, and ended up at a 404 here: https://pipedream.com/docs/v1/destinations/email/#email

**To Reproduce**
See above. :)

**Comment by dylburger** [comment]
@ctrlaltdylan Is this related to the v1 / v2 index issues?

**Comment by ctrlaltdylan** [comment]
@dylburger correct, Algolia was ignoring our v1 routes because a canonical tag was present, the latest crawl just finished a few hours ago.

But we'll need to update v1 to use the `pipedream-v1` index, and without 2 different Crawlers I'm not sure if we'll be able to fully separate v1 from v2 search results.

The next experiment will be to transform the results, because it's appending the `docs/v1` to the current subpath making the end result: 

`/docs/docs/v1/code`

Just as an example.

**Comment by ctrlaltdylan** [comment]
This issue should be resolved. Thanks for the report!

If you find any more issues with the search experience please let me know but we have done a big upgrade to fix the problems in both sets of docs.
