### ISSUE TITLE
[BUG] Cmd + / Hotkey to comment out code will also show the shortcuts modal

### ISSUE THREAD

**Issue by arthurwuhoo** [PipedreamHQ/pipedream#2398]
**Describe the bug**
Currently, on a mac in Chrome, pressing Cmd + / in the code editor will both comment out code and show keyboard shortcuts, which felt pretty jarring. Leaving comments feels pretty common, so I feel like Cmd + / should only comment out code when the editor input box is focused

**To Reproduce**
1. Click / focus the input box of any code editing step when in the workflow view
2. Press `Cmd` + `/` if on Mac

**Expected behavior**
Only code gets commented out

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 99.0.4844.51

**Comment by dylburger** [comment]
@arthurwuhoo This should be fixed! `Cmd` + `/` no longer overrides the native Monaco (VS Code) shortcut. Please hard refresh pipedream.com (`Cmd` + `Shift` + `Enter`) and let me know if that works.

We still allow other shortcuts (e.g. `Cmd` + `Enter` to test a step) to operate in the context of the code, since users often want to use those while they're still in the editor context. If you encounter other shortcuts that conflict with Monaco / VS Code defaults, you can always modify the Pipedream shortcut:

1.  Open the shortcut help menu
2. Click into the field with the shortcut (e.g. `Cmd` + `Enter`)
3. Enter your own key combination, and it should set the new combination as the shortcut for that operation.
