### ISSUE TITLE
[Refactor] Data Stores actions

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2530]
From Cassiano:
There are some ways to improve the readability of #2513.
We weren't able to code and test this solution.
The main idea of this task is to refactor the code maintaining the functionality of the previous code

**Comment by ctrlaltdylan** [comment]
Subscribing, just in case I need to update the pre-built Data Stores actions docs in tandem.

**Comment by feyzullah** [comment]
@vellames-turing I run these tests for "add-update-multiple-records" action. They may be helpful while refactoring.
[data_store_test.pdf](https://github.com/PipedreamHQ/pipedream/files/8400055/data_store_test.pdf)

**Comment by dylburger** [comment]
I noticed when helping a user that we still show a success message even if the value written is `undefined`. In that case we don't write the value to the DB. @dannyroosevelt Is that intentional behavior in the data store itself, or is that not expected? If it's expected then I would include some code to check for that case in the action and return an error to the user.

**Comment by dannyroosevelt** [comment]
> I noticed when helping a user that we still show a success message even if the value written is `undefined`. In that case we don't write the value to the DB. @dannyroosevelt Is that intentional behavior in the data store itself, or is that not expected? If it's expected then I would include some code to check for that case in the action and return an error to the user.

Good catch -- that is not expected.

**Comment by vellames-turing** [comment]
Starting here

**Comment by vellames-turing** [comment]
So, I guess I finished it. I tested for all @feyzullah  scenarios and some others. Everything looks good.
About the `undefined`.:
When a user sends an empty value using the constructor, the value will be changed to `null`. The key will be preserved but the value will be `null`. I think this is an interesting behavior since if the user really wants to delete the key, it can use the `delete` action. The interesting thing is that if the user says `{key=undefined}` the key will be erased, but if the user says `key=null` the key will not be erased and the value will be `NULL`. In my view, we need to double-check if this is the desired behavior, if it's not, I`d like to suggest a change in `datastore.set` to handle `null` and `undefined` as the same case.

I added the `xss` package to sanitize any `xss-attack` since I am using `eval` function to evaluate nested objects instead of regex. 

Also, I tried to keep the previous behavior of converting all strings that mean `number` and `boolean`. So `"30" will be converted to 30` and `"true" will be converted to true` 

@dylburger About await `set`. Looks like it is not returning promises. The return of `set` is `undefined`

**Comment by dannyroosevelt** [comment]
> So, I guess I finished it. I tested for all @feyzullah scenarios and some others. Everything looks good. About the `undefined`.: When a user sends an empty value using the constructor, the value will be changed to `null`. The key will be preserved but the value will be `null`. I think this is an interesting behavior since if the user really wants to delete the key, it can use the `delete` action. The interesting thing is that if the user says `{key=undefined}` the key will be erased, but if the user says `key=null` the key will not be erased and the value will be `NULL`. We have two different behaviors for `set` function here. In my view, we need to double-check if this is the desired behavior, if it's not, I would like to suggest a change in `datastore.set` to handle `null` and `undefined` as the same case.
> 
> I added the `xss` package to sanitize any `xss-attack` since I am using `eval` function to evaluate nested objects instead of regex. Regex is a good solution, but its not very easy to read for other people that may maintain this code, so I prefer to avoid it whenever is possible.
> 
> Also, I tried to keep the previous behavior of converting all strings that mean `number` and `boolean`. So `"30" will be converted to 30` and `"true" will be converted to true`
> 
> @dylburger About await `set`. Looks like it is not returning promises. The return of `set` is `undefined`

Thanks, Cassiano. I raised the `await` issue w/ the team, and we're also discussing the `null` vs `undefined` question.

**Comment by dannyroosevelt** [comment]
@vellames-turing we are going to be updating the `data_store` API to handle everything async, but we can't ship that change until all the `set` and `get` calls are updated to `await`. Can you add that change in?
