### ISSUE TITLE
Import Data into Dynamics 365 fields

### ISSUE THREAD

**Issue by MartenHirsch** [PipedreamHQ/pipedream#2596]
I want to take data that customers provide us in Jotform and import the data into the appropriate fields in Dynamics 365.  Dynamics 365 has out of the box entities/tables with fields but we use mostly custom entities/tables.  So i need to be able to push the data into those custom entity fields.

Here is some information on custom entities/tables.  https://docs.microsoft.com/en-us/power-apps/maker/data-platform/create-custom-entity

Here is a link to the web api for Dynamics 365.  https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/use-microsoft-dynamics-365-web-api?view=op-9-1

It would be great if your service would allow me to see these custom tables and then be able to map the jotform data to the appropriate field in the custom table.

**Comment by dylburger** [comment]
@MartenHirsch Thanks for the request! Are you familiar with Node.js? Since we support an integration with the [Dynamics 365 API](https://pipedream.com/apps/dynamics-365-business-central-api), you can:

1. Add a new step in your workflow
2. Search for "Dynamics 365"
3. Select the first option in the list:

<img width="924" alt="Screen Shot 2022-04-23 at 7 00 36 PM" src="https://user-images.githubusercontent.com/242668/164950045-af527e6a-5317-4df4-8bcb-10124fde3b65.png">

This gives you a pre-built code step you can modify in any way you'd like. If you're new to Node.js, I'd recommend taking a look at [our docs on making API requests](https://pipedream.com/docs/code/nodejs/http-requests/).

Finally - if you're using a Jotform trigger, you should be able to [reference that data](https://pipedream.com/docs/workflows/events/#copying-references-to-event-data) when passing data in the Dynamics 365 API request.

Let me know if that helps!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
