### ISSUE TITLE
[BUG] Zoom Trigger not working 

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#2660]
I am using the Zoom > Custom Event trigger and am not getting events to show up as I'd expect. 

This is a screenshot of a meeting I started and joined, so I'd expect to get at least 2 events, but nothing shows in the logs
![image](https://user-images.githubusercontent.com/20780753/164290556-62b04731-be04-497c-8ae7-41af2afd902f.png)

**Comment by jcortes** [comment]
@dannyroosevelt after some time of testing I realized the same happened to me and it was because I was using two different Zoom accounts and connected the wrong account in PD. So maybe that's what is happening to you too. Do you mind making sure you are using the right account in both platforms? and test again. Thanks!
