### ISSUE TITLE
[APP] Splunk

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#2662]

**Comment by sergioeliot2039** [comment]
I recently marked this as blocked on the App Store project list, because its authentication scheme is Basic + Bearer.
](https://openpath.readme.io/docs/using-the-api#using-the-login-api)https://www.splunk.com/en_us/blog/tips-and-tricks/splunk-rest-api-is-easy-to-use.html?msclkid=3a5b0a03c01b11ec868c08cb55c73973

**Comment by dylburger** [comment]
Duplicate, closing
