### ISSUE TITLE
[FEATURE] I would like to be able to replay all events or easily bulk select multiple events to replay in the workflow inspector

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2784]
**Is your feature request related to a problem? Please describe.**

In the case my deployed workflow fails multiple times, after I fix the issue I would like to easily replay all of these events.

**Describe the solution you'd like**

A similar button to the **DELETE ALL EVENTS** as well as a way to easily bulk select all events with a failed status to replay.

**Do you have a workaround?**
Clicking each failed event individually, then clicking **Resend Event** individually is the only option currently.

**Comment by dobsonjon** [comment]
+1 for this. As part of this feature, it would be great to see:

- option to replay only failed steps in each event
- option to replay multiple times with exponential backoff

This would make it a much easier sell for us to move off of Zapier, which already has these abilities. I prefer Pipedream, but without this feature I'm afraid we're stuck on Zapier because of dependencies on APIs that occasionally throttle us and trigger failed automations.

**Comment by davetapley** [comment]
@dobsonjon once bulk retry is implemented I think you could solve for those use cases with the existing [`$.flow.rerun`](https://pipedream.com/docs/code/nodejs/rerun/#flow-rerun) feature, by editing the failing workflow to add the required `$.flow.rerun` logic, then using this proposed bulk replay to manually restart.

---

Can I request, in addition to:
> easily bulk select all events with a failed status to replay

that we can also select all events within a time range?

I have a case where a workflow was reporting success ✅, but a bug in the code meant it wasn't doing what it was _supposed_ to be doing. I can also imagine cases like this would benefit from a manual bulk retry because even if I had implemented `$.flow.rerun` logic in my workflow, it's possible a bug could result in it not rerunning even when it should.

**Comment by csarigoz** [comment]
+1 for this. Happens for me all the time.

**Comment by davetapley** [comment]
Cruel, I just discovered the **Event History** page. 

Now I have to decide whether to try and write an automation, or click 100s of times 😭 

<img width="865" alt="Event_History_-_Pipedream" src="https://github.com/PipedreamHQ/pipedream/assets/48232/b3090d50-7a19-4d39-80e4-7fcd63417322">

**Comment by KarlBishop** [comment]
+1 for being able to bulk select and retry multiple events in one go.

I would also like the Event History page to reflect which events have been retried!
Currently it's very easy to forget which ones have been retried and to accidentally do the same one multiple times. My best method for avoiding this at the moment is to delete each event immediately after retrying it. But this is not ideal because I have to sacrifice my history. And, every time I delete an event, the history screen resets to Page 1 so I have to click multiple times on the Next Page button to get back to where I was working.

**Comment by KarlBishop** [comment]
Oh yeah, also, it'd be great if there was an option to skip automatic retries when manually retrying an Event.

At the moment, if I retry an Event on a Workflow that has auto-retries enabled and the rerun hits another error, then it keeps retrying and erroring over and over and there's no way to stop it AFAIK. Even disabling auto-retries on the Workflow at this point doesn't stop the process. I think the only way to prevent it at the moment is to disable auto-retries on the Workflow in advance of manually retrying an Event.

**Comment by mroy-seedbox** [comment]
+1 to "reflect which events have been retried!"

Or even replaying the workflow from the failed step, and updating the status afterwards. <-- This is how Zapier works.

So a failed event can become successful is manually replayed (from the failed step) without error.

**Comment by andrewjschuang** [comment]
A suggestion from an user while we wait for this feature:

Log or save externally `steps.trigger.context.trace_id` to later check the status / execution in the Event History, e.g. `https://pipedream.com/@/event-history/<trace_id>`

**Comment by bacherjo** [comment]
++1 from me. 
event history replay option for selected failed workflows, default option to replay from failed step only.
important especially, as the "auto retry on errors" currently does not work for timed out steps, but this is the most frequent error I have when partner systems are down.

**Comment by dannyroosevelt** [comment]
The core of this feature request is done! You can now select many events from Event History and delete or replay them all. We're planning to look at additional improvements in the future related to tying replayed events back to their original event to reflect the status, etc.

Check out our docs here: https://pipedream.com/docs/event-history#bulk-actions

**Comment by davetapley** [comment]
@dannyroosevelt this is great, but can we get a "select all matching", so I don't have to manually paginate and check all per page?

E.g. Gmail has this prompt:

<img width="1118" alt="Screen Shot 2024-11-01 at 2 00 35 PM" src="https://github.com/user-attachments/assets/fb884bc9-5be0-4c23-b8be-623351521abf">

**Comment by binarymonkey84** [comment]
@dannyroosevelt The management of failed events is still very difficult to work with when you have hundreds of failed events.

Many times now I've had workflow problems which generate thousands of failed runs very quickly. Trying to manually click through every page in the event history to bulk replay them one page at a time is obviously very error prone and time consuming.

I'm looking at 150 pages of failed events in the event viewer. With 20 events per page, that's 3000 failed events that I have to replay. Auto retry is in place but this doesn't actually help at all when there workflow changes are required, because auto-retry in Pipedream doesn't use the latest workflow version, it just auto-retries the version that was used for the original run. That in itself is not obvious in the UI.

So that's 2 clicks to bulk replay 20 events on each of the 150 pages (as you can't bulk replay more than a single page of events at a time). That's 300 clicks... and I've noticed navigating between pages of events often breaks in the UI, especially when doing it quickly.

Not to mention that the events on each page doesn't remain stable if any new events come in that match the filter, so you there's no certainty that all events will be replayed, or some may be replayed more than once.

It's not really usable in the current form for workflows that have a high volume of events - it would be great to see some improvements in this area. It's already a difficult situation when things break, and made exponentially worse when we have to tell the client that we can't reliably replay all the failed events due to UI limitations.

I'd suggest adding a lot more filters including workflow version, date from/to, and many more - combined with bulk retry all matching the (vastly more improved) filters.

In general if there was a way to simply 'replay all errors of this type', that would help make Pipedream far more practical in this area.
