### ISSUE TITLE
[BUG] Schedule Trigger is deployed just from saving

### ISSUE THREAD

**Issue by zalmanlew** [PipedreamHQ/pipedream#2885]
**Describe the bug**
Making any changes to the schedule trigger and hitting **Save** automatically saves _and_ deploys them - even though the user hasn't pressed deploy.

**To Reproduce**
1. create a workflow with the schedule trigger
2. edit the workflow
3. change the schedule to anything
4. hit save / continue
5. workflow has been deployed with the changes

**Expected behavior**
It should only save the updated trigger as a draft until the user **Deploy**s the workflow

**Screen Recording**

https://user-images.githubusercontent.com/35234925/169192479-5fe8bf31-2982-4063-9049-28e0a1d856a4.mp4

**Comment by dylburger** [comment]
@zalmanlew Apologies for getting back to you so late. This is actually by design at the moment. Since workflow triggers are independent entities, changes to them are independent of the workflow. You can modify a trigger configuration without re-deploying the workflow.

I'll share this feedback with the team so we make the UX more clear!
