### ISSUE TITLE
[FEATURE] Digest

### ISSUE THREAD

**Issue by marcelocecin** [PipedreamHQ/pipedream#2907]
**Is your feature request related to a problem? Please describe.**
Do you ever feel tormented by instant notifications? They're supposed to be helpful—but really, they just distract you from more important work.

**Describe the solution you'd like**
Digest captures info from multiple events in your workflows and collects them in a single easily consumed summary that can be sent to any app.

**Comparable features in other tools?**
https://zapier.com/apps/digest/integrations

**Additional context**
https://zapier.com/blog/updates/855/create-custom-digest-summary

**Comment by dannyroosevelt** [comment]
Actually @marcelocecin, we have a feature that may accomplish what you're trying to do -- [this documentation](https://pipedream.com/docs/examples/waiting-to-execute-next-step-of-workflow) is actually slightly stale (we have it in the queue to get it updated asap), but essentially you can,
1. [Configure an action](https://pipedream.com/apps/helper-functions/actions/schedule-task-in-future) to schedule a task in the future (and pass in whatever data you want).
2. In a different workflow, [configure a source](https://pipedream.com/apps/pipedream/triggers/new-scheduled-tasks) that will get triggered off the receipt of the events from step 1.

So this way you can send off events to the queue, which will trigger your 2nd workflow at a time in the future of your choosing.

This is not incredibly intuitive or well documented, so that's something we intend to improve soon!

Let me know if that helps.

**Comment by marcelocecin** [comment]
hi Danny
I will try to implement
thanks
