### ISSUE TITLE
CleverTap

### ISSUE THREAD

**Issue by parthdani** [PipedreamHQ/pipedream#2997]
**CleverTap**

**[Link to developer documentation](https://developer.clevertap.com/docs/upload-user-profiles-api)**

**Comment by sergioeliot2039** [comment]
HI @parthdani  Thanks for submitting your request! It looks like API access requires a paid account or going through a demo, so we are waiting for CleverTap to reach out -- are you able to grant us temporary access to the API so we can verify the authentication implementation?

Otherwise you can also try setting up the app here: https://pipedream.com/submit-an-app (this is an early alpha UI, so please let me know if you run into any issues).

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergioeliot2039** [comment]
Hey Parth, I drop you an email to dani to parth 15 at gmail dot com because the email addresses you disclosed were hidden by GitHub, so perhps you can reply back there? either with correct emails addresses (instead of hidden) or for kick starting the process for getting CleverTap trial access. Thanks!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment]
Hello @parthdani 

Happy to announce that finally there is a base integration with CleverTap via Pipedream:
https://pipedream.com/apps/clevertap

Michael may have already reached out to your team via email, so I just wanted to update here.

If there is any feedback, feel free to let us know.

Best,
Sergio
