### ISSUE TITLE
[FEATURE] ID and URL from Linear Created Issue

### ISSUE THREAD

**Issue by lupionpe** [PipedreamHQ/pipedream#3086]
**Is your feature request related to a problem? Please describe.**
When an issue is created on Linear it does not inform the issue ID or its URL

**Describe the solution you'd like**
Give back this informations

**Do you have a workaround?**
No

**Comparable features in other tools?**
No

**Additional context**
No

**Comment by vunguyenhung** [comment]
Hello @lupionpe, I observed that currently Linear Created Issue trigger returns both ID and URL, is this what you want?

![Linear_created_issue](https://user-images.githubusercontent.com/18277920/172656484-10e3cb85-05bd-4768-8d84-6a262197b620.png)

**Comment by lupionpe** [comment]
It exists as the trigger from created issues, but does not when the actions is create issue: https://pipedream.com/apps/linear-app/actions/create-issue

What I am asking is the feedback that issues was created and what is the id of the created issue

**Comment by vunguyenhung** [comment]
I observed that the Linear Create issue action:
- returns `id` 
- does not return `url`
![screenshot (26)](https://user-images.githubusercontent.com/18277920/172752254-992d70d8-2b6b-4dd3-8c38-c91c151506b2.png)

Checking furthermore, I observed that this is because Linear SDK only returns the `id` but not `url` (more detail [here](https://github.com/linear/linear/blob/master/packages/sdk/src/_generated_documents.graphql#L6361-L6368)). 

Hello @lupionpe as a workaround to serve your need, I suggest you add additional action to get Linear Issue URL using Linear (OAuth) API (unfortunately, currently we do not have Linear Get Issue action):
Add a new action using Linear (OAuth) API
![Screen Shot 2022-06-09 at 09 55 50](https://user-images.githubusercontent.com/18277920/172754451-9a50cade-4cd0-49d4-80ea-32cdb8490e7e.png)
Then use the following code in the action
```js
import { axios } from "@pipedream/platform"
export default defineComponent({
  props: {
    linear: {
      type: "app",
      app: "linear",
    }
  },
  async run({steps, $}) {
    const data = {
      "query": `
        query issue($id: String!) {
          issue(id: $id) {
            id
            url
          }
        }
      `,
      variables: {
        id: steps.create_issue.$return_value._issue.id
      }
    }
    return await axios($, {
      method: "post",
      url: `https://api.linear.app/graphql`,
      headers: {
        Authorization: `Bearer ${this.linear.$auth.oauth_access_token}`,
        "Content-Type": `application/json`,
      },
      data,
    })
  },
})
```

Result
![screenshot (28)](https://user-images.githubusercontent.com/18277920/172754973-1b67fff9-d891-4d46-a1dd-e40d19bbf7e5.png)

------


Hello @dannyroosevelt, I think we can make improvement on Linear app by adding Linear Get Issue action. What do you think?

**Comment by dannyroosevelt** [comment]
>I think we can make improvement on Linear app by adding Linear Get Issue action. What do you think?
@vunguyenhung makes perfect sense! Would you mind creating a ticket for that action and adding it to the board in the To Do column?

**Comment by vunguyenhung** [comment]
@dannyroosevelt, I have created an issue here: https://github.com/PipedreamHQ/pipedream/issues/310 🙏

**Comment by dannyroosevelt** [comment]
Thank you @vunguyenhung! 

@lupionpe Let us know if you are unblocked for now and feel free to follow along with the above ticket.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
