### ISSUE TITLE
[ACTION] Figma comment notification trigger

### ISSUE THREAD

**Issue by lupionpe** [PipedreamHQ/pipedream#3087]
**Is there a specific app this action is for?**
Figma

**Please provide a link to the relevant API docs for the specific service / operation.**
https://www.figma.com/developers/api#comments

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by michelle0927** [comment]
The title of this issue is a little confusing. It does say ACTION, but then requests a trigger. My interpretation would be that what's wanted is a trigger/source that emits an event when a new comment is created. I'd use a webhook with the event type - FILE_COMMENT. https://www.figma.com/developers/api#webhooks_v2

@lupionpe Can you elaborate on what's being requested in this issue?

@luancazarine What do you think? I see the PR for this contains a new action `delete-a-comment`, but no new triggers.
