### ISSUE TITLE
[ACTION] Slack - Block Kit Designer Action

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3100]
**Is there a specific app this action is for?**

Slack

**Please provide a link to the relevant API docs for the specific service / operation.**

The existing _Slack - Send Message with Block Kit_ expects a prior Node.js code step to generate the JSON structure of a Slack message.

It would be much more user friendly to create an action that allowed building of blocks through props.

Take Slack's native Block Builder as inspiration:

https://app.slack.com/block-kit-builder

The action would allow an array of individual blocks to be created, but with validation logic to help guide the block building process.

**Comment by vunguyenhung** [comment]
Confirm that the _Slack - Send Message with Block Kit_ action requires JSON input
![image](https://user-images.githubusercontent.com/18277920/172881921-77a6a4dd-d37b-4a29-ad51-4f108d4e0409.png)

Though, I would suggest that we instruct user to use [Slack's native Block Builder](https://app.slack.com/block-kit-builder) to produce the JSON and just simply copy the JSON into the Pipedream action. Since [Slack's native Block Builder](https://app.slack.com/block-kit-builder) already has validation & visualization in place, also it is managed by Slack so it will likely to be up-to-date with their API

@ctrlaltdylan @dannyroosevelt what do you think?

**Comment by dannyroosevelt** [comment]
Copy/pasting from their block builder won't totally work for our Block input actually, but it's very close. It looks like their payload includes an outer key, which breaks our input, so users will have to first remove that.
```
{
	"blocks": 
```

**Comment by dannyroosevelt** [comment]
I think it's a great idea to more closely embed some type of this functionality in our Slack actions, I just need to think a bit more about how that'd work. I created an internal ticket so we can track this there as well.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by dannyroosevelt** [comment]
This is done in the latest version of this action!
https://pipedream.com/apps/slack/actions/send-block-kit-message
