### ISSUE TITLE
[FEATURE] Support making workflow attachments web accessible

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#3168]
**Is your feature request related to a problem? Please describe.**
Imagine I've got a HTTP workflow that's meant to be an API used by web sites. If I want to put a web front end to it, I need to either:

a) modify the workflow to look for something in the request to know when to respond with HTML versus the API
b) make a new workflow just for the html (or use another service)

**Describe the solution you'd like**
Let me make an attachment 'web accessible', such that if the API was accessible at X, and I uploaded foo.html, I could then hit X/foo.html.

**Do you have a workaround?**

See A and B above. I don't like A as it makes the workflow 'less pure' as it's doing two things instead of one.

**Additional context**
This would be an option that would default to false, and could be limited to *.html, *.png, *.jpg, *.gif.

**Comment by dylburger** [comment]
This is a cool request but not something we're planning to implement. These files are ephemeral by design and only available in workflows. Check out this [related issue](https://github.com/PipedreamHQ/pipedream/issues/5662#issuecomment-1465420286) / suggestion to return the file via an HTTP-triggered workflow.
