### ISSUE TITLE
[Trigger] New Twitch trigger whenever a new clip is created for the Twitch channel specified by the user

### ISSUE THREAD

**Issue by Hassan-Abbas-SQA** [PipedreamHQ/pipedream#3184]
Request For a New Trigger : Emit an event whenever a new clip is created for the Twitch channel specified by the user.

**Comment by vellames-turing** [comment]
I notice the twitch is using default `axios`. I will change to pipedream axios, so we need to retest it, but in the end, this app will be totally up to date with our patterns.
Cc: @dannyroosevelt

**Comment by vellames-turing** [comment]
As far as I researched, unfortunately, twitch has no native [webhook](https://dev.twitch.tv/docs/cli/event-command) for this. The only way would be using the [get clips endpont](https://dev.twitch.tv/docs/api/reference#get-clips). The problem with this endpoint is that the clips are returned in order of most viewed and I did not find a way to order by newest.
The solution I have in my mind would be to use the filter per day and repeat the request for every day, So I would use a HashSet to avoid repeating `emits`. This is a very slow approach and high-cost approach since we will have to re-scan the day every time the timer triggers the source.
Do you think it is worth it to move ahead or maybe you guys have a better approach?
@dylburger @dannyroosevelt @js07

**Comment by js07** [comment]
@vellames-turing Does Twitch support getting clips created within a time interval smaller than 1 day using the `started_at` and `ended_at` parameters? E.g., get clips starting from 1 hour ago, rather than 1 day ago. Then store the `created_at` timestamp of the most recently created clip and request only newer clips on following runs of the source.

**Comment by vellames-turing** [comment]
Looks like it does. I will try to do that. Thanks!

**Comment by Hassan-Abbas-SQA** [comment]
on publishing this trigger @vellames-turing 
![image](https://user-images.githubusercontent.com/104946677/180074447-53d98c79-296d-44ea-b4fa-90a591b5f26b.png)
