### ISSUE TITLE
Stack Exchange

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3289]
### App
Stack Exchange
https://api.stackexchange.com/

### Triggers
- New answer
- New question

**Comment by GTFalcao** [comment]
@dannyroosevelt there are currently three StackExchange triggers:
- New Answers for Specific Questions
- New Answers from Specific Users
- New Question for Specific Keywords

Would these two new triggers be more generic versions then?
- emit event for a new answer to _any_ existing question, rather than selecting one or more questions or users to filter with;
- emit event for _any_ new question posted, rather than filtering by keywords.

**Comment by dannyroosevelt** [comment]
Oops, I missed those -- thanks for confirming. No action required.
