### ISSUE TITLE
[Bug] Twist OAuth flow is broken

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3306]
**Name of app / service**
https://twist.com

**Link to developer documentation**
https://developer.twist.com/v3/

Currently, we already have [a PR implementing actions for Twist app](https://github.com/PipedreamHQ/pipedream/pull/1337), but due to [an issue on the Oauth flow](https://github.com/PipedreamHQ/pipedream/pull/1337#issuecomment-1170010454) that we couldn't test & release it.

This issue is to track the fix to our current Twist OAuth flow

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
Hi @vunguyenhung, do you go by Leo on our [Pipedream-Users Slack space](https://join.slack.com/t/pipedream-users/shared_invite/zt-1burk0o2u-6TkKJtiubIn27JMWZic0oQ)?

Anyway, I removed the "added to app backlog" label - we use this when the app needs to be submitted to the [app store](https://pipedream.com/explore) using the [submit an app form](https://pipedream.com/submit-an-app) and ultimately approved by the team to be shown publicly. Since Twist is already integrated (see https://pipedream.com/apps/twist) there is no need to go through the underlying work process of "added to app backlog".

**Comment by sergioeliot2039** [comment]
Hey Leo!  I just saw after your reply the context provided by the [Issue Comment](https://github.com/PipedreamHQ/pipedream/pull/1337#issuecomment-1170010454) which you opportunely linked to.

> Hello @dannyroosevelt, I have just tested Twist component again and faced the same issue image
> 
> I think this is an issue on Oauth flow, I suggest that we create another ticket to investigate this on [App & Integrations Backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1). What do you think?
> 
> That sounds good, Leo, can you make that update?

Looks like Apps & Integrations Backlog is the right place (and thus the "added to app backlog" label) most suitable after all.
I have amended back as it was. Sorry for the pivoting

**Comment by dannyroosevelt** [comment]
confirming this is finally fixed
