### ISSUE TITLE
[FEATURE] Verify all modified component versions are incremented

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#3397]
When any common file is modified, every component that references that file must increment its version. If the component code is not directly changed, our current [PR checks](https://github.com/PipedreamHQ/pipedream/blob/master/.github/workflows/pull-request-checks.yaml) don't catch this scenario, so we sometimes end up merging changes that do not get published. We should fix this, so that prior to merging any PR, we verify that all impacted components have incremented their versions.

If a changed file in a PR is a [dependency](https://www.npmjs.com/package/dependency-tree) of a component, and the component's version is not incremented, the PR check should fail.

**Comment by dannyroosevelt** [comment]
@js07 can you add some details here on an approach that you think makes sense?

**Comment by js07** [comment]
An approach like this might work:
Replace the [`git_diff_on_components`](https://github.com/PipedreamHQ/pipedream/blob/93b2d149c8052aabcb8ff48fd6c596a07a78d134/.github/workflows/pull-request-checks.yaml#L37) step of the [`check_version`](https://github.com/PipedreamHQ/pipedream/blob/93b2d149c8052aabcb8ff48fd6c596a07a78d134/.github/workflows/pull-request-checks.yaml#L14) pull request check with a new `.js` script in [scripts/](https://github.com/PipedreamHQ/pipedream/tree/master/scripts):
1. For each component in the repo, get a list of dependency files (excluding `node_modules`) using an npm package like [dependency-tree](https://www.npmjs.com/package/dependency-tree)
2. Check if the component's dependencies includes a file that was changed in the PR
3. If so, check that the component's version was changed (e.g., using [`git diff`](https://github.com/PipedreamHQ/pipedream/blob/93b2d149c8052aabcb8ff48fd6c596a07a78d134/.github/workflows/pull-request-checks.yaml#L55))

**Comment by vunguyenhung** [comment]
Good day @jcortes @js07, the PR for this issue has been in Ready for PR review for a while. May I ask for the next action to move this forward?

**Comment by vunguyenhung** [comment]
Sorry I missed the case where changing the common file will require all related component to bump up version

For example, this [commit changes the `components/slack/sources/common/base.js` file](https://github.com/vunguyenhung/pipedream/pull/2/files#diff-23b3670bf6a41f57bd8267a205b3deb6b00608c3c4dde679ae579b2b40de9e34)

But the [Ensure component commits modify component versions step still passed](https://github.com/vunguyenhung/pipedream/runs/7898810006?check_suite_focus=true#logs)

Expected behavior: every Slack component that import this base file should be required to bump up version, including
- `components/slack/sources/new-direct-message`
- `components/slack/sources/new-mention`
- `components/slack/sources/new-message-in-channels`
- `components/slack/sources/new-reaction-added`
- `components/slack/sources/new-star-added`

**Comment by jcortes** [comment]
Hi @vunguyenhung I've added a fix that missed where there is no validation when those files aren't even touched so thanks for finding that bug. So please test again, thanks!

**Comment by vunguyenhung** [comment]
Hi @jcortes and everyone, all test cases are passed! Ready for release! 

Test report
[Verify_all_modified_versions_are_incremented_2155.pdf](https://github.com/PipedreamHQ/pipedream/files/9417145/Verify_all_modified_versions_are_incremented_2155.pdf)
