### ISSUE TITLE
[FEATURE] Search code in code steps across all workflows

### ISSUE THREAD

**Issue by huzaifah-esm** [PipedreamHQ/pipedream#3456]
**Is your feature request related to a problem? Please describe.**
I would like to, across all workflows, search for instances where I have used an environment variable (e.g. `process.env.MYVAR`). At this moment, the code content of code steps is opaque to any search and I would have to do this manually.

**Describe the solution you'd like**
In order of preference:
1. Code search built into the Pipedream dashboard and accessible using the search bar or another area.
3. Pipedream workflow code steps' content accessible through a REST API so that I can run my own search on the API response (e.g. using fuse.js).

**Do you have a workaround?**
Manually visiting each workflow (maybe hundreds) and searching every code step for a string.

**Comparable features in other tools?**
GitHub code search is decent within a repo.

**Comment by huzaifah-esm** [comment]
Yep searching across workflows in the UI would be great, but getting raw code content from an API will suffice for now? If there is a way to do that?

**Comment by dylburger** [comment]
I was reviewing old issues and realized we have an existing ticket tracking this at #665. Please follow that issue if you don't mind. We're close to rolling out our Git integration, which will also make this easier, since you can serialize workflows to a configuration file, checkout the repo locally, and search there.
