### ISSUE TITLE
Twitch Get Clips

### ISSUE THREAD

**Issue by eternalfragment** [PipedreamHQ/pipedream#3490]
For the Twitch Get Clips function, add add fields for after and before dates (so you can pull only the last 24 hours of clips for example)

**Comment by vunguyenhung** [comment]
Hello @eternalfragment, I understand your need is to have Before Date & After Date props for filtering clips returned by Twitch: Get Clip action.

But we currently couldn't support this natively inside the Twitch: Get Clip action because the [Twitch API doesn't provide this functionality](https://dev.twitch.tv/docs/api/reference#get-clips)

For now as a workaround, right after the Twitch: Get Clips action, I suggest you to add a custom code action (Node.js, Python, Bash, etc...) code to filter by Before Date & After Date. For example, Node.js code
```js
// To use previous step data, pass the `steps` object to the run() function
export default defineComponent({
  async run({ steps, $ }) {
    const clips = steps.get_clips.$return_value
    const afterDate = new Date('2022-07-20T10:00:00.000Z')
    const beforeDate = new Date('2022-07-22T16:00:00.000Z')
    const filteredClips = clips.filter(clip => {
      const clipCreatedAt = new Date(clip.created_at)

      return beforeDate >= clipCreatedAt && afterDate <= clipCreatedAt
    })

    return filteredClips
  },
})
```

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
