### ISSUE TITLE
[BUG] Sendinblue Transactional Email action fails when trying to add recipients to **To** field

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#3514]
**Describe the bug**
Sendinblue Transactional Email action fails when trying to manually add recipients to **To** field

**To Reproduce**
1. Create a new workflow, add SendInBlue: Send Transactional Email
3. On the `To` prop, **manually** add the JSON data using Custom Expression. For example: `{{ [{"email":"test@example","name":"Test User"}] }}`
4. Observe the error
```
SyntaxError
Unexpected token o in JSON at position 1
```
![FireShot Capture 396 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/180733335-c88b1f65-b7bb-4bbf-a849-5d82342845a7.png)

**Expected behavior**
1. On the `To` prop, the User can manually add the JSON data using Custom Expression. 
2. The `To` prop need to be able to accept JSON Object (.i.e `{"email":"test@example","name":"Test User"}`) and JSON Array (.i.e `[{"email":"test@example","name":"Test User"}]`)

**Additional context**
[Reported by a customer here](https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1658670184747329)

**Comment by vunguyenhung** [comment]
Hello @dylburger, I can reproduce this bug. I've updated the issue description to add more details and added to our Component backlog

Kindly check when you have time and edit as needed 🙏

**Comment by alexkazachkov** [comment]
Hello, has this issue really been solved? I tried to do the same thing now, but it still doesn't seem to work:

**Describe the bug**
SendInBlue integration has an issue with the send_transactional_email workflow, where if I want to use the "To" (or any other) sending field and want to enter a custom expression, it won't work and just show the error "Field To should be an array". 
I tried to use the example as is written below the input field { "name": "John Doe", "email": "john@doe.com“ }, but this one doesn't work either. I wanted to use custom expressions from the previous steps in my workflow (webhooks). See Additional context on how I bypassed this issue by writing my own working code.

**To Reproduce**
Steps to reproduce the behavior:
1. Add a step for SendInBlue send_transactional_email in your workflow.
2. Connect a SendInBlue acount.
3. For "Use template" you can click on "false".
4. Select a sender from the list of contacts under "select an option".
5. For subject, html and text content write anything you want.
6. For "Reply to" use the same contact as sender.
7. Now try to fill into the "To" field the example text given below the field and edit out the John Doe name and email and replace with your name and email, so that you can see if the mail goes through to you. Of course being able to directly input a custom expression from a previous webhook step needs to work, too, which currently also doesn't work.

**Expected behavior**
The email will be sent and there won't be any error message like "Field To should be an array".

**Screenshots**
No screenshots, but can add if necessary.

**Smartphone (please complete the following information):**
 - not used

**Additional context**
I have solved this issue by creating my own code with the "Use any SendinBlue API in Node.js" option.
My input for the "To" field here was as according to a code like this:

`data: JSON.stringify({
        sender: {email: 'test@email.com'},
        to: [{email:`${steps.trigger.event.data.email}`, name:`${steps.trigger.event.data.name}`}],
...
`

It would be good if I could use the same scheme for "To" and put this line of code directly into the send_transactional_email workflow. And it's not urgent as I have like I have written solved this issue, but maybe would be good for new users to have a working option for custom expressions directly inside the send_transactional_email workflow.

**Comment by dannyroosevelt** [comment]
@alexkazachkov I opened a new bug ticket here: https://github.com/PipedreamHQ/pipedream/issues/4253
