### ISSUE TITLE
Alpaca

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3549]
### App
Alpaca

### Actions
* List Orders
* List Positions
* Cancel All Order
* Cancel Order
* Close All Postions
* Close Position
* Get Account Info
* Place Order

**Comment by feyzullah** [comment]
Hi @jverce do `List Orders` and `List Positions` trigger when a new one is created, one is fulfilled or one is cancelled?

**Comment by Hassan-Abbas-SQA** [comment]
@feyzullah TestCases
1: Place Order : Bug : if QTY or Notional are required fields these should be in the required fields section not in optional fields section
<img width="974" alt="image" src="https://user-images.githubusercontent.com/104946677/191734731-18f53266-30f3-49cf-86fe-53397157bd5a.png">

2: Cancel order: Bug: when i want to select a manual entry key Pipedream page gets freezes may be somekind of memory leakage is this tried multiple times but getting this issue 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/104946677/191735963-d9ec5cbc-14b9-47f0-bd35-944e71f0d27c.png">

**Comment by feyzullah** [comment]
> @feyzullah TestCases 1: Place Order : Bug : if QTY or Notional are required fields these should be in the required fields section not in optional fields section <img alt="image" width="974" src="https://user-images.githubusercontent.com/104946677/191734731-18f53266-30f3-49cf-86fe-53397157bd5a.png">
> 
> 2: Cancel order: Bug: when i want to select a manual entry key Pipedream page gets freezes may be somekind of memory leakage is this tried multiple times but getting this issue <img alt="image" width="974" src="https://user-images.githubusercontent.com/104946677/191735963-d9ec5cbc-14b9-47f0-bd35-944e71f0d27c.png">

Hello @Hassan-Abbas-SQA for the first comment;
There are 2 props and there is such case;
* At least one of the props should be given
* Both of them cannot be given at the same time
So if we add `Qty` we cannot add `Notional` and if we add `Notional` we cannot add `Qty`.
Because of these, I needed to make them `optional` props. If any other info is needed for the prop descriptions, we can put them there.
For the second comment;
There was a bug in pagination, it should have been fixed. Can you please check again?

**Comment by Hassan-Abbas-SQA** [comment]
@feyzullah 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/104946677/191849298-e234f093-c6f5-4d61-9c16-9b39dcf75240.png">

**Comment by rrbigdog** [comment]
Can an option be added for extended hours?
