### ISSUE TITLE
[BUG] "SyntaxError Missing } in template expression" when referencing an array in a template expression

### ISSUE THREAD

**Issue by marqzman** [PipedreamHQ/pipedream#360]
**Describe the bug**
Whenever the URL is referencing an array in the template expression, I get the error `SyntaxError Missing } in template expression".

**To Reproduce**
1. Trigger the workflow with a body that includes an array.
1. Create a step that sends an http request
1. Add a query parameter with the value equal to an item in an array from the event.

**Expected behavior**
Should be able to reference an array item when building a request.

**Screenshots**
![image](https://user-images.githubusercontent.com/1877243/91222847-62572900-e6e5-11ea-83ff-290c681777d8.png)

**Desktop (please complete the following information):**
 - OS: Win 1-]
 - Browser: Brave Browser
 - Version: V1.12.114

**Additional context**
This format `event.body.links.artifacts.0.files.0.href` is how the editor suggested I select an array item. I did try `event.body.links.artifacts[0].files[0].href` and received the error `SyntaxErrorUnexpected token : in JSON at position 247`

**Comment by marqzman** [comment]
I think I just realized that the issue is with the value of `...files[0].href` since `...files[0].name` works just fine.

**Comment by dylburger** [comment]
@marqzman in this case, I believe you may need to [URL encode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) the `href` you're passing here, since you're passing the `href` as a query string parameter in a URL itself, so special characters like `/` and `:` will need to be encoded when used in this manner.

Let me know if that works for you.

**Comment by dylburger** [comment]
@marqzman we're also addressing the issue where the editor autocompletes properties like `0`, instead of the correct `[0]` reference to the array element. 

Like you noticed, manually adding an element like `[0]`, instead of using the autocomplete-suggested version, should work for now. We'll keep this ticket open and update it when we address it.

**Comment by marqzman** [comment]
@dylburger Thanks for your help, Encoding it was the solution.

**Comment by dylburger** [comment]
@marqzman we also improved the ability for you to autocomplete array indices. If you autocomplete all the way to the property `event.body.links.artifacts` and press `[` to start your reference for an element of the array, we should show you sample indices that have been sent in previous events.

For example, I sent some data with a shape like yours and included three elements in a couple of nested arrays. When I autocomplete I can now reference those elements within square brackets:

![2020-08-26 08 38 40](https://user-images.githubusercontent.com/242668/91325314-e2c66a00-e777-11ea-9a9c-21973180bb06.gif)

I hope that helps with the general issue autocompleting arrays. Thanks again for the feedback.
