### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3728]
### App
Pipeline

### Triggers
* New Ask
* Update Ask

### Actions
* Add AdHoc Step
* Create Bundle
* Add Ask to Bundle
* Attach File to Step
* Add Follower to Ask
* Add Note to Step
* Cancel Ask
* Close Ask
* Complete Step
* Create Ask
* Create Contact
* Reassign Step
* Remove Ask From Bundle
* Send Email
* Skip Step(s)
* Spawn Ask
* Update Field
* Find Ask
* Retrieve Ask

**Comment by michelle0927** [comment]
The actions and triggers listed above are for pipelineapp.io, which is not currently an app in Pipedream. I assume this issue was meant to be for pipelinecrm.com, which Pipedream does currently support. Below are the correct triggers and actions for Pipeline.

**Triggers**
- Deal Status Changed - Triggers when a deal in your PipelineDeals account is updated from one status to another
- Moved Deal - Triggers when a deal in your PipelineDeals account is moved from one deal stage to another
- New Company - Triggers when a new company is created in your PipelineDeals account
- New Deal - Triggers when a new deal is created in your PipelineDeals account
- New Person - Triggers when a new person, lead, or contact is created in your PipelineDeals account

**Actions**

- Create Activity - Creates a new activity associated to an existing person, company, or deal
- Create Event - Creates a new calendar event in your PipelineDeals account
- Create Task - Creates a new calendar task in your PipelineDeals account
- Create Company - Creates a new company in your PipelineDeals account
- Create Deal - Creates a new deal in your PipelineDeals account
- Create Person - Creates a new person in your PipelineDeals account
- Find User - Find an existing user on your PipelineDeals account
- Move Deal to Next Stage - Moves a deal to next stage
- Update Company - Updates an existing company in your PipelineDeals account
- Update Deal - Updates an existing deal in your PipelineDeals account
- Update Person - Updates an existing person in your PipelineDeals account
- Find Company - Find an existing company in your PipelineDeals account
- Find Deal - Find an exiting deal in your PipelineDeals account
- Find Person - Find an existing person in your PipelineDeals account
