### ISSUE TITLE
[SOURCE] Gitlab

### ISSUE THREAD

**Issue by puzanov** [PipedreamHQ/pipedream#376]
**Describe the event source. What app, what event?**

I'd like to receive events from Gitlab.com projects, as like we have now in Github

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**

* https://docs.gitlab.com/ee/api/README.html
* https://docs.gitlab.com/ee/user/project/integrations/webhooks.html

**Comment by dylburger** [comment]
@puzanov thanks for the request! 

Would you be open to developing this source yourself? It may not have been obvious, but all event sources are just Node.js modules that implement [a specific API](https://github.com/PipedreamHQ/pipedream/blob/master/COMPONENT-API.md). We developed a [Quickstart](https://github.com/PipedreamHQ/pipedream/blob/master/QUICKSTART.md) that shows you how to develop a basic event source, and you can take a look at all existing sources in the [`components` directory](https://github.com/PipedreamHQ/pipedream/tree/master/components) of this repo as examples. No worries if you don't have the time - we are happy to develop it ourselves - but I wanted to mention this as an option!

Since the Gitlab source would ingest data delivered via webhooks, I'd recommend taking a look at two other, similar examples:

* [Github](https://github.com/PipedreamHQ/pipedream/blob/master/components/github/custom-events.js)
* [Stripe](https://github.com/PipedreamHQ/pipedream/blob/master/components/stripe/custom-events.js) 

Both of these sources work by using your linked account to make an API request to create a webhook in the source service when the source is first created (see the code in the `activate` hook, [here](https://github.com/PipedreamHQ/pipedream/blob/master/components/github/custom-events.js#L19) and [here](https://github.com/PipedreamHQ/pipedream/blob/master/components/stripe/custom-events.js#L21), for example).
When you create the webhook via API, you'll want to pass `this.http.endpoint` as the value of the target webhook URL. This should configure the webhook in Gitlab to send webhook requests to the current component.

An event source's `run` method is triggered by incoming webhook requests. This is where you'll want to handle incoming events. Typically, the `run` method just:

* Validates the incoming event, and
* Emits the event data you'd like to send to listening workflows.

Again, the `run` methods in the [Github](https://github.com/PipedreamHQ/pipedream/blob/master/components/github/custom-events.js#L37) and [Stripe](https://github.com/PipedreamHQ/pipedream/blob/master/components/stripe/custom-events.js#L37) sources are good examples to start from.

Let me know if you're interested and I'm happy to help support you in any way.

**Comment by puzanov** [comment]
@dylburger did not know that we can create sources ourselves. That's great, I will try. Thanks

**Comment by knightrider-ux** [comment]
@dylburger  when you report for this  bug ?

**Comment by jverce** [comment]
Hi @puzanov, all event sources available in Github are now available for Gitlab as well, with a few exceptions:
* New label
* New security alert
* New star

Some missing features from the Gitlab API (mostly the ability to sort results or to expose certain data) prevented us from doing so at this moment. Hopefully if the required features are added to the API it'd be easier to implement the remaining event sources since all the scaffolding would already be there.
