### ISSUE TITLE
Streak

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3795]
### App
Streak

### Triggers
* Box Change Pipeline
* Box Change Stage
* Updated Box
* Box Email Received Count Change
* New Comment
* Updated Contact
* New Box
* New Contact
* Task Complete
* New Task
* Task Due

### Actions
* Add Contact to Box
* Add Organization to Box
* Create New Box
* Create Comment
* Create Task
* Edit Box
* Edit Task
* Get File by File Key
* Get Full Thread by Key
* Link Boxes
* Create Meeting / Call Log
* Update Contact
* Find a Box
* Find a Contact
* Find an Organization
* Find or Create Box

**Comment by andrewjschuang** [comment]
Triggers implemented in #4048.

**Comment by Hassan-Abbas-SQA** [comment]
@andrewjschuang if i have selected box2 and i want to merge it to other boxes then it should never show me the box2 in the other boxes list because it will never make any point and also while trying this i was getting bad request error which is unnecessary 
![image](https://user-images.githubusercontent.com/104946677/205756521-43746334-a311-4eb7-b6a9-b9cc7a94d0f2.png)

**Comment by Hassan-Abbas-SQA** [comment]
Rest of the things works pretty fine 
![image](https://user-images.githubusercontent.com/104946677/205756846-6c33685c-2cf3-475b-95bc-759868ce3a23.png)
