### ISSUE TITLE
Trengo

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3819]
### App
Trengo

### Triggers
* New Inbound Message
* Ticket Label Added
* New Internal Note
* New Outbound Message
* Phone Call Ended
* Phone Call Missed
* Phone Call Started

### Actions
* Create a Contact
* Log a Voice Call
* Send a Team Chat Message
* Send a Message
* Send a WhatsApp Message Template
* Find a Contact
* Find or create contact

**Comment by Hassan-Abbas-SQA** [comment]
FailedTestcases
1: Trigger (New INBOUND MESSAGE EVENT) description should be "Emit new events when an inbound message received."
instead of 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/104946677/202010643-bcaec4ba-9782-4c9f-b595-90aba40e10d4.png">
2: Action (LOG A VOICE CALL) Spelling error 
<img width="949" alt="image" src="https://user-images.githubusercontent.com/104946677/202010883-0b5dc3d1-f601-49a2-9fdb-985fc8247aff.png">

**Comment by Hassan-Abbas-SQA** [comment]
action : send a whtsapp message template
<img width="949" alt="image" src="https://user-images.githubusercontent.com/104946677/202262523-73a1fdbb-ebec-4f35-8371-f88f353ad64a.png">
