### ISSUE TITLE
Verifalia

### ISSUE THREAD

**Issue by jverce** [PipedreamHQ/pipedream#3827]
### App
Verifalia

### Actions
* Delete Email Verification Job
* Verify Email Address
* Verify List of Email Addresses
* Get Credit Balance

**Comment by Hassan-Abbas-SQA** [comment]
@lcaresia if you are asking for Enter a list of email address to verify as input from user you should provide an example of list of emails like this ['someone@gmail.com','someone2@outlook.com'] instead of only single email address it can confuse a user how to insert values.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/104946677/185211399-835f2e84-1c01-4806-a1fd-7150ebbfbecd.png">
