### ISSUE TITLE
Paylocity

### ISSUE THREAD

**Issue by EricBDuncan** [PipedreamHQ/pipedream#3907]
**Name of app / service**
Paylocity API & Webhooks

**Link to developer documentation**
https://www.paylocity.com/our-products/integrations/api-library/
https://www.paylocity.com/our-products/integrations/webhooks/

**Is lack of support preventing you from building workflows, or do you have a workaround?**
They can provide new employee onboarding information via a webhook but not in the API. I want to get their webhook data so our PowerShell scripts can start the account provisioning process.

Integrating the API might make it easier for us to collect and process employee data.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Accept the webhook data and hold it until we connect get the data and remove it.

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by sergioeliot2039** [comment]
@dylburger , is someone taking hands on new app requests that require OAuth integration (such as this one for Paylocity) while Danny is away?

**Comment by dylburger** [comment]
I'll bring it up with the team, thanks for letting me know Sergio!

**Comment by sergio-eliot-rodriguez** [comment]
Hi @EricBDuncan 

This is Sergio, I am with the integrations team at Pipedream.

I was looking at this integration request for Paylocity, and it turns out they have certain requirements to become a Technology Partner and get access to the API.

> In this phase, your goal as a prospective technology partner is to find three mutual Paylocity customers who are willing to act as an advocate and let you use them for early adoption and testing, confirm and standardize your API Access levels required to drive the integration solution, and provide appropriate client guidance around API access requests (which we will use as a measure of your integration's initial supportability). 

at [Integration requirements - Discovery](https://developer.paylocity.com/integrations/docs/integration-requirements#discovery)

Now, a customer can request an integration and provide info about the company creating the integration for the customer,

>  If you have only one Paylocity customer advocate, your integration will not qualify to be included in the Paylocity Integrations Marketplace, but you may still implement it as a customer-specific integration. 

at [Phase 1: Discovery & customer advocation](https://developer.paylocity.com/integrations/docs/partnership-requirements#phase-1--discovery--customer-advocation)
Wondering if you would like to collaborate with us as the one customer advocate to get the integration started with Paylocity?

There's some work ahead such as filling a form, and engage with Paylocity account executives, etc.

Kindly let us know if you're interested.

Thank you,
Sergio

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
