### ISSUE TITLE
[FEATURE] Keep all panels pinned open via an Account Setting

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3909]
**Is your feature request related to a problem? Please describe.**

It's very tedious to cmd + shift + P or click the Pin icon in the top right of results panels, code, configuration panels is very burdensome if you prefer to have them all auto-open by default instead of auto-closed.

**Describe the solution you'd like**
I'd like an account setting to keep all panels auto-pinned.

**Do you have a workaround?**
Individually pinning open _every single panel_.

**Comparable features in other tools?**
No.

**Additional context**
https://pipedream-users.slack.com/archives/CPTJYRY5A/p1658237897356139

**Comment by nachocab** [comment]
This is another limitation of the current pinning behavior:

1. Pin code step A
2. Click somewhere on code step B (so it's focused)
3. Click back on the code in step A

Expected behavior: nothing happens, I can continue typing
Current behavior: the code step gets focused and the screen scrolls all the way up to the code step title, so I have to scroll down to continue typing

**Comment by nachocab** [comment]
@ctrlaltdylan Any updates on this?

**Comment by ctrlaltdylan** [comment]
Not at this time @nachocab sorry, this issue will be updated when it's available.

**Comment by dannyroosevelt** [comment]
We quietly shipped defaults for your Pipedream account, to toggle auto-collapsing on and off:

<img width="239" alt="Screenshot 2023-05-31 at 9 10 41 PM" src="https://github.com/PipedreamHQ/pipedream/assets/20780753/a102820d-0c01-49ac-947b-30ec94ddf7f6">
