### ISSUE TITLE
[BUG] Monday.com - Create Item - not respecting Item Column Values

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4128]
**Describe the bug**

Using the built-in create_item for [Monday.com](http://monday.com/) I am able to create the item, but the Item column values are not being set.

**To Reproduce**
1. Create a Monday.com - Create Item action in a workflow
2. Set custom Item Column Values
3. Test
4. See a success message from the action

**Expected behavior**
Expected Behavior: On Create Item action, when I select the board, I should be able to see additional props matching columns for the board, so that user can input respective value. For example, for the board below, I should see 5 additional props matching with the highlighted columns
![FireShot Capture 513 - Pipedeam test - hungvturing monday com](https://user-images.githubusercontent.com/18277920/187716846-138aef1f-cb07-46ce-b404-a510d13ac644.png)
Reference: [Monday.com Columns Doc](https://developer.monday.com/api-reference/docs/columns-queries-1)

**Screenshots**
![4f76d55b65e82fa275d89507cdd64a35cc7f2bc0_2_1380x734](https://user-images.githubusercontent.com/2694734/187530346-84d3eb60-a46c-463e-81a3-4e3a6693fc99.png)

**Additional context**
Problem reported here: https://pipedream.com/community/t/unable-to-set-values-in-columns-for-a-new-item-in-monday-com-integration/3112/3

**Comment by vunguyenhung** [comment]
I can reproduce this bug. More detail,

I fetch all Columns in the Board
![FireShot Capture 512 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/187715569-54bc367d-575f-4d47-8741-8a05d558bd3d.png)

When I add the Column Value with the format `{"id": "column-id", "value": "column-value"}`, there's no value set in Monday.com 
![FireShot Capture 510 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/187714279-d7454116-3447-468c-9241-15b0f063b900.png)
![FireShot Capture 511 - Pipedeam test - hungvturing monday com](https://user-images.githubusercontent.com/18277920/187715343-67de0292-aa49-43bb-8ee2-7487211ecffa.png)

**Expected Behavior:** On Create Item action, when I select the board, I should be able to see **additional props** matching columns for the board, so that user can input respective value.
For example, in my board case, expected I should see 5 additional props matching 5 columns when I get the board
<img width="835" alt="image" src="https://user-images.githubusercontent.com/18277920/187716482-075f0e86-ef9c-4b19-b353-d9349b2b2cbb.png">

**Comment by michelle0927** [comment]
I found that the `create-item` action does work when the Item Column Values are entered this way:

<img width="1037" alt="Screen Shot 2022-08-31 at 1 28 39 PM" src="https://user-images.githubusercontent.com/10889229/187748206-91f4ff28-a997-423a-9222-237e469d6148.png">
However, I agree that it makes sense to have `additionalProps` for entering the column values. I created a PR #4137 to address the issue.

**Comment by Hassan-Abbas-SQA** [comment]
When i tried to create an item iam getting this error 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/104946677/187935345-4d959580-27dc-43c2-83e8-13657c94587d.png">
<img width="908" alt="image" src="https://user-images.githubusercontent.com/104946677/187935494-731eab15-1f17-4651-bb98-8257b09db1a1.png">

**Comment by michelle0927** [comment]
@Hassan-Abbas-SQA For `person`, the API is expecting a user ID. For `status`, it's expecting a status ID/index (https://view.monday.com/1073554546-ad9f20a427a16e67ded630108994c11b?r=use1). The status indexes are associated with a color, and the labels (Done, Working on it, etc.) are customizable by the user. 

We won't know for sure what kind of columns the user's board has, but I updated the component to add more useful descriptions for `status`, `person`, and `date4` since those are the ones initially included.

**Comment by Hassan-Abbas-SQA** [comment]
@michelle0927 Working Fine
<img width="908" alt="image" src="https://user-images.githubusercontent.com/104946677/187966952-2280470e-6122-40ee-9156-a0b297d63e2b.png">

<img width="908" alt="image" src="https://user-images.githubusercontent.com/104946677/187967035-8a8d277a-7e01-4fb8-b8d7-6dd030202ccb.png">
