### ISSUE TITLE
[BUG] pCloud Watch Folder trigger does not pick up events

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4136]
From a user report:
> - Folder list sometimes populates, sometimes doesn't (stuck with spinner)
> - Even if I manage to pick a folder, the "Try now" button doesn't work, the "Waiting for events" spinner spins ad infinitum...

2 potential issues to verify:
1. Folder prop potentially not working consistently
2. The Watch Folder source not picking up events

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, 

I can confirm that the Watch Folder source only show the past event and does not pick up new events. More detail:
I created the Watch Folder source on "My Video" folder
![FireShot Capture 514 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/187807007-823bf1ab-946e-4c4a-b62b-7d142aecbebb.png)

Then I uploaded some files there
![FireShot Capture 516 - pCloud __ File Manager - my pcloud com](https://user-images.githubusercontent.com/18277920/187807028-fa8d3b81-2036-4092-ab23-1e48cb7ffae2.png)

But no event were emitted. I've tried to change the Source `Folder Event` prop to both `Created` and `Modified`, but there's still no event emitted
![FireShot Capture 514 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/187807007-823bf1ab-946e-4c4a-b62b-7d142aecbebb.png)
Source log
![FireShot Capture 517 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/187807270-e97c6aea-ddb2-49ec-b7af-db99ade5981d.png)

-----

For the bug `Folder prop potentially not working consistently`, I suspect that this is related to pCloud API that fails intermittently. In this case I would suggest we retry 2-3 times with 500ms timeout each (max 1,5s), so that it would be less error showing to user

What do you think?
