### ISSUE TITLE
[SOURCE] Jira Software Cloud

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#415]
**Describe the event source. What app, what event?**
Jira Software Cloud

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
New Sprint
New Project
New User
New Comment
New Issue
New Issue (Via JQL)
Updated Issue

**Comment by dylburger** [comment]
From #411:

* Start/stop of a sprint 
* updating the status of a task (event emitted on task state transition)

**Comment by jverce** [comment]
Looks like webhook endpoints are not provided via the REST API with OAuth token authentication:
https://ecosystem.atlassian.net/browse/ACJIRA-1632

Response from `GET /rest/api/2/webhook`:
```json
{
    "errorMessages": [
        "Webhook registration for 3LO apps is currently under development. You can track the progress here: https://ecosystem.atlassian.net/browse/ACJIRA-1632."
    ],
    "errors": {}
}
```

**Comment by dylburger** [comment]
JIR should support webhooks for 3LO apps now ([see ticket](https://ecosystem.atlassian.net/browse/ACJIRA-1632)).

**Comment by feyzullah** [comment]
Hi @jverce, I am currently working with other Jira sources described in [issue](https://github.com/PipedreamHQ/pipedream/issues/1028). Can I assign myself here and do this task?

**Comment by feyzullah** [comment]
I could not create sources for sprints and projects. It should be because only the above triggers are allowed for Connect and OAuth2.0 apps.
* jira:issue_created
* jira:issue_updated
* jira:issue_deleted
* comment_created
* comment_updated
* comment_deleted
* issue_property_set
* issue_property_deleted

They say, *Limitations apply to the REST API in order to guarantee stability and performance of Jira Cloud for all apps and users.*
[See the document](https://developer.atlassian.com/cloud/jira/service-desk/webhooks/#supported-events)

**Comment by dannyroosevelt** [comment]
This is ready for release!
