### ISSUE TITLE
[ACTION, TRIGGERS] - Google Analytics new components

### ISSUE THREAD

**Issue by franceme** [PipedreamHQ/pipedream#4150]
**Google Analytics**

**[Link to developer documentation](https://developers.google.com/analytics/devguides/reporting/core/v4)**

**As far as I know there is no workaround.**

**I would like to be able to retrieve analytics for a custom website on specific time cycles. I would also like to setup alerts if a specific page is opened.**

**Comment by sergioeliot2039** [comment]
**App**
Google Analytics

**Actions**
Run Report

**Sources**
Page Opened


For developers, here's a heads up
Run Report is common action on other integration platform, I guess specifying the website would be part of the query to run the report against, which may include a hostname/url dimenion
unsure if the right endpoint is Run Report (shows as v1 of GA API), or batch Get
https://developers.google.com/analytics/devguides/reporting/core/v4/rest?hl=en
https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport
See hustname fullpag dimension at: https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema#dimensions

I didn't see webhooks available, and unless these alerts https://support.google.com/analytics/answer/1033021?hl=en#zippy=%2Cin-this-article can be created programmatically, and are sent to an URL instead of EMail, my guess is the Opened Page needs to be implemented by polling running the same RUn Report action's endpoint

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/) and [sources](https://pipedream.com/docs/components/quickstart/nodejs/sources/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by dylburger** [comment]
We've added this issue to our backlog. You can follow this issue for updates!
