### ISSUE TITLE
[ACTION] beehiiv - Subscribers support

### ISSUE THREAD

**Issue by ejwhite7** [PipedreamHQ/pipedream#4191]
**Describe the actions to be supported**

The `subscribers`  and `publications` endpoints need to be supported in two separate actions. API documentation below.

**Additional context**
Documentation: https://www.beehiiv.com/developers/docs

**Comment by ctrlaltdylan** [comment]
Thanks for filing this @ejwhite7 

Whomever picks up this card, please DM me on the Slack Community for the BeeHiiv credentials that @ejwhite7 has kindly shared with us for a test account to use.

**Comment by dannyroosevelt** [comment]
@ejwhite7 thanks for submitting a request!

It looks like you're attempting to use the integration to add new subscribers, is that right? It sounds like a built-in action would be useful. The default "scaffolding" step that we have available today is only a framework to help you get started writing code, and it should work as a GET request to the `/publications' endpoint -- are you able to confirm?

If you're familiar with Node.js, you're welcome to [contribute an action to Pipedream yourself](https://pipedream.com/docs/components/guidelines/#getting-started)! Otherwise we can add it to the team's backlog to build out for you.

Let me know if that's helpful and if you have questions.

**Comment by ctrlaltdylan** [comment]
@ejwhite7 I have updated your original post with the description of the two actions that I believe should be added as pre-built actions.

Please let us know if there are additional endpoints that need to be supported.

**Comment by ejwhite7** [comment]
Anything else needed from me here?Best,EJSent from my iPhoneOn Sep 8, 2022, at 2:22 PM, Dylan Pierce ***@***.***> wrote:﻿
@ejwhite7 I have updated your original post with the description of the two actions that I believe should be added as pre-built actions.
Please let us know if there are additional endpoints that need to be supported.

**Comment by ctrlaltdylan** [comment]
Hi @ejwhite7, no I don't believe so but we'll reach out if we get blocked. Thanks for filing this! You'll be notified on any new activity.
