### ISSUE TITLE
[BUG] Postgres: New or Updated Row source does not emit event on table with more than 100k rows 

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4198]
**Describe the bug**
When deploying new Postgres: New or Updated Row source and choosing a table with more than 100k rows. [In the code here](https://github.com/PipedreamHQ/pipedream/blob/master/components/postgresql/postgresql.app.mjs#L158-L161), because there's no initial date, so the action looks at EVERY row in the table.

**To Reproduce**
1. Create a database with more than 100k rows
2. Create a new Postgres: New or Updated Row, select the table
3. Observe that there's no event emitted

**Expected behavior**
The source should show the last 10 rows initially, then emit events for each new/updated row afterward

**Comment by DilanAthukorala** [comment]
@michelle0927 Observing following issue while creating the source
![image](https://user-images.githubusercontent.com/102980146/191101526-701bcfd8-dcf3-43ce-bdc1-e5c29b4613a5.png)

**Comment by michelle0927** [comment]
> @michelle0927 Observing following issue while creating the source 

@DilanAthukorala I haven't been able to reproduce this yet. Is "playerstable" the database `table` being selected?

**Comment by vunguyenhung** [comment]
Hello @DilanAthukorala, I think we should not move this to Change Required until we got clear sign that this is a bug. I think your error might be more related to your database. Could you try the current version of the source to see if it works?

**Comment by DilanAthukorala** [comment]
@michelle0927 @vunguyenhung , I was able to select all the fields but when clicking the "Create Source Button" this error is thrown. I assumed there's no error in my DB since it worked fine with the currently available version of the "New or Updated Row" source. Only this version is throwing the error. Please let me know if you need further information to troubleshoot this. 

[How to reproduce](https://drive.google.com/file/d/1RElHca8GFZl6tNj1GMdoArm-eXmjOXDv/view?usp=sharing)

create table
`CREATE TABLE players.playerstable (
  id serial not null,
  about varchar(100),
  age int,
  timestamp timestamp default current_timestamp
)`

**Comment by vunguyenhung** [comment]
Thank you @DilanAthukorala, keep it up! @michelle0927 could you try to reproduce following @DilanAthukorala steps?
