### ISSUE TITLE
[BUG] Not able to create Linear (API Key) Created Issue trigger due to timeout

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4265]
Originally reported by a customer via email, I confirmed the same on my end 
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/190710936-5deb63fd-691e-4cb0-88e1-240157a3e4a8.png)

**Comment by vunguyenhung** [comment]
Hello @dannyroosevelt, it seems like I couldn't reproduce this issue on my end. I created 3 sources successfully:

The first source: New Created Issue (Instant)
![FireShot Capture 571 - Source_ New Created Issue (Instant)#1 - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191146030-dc3a70ba-e230-4b13-aaeb-e144ab5e85be.png)

The second source: New Created Issue (Instant)
![FireShot Capture 569 - Source_ New Created Issue (Instant) - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191145821-d38b4ed9-01d6-4aec-9c17-57ecb572cb59.png)

The third source: New Updated Issue (Instant)
![FireShot Capture 570 - Source_ New Updated Issue (Instant)#3 - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191146001-01baa17b-cbf6-401e-9e7b-8303e28f2c4a.png)

Is it possible because your & customer's Linear account & team has other settings that my account doesn't? The error seems like come from Pipedream internals, is there any way that I can check for more error details?

**Comment by dannyroosevelt** [comment]
Interesting. Can you try creating the source from within the workflow building instead of from /sources?

**Comment by vunguyenhung** [comment]
@dannyroosevelt, I can create the Linear source from the Workflow Builder UI.
![FireShot Capture 362 - Untitled workflow - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191418278-75e8235b-a3e2-4fc2-b15e-d57b0499bb54.png)

I suspect that this issue might also related to Linear API: Create Webhook intermittently takes longer than Pipedream's timeout duration.

**Comment by dannyroosevelt** [comment]
@vunguyenhung I got Jacob to help investigate this and it might be due to the source automatically trying to fetch too many events on deploy. Can you get a ticket on the board to make sure Linear sources (for both `linear` and `linear_app`) only fetch 100 events on deploy?

**Comment by vunguyenhung** [comment]
I think Jacob investigation makes sense @dannyroosevelt! I have created the ticket here: https://github.com/PipedreamHQ/pipedream/issues/4325 and moved it to near-top of component backlog
