### ISSUE TITLE
[IMPROVEMENT] Linear & Linear App sources: Only fetch 100 records for initial historical events

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4325]
Related to the bug here https://github.com/PipedreamHQ/pipedream/issues/4265

**Is your feature request related to a problem? Please describe.**
When deploying a new Linear New Issue Created (Instant) source, the source will automatically fetch **all** existing Linear issues [per the code here](https://github.com/PipedreamHQ/pipedream/blob/2cc556085eec3fda652f88be60c04426c2a0aef0/components/linear_app/sources/common/webhook.mjs#L52-L54). This fetch process might take longer than Pipedream's source timeout, causing Pipedream to throw timeout error, resulted in the source failed to be created

**Describe the solution you'd like**
When Linear and Linear App sources are deployed, only fetch **100** existing resources (issues, comment, etc...) to emit initial historical events

**Do you have a workaround?**
No

**Comment by jcortes** [comment]
Hi @vunguyenhung Can you explain more in detail how to reproduce this bug please?

**Comment by jcortes** [comment]
Hi @vunguyenhung I've tested it and was able to reproduce. So I think one strategy we can try to use it's just to display the latest 200 items because otherwise we'll have that kind of timeout from Pipedream and then just start listening on new webhook events. I made some modifications so you can test them out. Also made some improvements and refactors.

**Comment by vunguyenhung** [comment]
Hi everyone, all test cases are passed! Ready for release!

Test report
[Notion_4368.pdf](https://github.com/PipedreamHQ/pipedream/files/9707131/Notion_4368.pdf)
