### ISSUE TITLE
[APP]**integration in sending messages from a google sheet to whatsapp**

### ISSUE THREAD

**Issue by arg1972** [PipedreamHQ/pipedream#4330]
**Name of app / service**

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergioeliot2039** [comment]
interesting @arg1972 requests!!

First off,
Google Sheet is integrated here: https://pipedream.com/apps/google-sheets
WhatsApp is blocked because we can't create an app that others can use, we are waiting for Meta, WhatsApp's parent company  to roll out a feature allowing this. We are tracking WhatsApp app integration here: https://github.com/PipedreamHQ/pipedream/issues/2896

Second, it seems you are trying to build a workflow that uses Google Sheet and WhatsApp right?
Here is a guide for building workflows on Pipedream: https://pipedream.com/docs/workflows/
You can use [WhatsApp by Online Live Support](https://pipedream.com/apps/online-live-support) integration as a workaround for WhatsApp.

With this are you all set, or do you need specific triggers and/or actions different to the ones we have integrated now?

**Comment by dylburger** [comment]
Thanks for the request! We've added this to [our integrations backlog](https://github.com/orgs/PipedreamHQ/projects/8/views/1), and we'll update this ticket with progress.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
