### ISSUE TITLE
[BUG] Gmail Send Message action returns an error but still sends a message

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4614]
Looks like we're returning the below error in certain cases, but the emails still send. This is especially problematic in cases where we attempt to retry the seemingly failed step.

>**TypeError**
> this.to.join is not a function

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/198890279-67a6feb5-7b8c-4a37-ae40-5ddf4844d023.png)

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/198890317-0a3022cd-691a-4401-a562-bb7950648789.png)

**Comment by dannyroosevelt** [comment]
@andrewjschuang can you please take a look?

**Comment by andrewjschuang** [comment]
@dannyroosevelt this happens with any `array` type prop (in this case `string[]`).
If a user tries entering a custom expression and instead of an array they insert a string, then the error above will occur.

I will adjust the code to catch this case, but FYI this is a global behaviour in the Pipedream UI with `array` props.

**Comment by andrewjschuang** [comment]
> @dannyroosevelt this happens with any `array` type prop (in this case `string[]`). If a user tries entering a custom expression and instead of an array they insert a string, then the error above will occur.
> 
> I will adjust the code to catch this case, but FYI this is a global behaviour in the Pipedream UI with `array` props.

Actually, nvm. This above was not the issue here.
