### ISSUE TITLE
[BUG] Xero add items to sales invoice

### ISSUE THREAD

**Issue by TomVonWood** [PipedreamHQ/pipedream#4661]
**Describe the bug**
1. When I add items as an array I get an error (Unexpected token o in JSON at position 1) 

2. When I add items as individual objects (in seperate steps) the step runs but no items are added to the invoice.

[See the discussion on the community here](https://pipedream.com/community/t/what-dataformat-does-the-xero-integration-expect/3616/13)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/115629329/199761901-51f9cb0d-5531-4b89-b6f8-211c3422dd46.png)
**Desktop (please complete the following information):**

**Comment by vunguyenhung** [comment]
Hello @TomVonWood, I'm able to reproduce your issue with simple array. I will add this to our component backlog
![0807 - 0711](https://user-images.githubusercontent.com/18277920/200206845-ba1e2211-00e2-4b0f-8293-71c5b5d8c256.png)

**Note:**
I've also tried single object and the action executed successfully, but I see there's no item added in the invoce
![0810 - 0711](https://user-images.githubusercontent.com/18277920/200206965-897fad93-6e9b-44d8-8c6a-6760ecd465fa.png)

Expected behavior:
- I should be able to add the Line Items as array using expression syntax
- I should see new Line Item added in Xero invoice when the action executed successfully

**Comment by Hassan-Abbas-SQA** [comment]
![image](https://user-images.githubusercontent.com/104946677/200593394-218ee91c-b346-4a91-86fe-724eadf18578.png)

**Comment by Hassan-Abbas-SQA** [comment]
https://user-images.githubusercontent.com/104946677/200623858-0418523a-f916-4b8f-8f02-43ef1340378b.mov
