### ISSUE TITLE
[Feature] About Notion api

### ISSUE THREAD

**Issue by boyce0215** [PipedreamHQ/pipedream#4760]
Hi!
I want use "create-page-from-database" by sync my google  calendar. But I find the date property don't support end date incloude time.

I read Notion API Reference it has write about that. Can Added it?

Thank you

**Comment by sergioeliot2039** [comment]
User appears to be asking about an enhancement on the Notion "Create Page from Database" action,

![image](https://user-images.githubusercontent.com/25184117/202247190-5e6fc11a-86c8-4a6b-ab8f-bc990b1bbff3.png)

**Comment by dannyroosevelt** [comment]
@boyce0215 can you tell me a bit more about the problem you're trying to solve? Or can you link me to the docs you're looking at?

**Comment by boyce0215** [comment]
@dannyroosevelt I try to create new event at google calendar, and want make it sync to my notion database.
But I find property about "date", it only can typing Start date or End date. Not both!
example
<img width="938" alt="image" src="https://user-images.githubusercontent.com/25250890/202330861-bfac72a3-b4b1-4f97-b52f-6f6508facaf2.png">

**Comment by dannyroosevelt** [comment]
Can you confirm what action you are using? I see an end date prop here:
https://pipedream.com/apps/google-calendar/actions/create-event

**Comment by boyce0215** [comment]
My trigger use this.
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/25250890/202363344-f1d5185c-3535-4884-987a-cc4f9eef545d.png">

**Comment by boyce0215** [comment]
@sergioeliot2039 I use the query_database and then can see "date" has "end" this key. so how can I take my google calendar event into this value?
<img width="956" alt="image" src="https://user-images.githubusercontent.com/25250890/202365273-0e718afb-7e43-4cd2-b3e4-9bca9b2f6604.png">

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergioeliot2039** [comment]
Hi there @boyce0215 

I believe you are trying to build a filter to be applied against some Notion actions, namely "Query Database", and "Create Page from Database"; you want to build this filter and use the event start and end dates from the Google Calendar "New Event" trigger or "Create Event" action (this is not clear). 

I believe you find difficult to build such a filter.

I have created for you a working filter that you can use inside query_database's filter property that uses these dates:

//
{ "property": "title", "rich_text": { "does_not_contain":  "{{steps.trigger.event.start.date}}" } }
//

> {
>     "filter": {
>         "and": [
>             {
>                 "property": "title",
>                 "rich_text": {
>                     "does_not_contain": "**{{steps.trigger.event.start.date}}**"
>                 }
>             },
>             {
>                 "property": "title",
>                 "rich_text": {
>                     "does_not_contain": "**{{steps.trigger.event.start.date}}**"
>                 }
>             }
>         ]
>     }
> }

Note that both **steps.trigger.event.start.date** and **steps.trigger.event.start.date** are expression taken from a prevous workflow space (in my case these come from a New Event trigger).

The filter shows how two take into account start date and end date, , however, you will have to do further adjustments, because I used "does not contain" filter type for sake of an example on how to include both properties into the [compound filter ](steps.trigger.event.start.date). Please refer to Notion documentation about the [Filter object](https://developers.notion.com/reference/post-database-query-filter) to check out which filters are available and the syntax as a guidance for writting the filter you need.

Hope this helps.

**Comment by sergioeliot2039** [comment]
@boyce0215 when you get a chance, can you confirm if this is the issue you were encountering?
