### ISSUE TITLE
[BUG] @pipedream/axios library does not accept baseURL param

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4790]
**Describe the bug**
I imported `@pipedream/axios` library following [this document](https://pipedream.com/docs/pipedream-axios/#why-pipedream-platform-axios)
Then I proceed to use the library, passing the `baseURL` param that is a part of [standard axios request config (opens new window)](https://github.com/axios/axios#request-config). But the request failed
<img width="819" alt="image" src="https://user-images.githubusercontent.com/18277920/202961052-06bf6f3a-b9e8-4c1a-8623-ff8b4a8a5bb2.png">

When I use the full `url`, it succeeded
<img width="821" alt="image" src="https://user-images.githubusercontent.com/18277920/202961230-d5064318-1d4d-4cd6-9e10-978d44f5e491.png">

**To Reproduce**
1. Create a new Node.js code step
2. Add the following code
```js
// To use any npm package on Pipedream, just import it
import { axios } from "@pipedream/platform"

export default defineComponent({
  async run({ steps, $ }) {
    return await axios($, {
      baseURL: "https://httpstat.us",
      url: "/200"
    })
  },
})
```
3. Test the action, observed that the action returns error

**Expected behavior**
The action should be executed successfully. The request is sent to the destination and it can receive a response.

**Additional context**
First reported by a customer here https://pipedream-users.slack.com/archives/CPTJYRY5A/p1668964042950259

**Comment by GTFalcao** [comment]
@vunguyenhung , as [we could not find a way](https://pipedream-users.slack.com/archives/G01J50YGJGP/p1669065284106239) to test the platform package directly without publishing it, I published its contents (exactly as they are on [this branch](https://github.com/PipedreamHQ/pipedream/tree/4790-axios-baseurl-fix)) as a separate package named `pd-platform-test-gtfalcao`.

![image](https://user-images.githubusercontent.com/48412907/203443123-dd699c0e-cfc2-4b20-bc36-19c2ac6afb6f.png)

When the official `platform` package is updated and this issue is closed, I will unpublish this package.

**Comment by vunguyenhung** [comment]
Thank you for testing this @GTFalcao! After the code is approved I will move this to ready for release and test it again after the package is released

**Comment by GTFalcao** [comment]
![image](https://user-images.githubusercontent.com/48412907/203624360-8005aded-a411-4323-985a-c8c5e32b2693.png)
Platform package updated successfully
