### ISSUE TITLE
[ACTION] Update Signatures For Organization Gsuite

### ISSUE THREAD

**Issue by Modocosm** [PipedreamHQ/pipedream#4801]
**Is there a specific app this action is for?**
gmail in gsuite

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.google.com/gmail/api/guides/alias_and_signature_settings#managing_signatures
https://googleapis.dev/nodejs/googleapis/latest/gmail/classes/Resource$Users$Settings$Sendas.html#patch

**Comment by vunguyenhung** [comment]
I can confirm that currently there's no action for this
<img width="819" alt="Screen Shot 2022-11-22 at 20 18 09" src="https://user-images.githubusercontent.com/18277920/203323790-c3755d0c-42c2-40db-8374-0ba969b2df40.png">

And I've also added the API doc that uses Google APIs Node.js lib: https://googleapis.dev/nodejs/googleapis/latest/gmail/classes/Resource$Users$Settings$Sendas.html#patch

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by andrewjschuang** [comment]
Currently we don't have the required scopes for this method. As seen in [the docs](https://developers.google.com/gmail/api/reference/rest/v1/users.settings.sendAs/patch#authorization-scopes), one of these is necessary:

- https://www.googleapis.com/auth/gmail.settings.basic
- https://www.googleapis.com/auth/gmail.settings.sharing

@dannyroosevelt is adding one of these scopes be viable?

**Comment by dannyroosevelt** [comment]
Sorry for the delay on this -- both of those are **restricted scopes**, which have an unreasonably high bar to get approval for, from Google.

The best solution right now would be to build out the action for the Gmail Developer app.

@Modocosm have you seen the [Gmail Developer app](https://pipedream.com/apps/gmail-custom-oauth#getting-started)? It uses your own custom client ID and secret from a Google Cloud Project, instead of Pipedream's app, in order to work around Google's onerous requirements. Is that a viable solution for you?

**Comment by Modocosm** [comment]
> Sorry for the delay on this

😄 _(no worries at all)_ 😄 
> The best solution right now would be to build out the action for the Gmail Developer app.
> @Modocosm have you seen the [Gmail Developer app](https://pipedream.com/apps/gmail-custom-oauth#getting-started)? It uses your own custom client ID and secret from a Google Cloud Project, instead of Pipedream's app, in order to work around Google's onerous requirements. Is that a viable solution for you?

### Most Probably, 
the google cloud account is very recently setup though.
No idea if that impacts that scope.

> Confirmed it works with the https://github.com/PipedreamHQ/pipedream/pull/4816 in Gmail Developer App, just be sure the add the scope https://www.googleapis.com/auth/gmail.settings.basic when authenticating your account in Pipedream.

# **Epic!** Thanks Y'all!
## Really appreciate the solution :) Will give it a shot later today.
Will Confirm then

**Comment by vunguyenhung** [comment]
Hello @Modocosm @andrewjschuang, I've tested this action and verified it working
![12 26 10 - 13 - 12 - 2022](https://user-images.githubusercontent.com/18277920/207234014-76c3785a-0b1d-49a7-bb25-a2d9bfe87db8.png)

Some notes regarding the usage,
1. I need to add both scopes `https://mail.google.com https://www.googleapis.com/auth/gmail.settings.basic` in order for the Oauth flow to work
<img width="1919" alt="Screen Shot 2022-12-13 at 12 28 26" src="https://user-images.githubusercontent.com/18277920/207234307-e45425a9-2bf5-4291-b8fd-752f30323f94.png">

3. You might need to format it as HTML
![12 26 10 - 13 - 12 - 2022](https://user-images.githubusercontent.com/18277920/207234014-76c3785a-0b1d-49a7-bb25-a2d9bfe87db8.png)

**Comment by Modocosm** [comment]
I have it working when targetting self.

But not (as org owner/admin) targeting anyone other org emails. 🤔

**Comment by vunguyenhung** [comment]
> But not (as org owner/admin) targeting anyone other org emails. 🤔

May I ask what is your usecase for this? Is it possible for you to have Pipedream connect to that specific org account?

I searched through the internet and find an article here to set Org's default footer: https://www.techrepublic.com/article/how-to-set-a-gmail-signature-for-your-organization/ 

Is it fulfill your need?

**Comment by vunguyenhung** [comment]
> But not (as org owner/admin) targeting anyone other org emails. 🤔

@andrewjschuang, on another note, I think we can [update this line right here to have it use a prop](https://github.com/PipedreamHQ/pipedream/blob/ecee3bbb88acf637465c514038d14729be586a5b/components/gmail_custom_oauth/gmail_custom_oauth.app.mjs#L25) to update other org email. Though I have not tested it since I don't have org admin email

**Comment by Modocosm** [comment]
> @Modocosm May I ask what is your usecase for this? Is it possible for you to have Pipedream connect to that specific org account?
> 
> I searched through the internet and find an article here to set Org's default footer: https://www.techrepublic.com/article/how-to-set-a-gmail-signature-for-your-organization/
> 
> Is it fulfill your need?

Footers are assigned/enforced specifically for compliance disclaimers. mostly unstyled.
Sigs separately would take user variables and enforce branding consistency in (especially) external communications. Universally, the whole team is in favor of this. As the brand evolves, it would help reduce redundant data entry busy work

**Comment by andrewjschuang** [comment]
> @andrewjschuang, on another note, I think we can [update this line right here to have it use a prop](https://github.com/PipedreamHQ/pipedream/blob/ecee3bbb88acf637465c514038d14729be586a5b/components/gmail_custom_oauth/gmail_custom_oauth.app.mjs#L25) to update other org email. Though I have not tested it since I don't have org admin email

@vunguyenhung `email` in [this line](https://github.com/PipedreamHQ/pipedream/blob/ecee3bbb88acf637465c514038d14729be586a5b/components/gmail_custom_oauth/actions/update-signature/update-signature.mjs#L18) is an optional prop that the user can type in to change the signature for another email. Though I have not tested for the same reason

**Comment by vunguyenhung** [comment]
@andrewjschuang, per this [Gmail API doc here](https://developers.google.com/gmail/api/reference/rest/v1/users.settings.sendAs/update), it allows us to set the `userId` as email in order to set signature for other org email.
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/18277920/207313152-1814f557-aabe-4c4e-9e9a-c57ecb032d9e.png">


I think we can use the existing `Email` prop, we just need to pass the email to the `userId` field when it is set by user, or `me` if it is not set.

What do you think?

**Comment by andrewjschuang** [comment]
@vunguyenhung from my understanding of this doc, the parameter `sendAsEmail` is the one that configures another email to have the signature set

**Comment by vunguyenhung** [comment]
Hello @andrewjschuang, @Modocosm have tested the `Email` prop, but [it is not working for other org email for his case](https://github.com/PipedreamHQ/pipedream/issues/4801#issuecomment-1347776236). Is it possible to try pass the email to `userId` param for him to test if it works?

I'm sorry for back-and-forth communication 🙏 I'd love to have it work for @Modocosm.

**Comment by andrewjschuang** [comment]
@vunguyenhung np, can you please test this branch? - **gmail-update-signature-test**

**Comment by vunguyenhung** [comment]
Thank you @andrewjschuang! Hello @Modocosm, since I don't have the Gmail Org account to test. 

Could you do the following steps to deploy the action to your account to test on your side?
1. Start the Pipedream development environment on Gitpod, following the guidelines here https://pipedream.com/blog/building-a-custom-pipedream-action-component-with-gitpod/
2. On Gitpod, paste your Pipedream API Key (can be acquired from your [Pipedream setting page](https://pipedream.com/settings/account)) into the terminal
![image](https://user-images.githubusercontent.com/18277920/207485295-a5fc02d2-ad1b-422f-8920-324c6fd41dfb.png)
3. Then publish the new Update Signature action code by @andrewjschuang by adding the following commands to the terminal:
```bash
# Checkout the git branch
git checkout origin/gmail-update-signature-test

# Publish the Update Signature action
pd publish components/gmail_custom_oauth/actions/update-signature/update-signature.mjs
```
4. Finally, you can add the Pipedream action from `My Action` section
<img width="822" alt="Screen Shot 2022-12-14 at 08 59 01" src="https://user-images.githubusercontent.com/18277920/207486503-e622a9f2-5f17-4a35-aa91-258d83f5a322.png">
<img width="821" alt="Screen Shot 2022-12-14 at 08 59 38" src="https://user-images.githubusercontent.com/18277920/207486586-0f8d7499-7b0d-4e7d-a693-601794d98cbb.png">

**Comment by vunguyenhung** [comment]
Hello @Modocosm, we figures that to update the signature for other org email, you'll need to use other kind of authentication which is Google Cloud Service account with delegated domain-wide authority
`Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.`

So we have updated the Update Signature action to use Google Cloud authentication. The new code is available in the branch `checkpoint-gmail` now, could you test it following the below steps?

1. Start the Pipedream development environment on Gitpod, following the guidelines here https://pipedream.com/blog/building-a-custom-pipedream-action-component-with-gitpod/
2. On Gitpod, paste your Pipedream API Key (can be acquired from your [Pipedream setting page](https://pipedream.com/settings/account)) into the terminal
![image](https://user-images.githubusercontent.com/18277920/207485295-a5fc02d2-ad1b-422f-8920-324c6fd41dfb.png)
3. Then publish the new Update Signature action code by @andrewjschuang by adding the following commands to the terminal:
```bash
# Checkout the git branch
git checkout origin/checkpoint-gmail

# Publish the Update Signature action
pd publish components/gmail_custom_oauth/actions/update-signature/update-signature.mjs
```
4. Finally, you can add the Pipedream action from `My Action` section
<img width="822" alt="Screen Shot 2022-12-14 at 08 59 01" src="https://user-images.githubusercontent.com/18277920/207486503-e622a9f2-5f17-4a35-aa91-258d83f5a322.png">
<img width="821" alt="Screen Shot 2022-12-14 at 08 59 38" src="https://user-images.githubusercontent.com/18277920/207486586


Thank you so much for your support @Modocosm!

**Comment by Modocosm** [comment]
Alrighty, im back, thanks for the detailed walkthrough! Much appreciated :)

Ill give it a shot shortly and let you know.

**Comment by Modocosm** [comment]
![image](https://user-images.githubusercontent.com/106853815/208215887-8b542eb2-ae72-4870-af5a-8c2d1a0dd97e.png)

thanks for y'alls patience, have tested the new code, this is the error.

**Comment by Modocosm** [comment]
# Correction! Its working :D my bad.

Thanks @andrewjschuang @vunguyenhung! 🥳

**Comment by andrewjschuang** [comment]
@Modocosm That's great to hear, thanks for testing it out!
@vunguyenhung I'll create another PR so this gets published to the official registry. Thanks for kindly insisting on this feature, turned out great!
