### ISSUE TITLE
[BUG] Nordigen account disconnects after 1 month

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4894]
**Describe the bug**
I use the Nordigen source to retrieve transactions on my account. Everything is working fine for 1 month and then I don't receive new transactions. I found out that my Nordigen account disconnects after1 month. I have to reconnect it every month to fix the issue.

![](https://www.pixenli.com/image/8HvZtxZt)

**To Reproduce**
1. Create a Nordigen source and connect it correctly
2. Wait 1 month for your Nordigen account to be disconnected

**Expected behavior**
It should not disconnect.

**Comment by vunguyenhung** [comment]
As I wasn't able to reproduce this, I'll add tracked-internally for Pipedream's Engineer to do the further check 🙏

**Comment by dannyroosevelt** [comment]
@LucBerge we have a suspicion that this might be related to how Nordigen is handling authentication, since there are a few unique / off-spec parts of their authentication strategy:
1. They expire their `refresh_token` after 30 days (this is typically a longer-lived token, unlike `access_token`)
2. They declare the expiry of the `access_token` via `access_expires` instead of the standard, `expires_in`

We made a change to the app's refresh strategy yesterday that should hopefully handle #1, and we have a patch in review now that should enable us to handle #2 ([being tracked here](https://github.com/PipedreamHQ/pipedream/issues/4566))

**Comment by LucBerge** [comment]
So I guess refreshing the `refresh_token` every 30 days is the solution ?!
I'll let you know if it works in January, thank you

**Comment by dylburger** [comment]
This should be completed! Please let us know if you see any issues

**Comment by dannyroosevelt** [comment]
FYI we just shipped an update to handle Nordigen's custom `access_expires` field, which should hopefully resolve the issue.

**Comment by LucBerge** [comment]
Ok, I'll let you know here
