### ISSUE TITLE
[BUG] Github - Create or update file contents missing `sha` prop

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#5015]
**Describe the bug**
The `sha` prop is missing from the **Github - create or update file contents** action.

The `sha` is necessary to be able to _update_ files within a Github repo.

**To Reproduce**
1. Attempt to update an exisiting file in a repo using this action
2. Receive a 409 error from the Github API

**Expected behavior**
I expect to be able to define a `sha` of the file being overwritten by the action as stated in the github docs:

https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents

<img width="607" alt="CleanShot 2022-12-21 at 16 01 32@2x" src="https://user-images.githubusercontent.com/2694734/209002043-ea5136b7-445c-4a4a-b2b3-5f9c6bc8144e.png">

**Screenshots**
<img width="930" alt="CleanShot 2022-12-21 at 16 01 45@2x" src="https://user-images.githubusercontent.com/2694734/209002106-de8bc1a1-3f8e-4155-b974-85b3f705d186.png">

**Comment by DilanAthukorala** [comment]
@ctrlaltdylan I was able to update the the file content successfully without sha, Is there certain type of configuration that require sha (if so we can add it as a optional param)? 
![image](https://user-images.githubusercontent.com/102980146/209196545-7adafaca-30aa-4fff-afad-36fd48e91fdb.png)

**Comment by alysonturing** [comment]
Hello @ctrlaltdylan, I’m working on this bug and we are adding the `sha` prop automatically, by identifying that we should update the file instead of creating a new one..
I highlighted in the code where its implemented, I also tested it in my own repository and it’s working for updating files. I wonder why you got an error... probably by something else, unrelated, but I’d like to investigate further.

![image](https://user-images.githubusercontent.com/103650302/210261819-00e24621-cc61-4c23-a453-23c81b342877.png)
