### ISSUE TITLE
[TRIGGER] WhatsApp Business - New Message source

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5213]
**Describe the event source. What app is this for, and what event does the trigger correspond to?**
WhatsApp Business

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.facebook.com/docs/graph-api/webhooks/getting-started/webhooks-for-whatsapp

**Comment by rrbbtalnorth** [comment]
Hi, I have created a scenario - send a text message with WhatsApp Business API on new requests from HTTP / Webhook API

https://pipedream.com/apps/http/integrations/whatsapp-business/send-text-message-with-whatsapp-business-api-on-new-requests-from-http-webhook-api-int_Qmsndme

I took this scenario

And my problem - the webhook after I receive one message on WhatsApp instead of sending the response just once, it sends the response continuously
