### ISSUE TITLE
[ACTION] Shopify - Get Products

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5364]
**Is there a specific app this action is for?**
Shopify

**Please provide a link to the relevant API docs for the specific service / operation.**
https://shopify.dev/api/admin-rest/2023-01/resources/product#get-products?ids=632910392,921728736

The user can optionally select Product IDs to get only data of some products

**Comment by Kirito-Excalibur** [comment]
So you want to change the docs of this page? https://shopify.dev/api/admin-rest/2023-01/resources/product#get-products?ids=632910392,921728736

**Comment by zecul** [comment]
> So you want to change the docs of this page? https://shopify.dev/api/admin-rest/2023-01/resources/product#get-products?ids=632910392,921728736

Right now "[Shopify search for product](https://pipedream.com/@furtherrecords/search-for-products-from-shopify-api-p_A2CbaRN/build)" ony uses "Title". I would like it to instead/as well use "Product ID" because it is unique. Title is not unique in my store.

![image](https://user-images.githubusercontent.com/123815443/215966881-57e7a90d-4c5a-42f1-afed-7a6c2e0fdbfa.png)

https://github.com/PipedreamHQ/pipedream/blob/master/components/shopify/actions/search-products/search-products.mjs

**Comment by zecul** [comment]
Other useful but less vital search fields would be:

collection_id
product_type
vendor

**Comment by Hassan-Abbas-SQA** [comment]
TestPassed Functionally Positive Scenario
<img width="451" alt="Screenshot 2023-02-07 at 11 58 22 PM" src="https://user-images.githubusercontent.com/104946677/217340050-09945594-58ee-42b7-a6a9-8a5196cd991e.png">

TestFailed 
please add some description about how do a user can add id or list of ids manually because when i provided it an array with the id its throwing an error
<img width="599" alt="image" src="https://user-images.githubusercontent.com/104946677/217340411-9ca12f25-eb37-4360-8866-45dcaa73260f.png">

**Comment by michelle0927** [comment]
@Hassan-Abbas-SQA I updated `search-products` to allow `productIds` to be entered as a string instead of an array (the screenshot above shows it entered as a string - "[132323]"), and I updated the description of `collectionId` to provide more information.
