### ISSUE TITLE
[ENHANCMENT] PagerDuty: New or Updated incident - add more data in event body 

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5377]
**Is your feature request related to a problem? Please describe.**
When the PagerDuty: New or Updated incident source emit new events, it only include some fields (`id`,  `event`, `incident`) on the event body. But users sometime need data from other fields such as `channel`
<img width="1200" alt="image (2)" src="https://user-images.githubusercontent.com/18277920/216019800-57c97edb-d986-4cfd-8cf7-11c82921ab66.png">

**Describe the solution you'd like**
Include the `channel` field into the event body.

**Do you have a workaround?**
No

**Additional context**
First reported by a user here: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1675245755150179

**Comment by Hassan-Abbas-SQA** [comment]
@vunguyenhung please test this issue as i can’t create PagerDuty account tried with VPN too but i don’t know why its happening due to this i can’t integrate or test this as i can see that you already have PagerDuty Account it would be better if you can please test it iam assigning this issue to you 
![image](https://user-images.githubusercontent.com/104946677/216395605-aef8fb81-41e5-4e6e-8488-922aaa9e1b4f.png)
<img width="897" alt="image" src="https://user-images.githubusercontent.com/104946677/216395851-abfebed2-b4b2-4475-9be7-0c21aa4fd7dd.png">
