### ISSUE TITLE
[BUG] New Big Cartel account connection has incorrect credentials

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5465]
**Describe the bug**
After connecting a new Big Cartel account, the account name section was incorrectly displayed, and the stored credentials is invalid

**To Reproduce**
1. Create a new workflow, add a Node.js action using Big Cartel app
2. Try to create a new Big Cartel account connection, observed that the new account has the text display `([object Object])`
<img width="731" alt="image" src="https://user-images.githubusercontent.com/18277920/218407631-ba25ae42-23f2-4621-b64a-2a472a406cd2.png">
3. Using the new account connection to call the sample request, observe that it failed
<img width="683" alt="image" src="https://user-images.githubusercontent.com/18277920/218407959-0a0c9e75-c6a4-4234-8c64-42ffe68fd05a.png">

4. Though the action passed if I used the account that I connected on Sep 2022
<img width="693" alt="image" src="https://user-images.githubusercontent.com/18277920/218422395-d57687b7-c242-41ac-b488-6ef5fca178d8.png">

**Expected behavior**
The new Big Cartel account connection should be displayed correctly, and the stored credentials should be valid to call Big Cartel API

**Additional context**
Might related to a customer report here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1676275017367019

**Comment by sergioeliot2039** [comment]
sorry for the pivoting for a moment I though this was a problem on the way data is being displayed,
but i see `account_id` has a `null ` value under the `auth `bag 

![image](https://user-images.githubusercontent.com/25184117/219826957-a7fd0623-fcdf-4177-9a3c-72df8d85b125.png)

however i you see the connection from the Accounts page under PD UI, you see the value properly set 

![image](https://user-images.githubusercontent.com/25184117/219826966-2df24072-0e80-4327-bef2-8ce311e24707.png)
so i think this is might be an internal issue since the value is properly obtained from the oauth flow?

can you confirm / help triage properly @dannyroosevelt ?

**Comment by dannyroosevelt** [comment]
Thanks @vunguyenhung and @sergioeliot2039, this is fixed (you'll have to reconnect your account).
