### ISSUE TITLE
[BUG]  Gmail (Developer App) credentials expire from time to time

### ISSUE THREAD

**Issue by ze-finky** [PipedreamHQ/pipedream#5494]
**Describe the bug**
I use this feature to check when new emails are received, but from time to time the workflow stop working as Gmail credentials expire and I need to manually log in again. Besides that, this error occurs silently, and I can only correct it after someone using the results of the workflow indicates me that something didn’t go through.

**To Reproduce**
1. Create a source using Gmail (Developer App), which triggers when an email arrives (timer every 15min, standard)
2. Just wait and it will expire after 7 days or so
3. The error appears only in the Log of the Source:

Error: Invalid Credentials
at Gaxios._request (/var/task/node_modules/gaxios/src/gaxios.ts:158:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async OAuth2Client.requestAsync (/var/task/node_modules/google-auth-library/build/src/auth/oauth2client.js:382:18)
at async Object.listMessages (file:///var/task/user/gmail/gmail.app.mjs:119:24)
at async Object.run (file:///var/task/user/gmail_custom_oauth/sources/common/polling.mjs:64:22)
at async /var/task/index.js:122:11
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async Runtime.exports.main [as handler] (/var/task/index.js:60:20)

**Expected behavior**
Not to have to login again, or at least et some notification when it occurs.

**Comment by vunguyenhung** [comment]
Hello @ze-finky, thank you for raising this issue. 

Hello @sergioeliot2039, could you advice if this could be improved in Pipedream's OAuth flow?

**Comment by sergioeliot2039** [comment]
Hello everyone

@vunguyenhung 
I think there are chances that this could be tackled (or help troubleshoot in any case) by the team because Pipedream is managing authentication (in this case implementing the OAuth flow) despite using the user's OAuth client they created on their Google Cloud Platform account.

However, taking a look at the instructions found in the Gmail Developer app [Read.ME](https://github.com/PipedreamHQ/pipedream/tree/master/components/gmail_custom_oauth) it is contemplated that users have to enter their own OAuth scopes, when connecting their Gmail Developer App.

So @ze-finky one, there are chances that you need an additional scopes to avoid your access token expiring, by specifying an online mode according to article [HTTP OAuth2 Connection to Gmail and Google API fails after 60 mins due to token expiry](https://support.workato.com/en/support/discussions/topics/1000084066) adressing a similar case. Can you please check it it and see if it is revelant to your issue? 

Finally, @dannyroosevelt may have more advice

**Comment by sergioeliot2039** [comment]
@ze-finky 

As an alternative to the notifications mentioned in the issue's **Expected Behavior** you can see the "Accounts", page and look for connections that don't have good health, they are marked with a red circle, such as the one for **Coinbase** in the following screenshot. I'd expect your Gmail Developer App shows this red circle when it starts to fails. So maybe you can manually monitor it

![image](https://user-images.githubusercontent.com/25184117/219380188-7ed22898-b6e1-4d46-a599-5fac18bb3e90.png)

**Comment by ze-finky** [comment]
> Hello everyone
> 
> @vunguyenhung I think there are chances that this could be tackled (or help troubleshoot in any case) by the team because Pipedream is managing authentication (in this case implementing the OAuth flow) despite using the user's OAuth client they created on their Google Cloud Platform account.
> 
> However, taking a look at the instructions found in the Gmail Developer app [Read.ME](https://github.com/PipedreamHQ/pipedream/tree/master/components/gmail_custom_oauth) it is contemplated that users have to enter their own OAuth scopes, when connecting their Gmail Developer App.
> 
> So @ze-finky one, there are chances that you need an additional scopes to avoid your access token expiring, by specifying an online mode according to article [HTTP OAuth2 Connection to Gmail and Google API fails after 60 mins due to token expiry](https://support.workato.com/en/support/discussions/topics/1000084066) adressing a similar case. Can you please check it it and see if it is revelant to your issue?
> 
> Finally, @dannyroosevelt may have more advice

Regarding this similar case, it suppose that can be the solution indeed, but I believe the connection setup is part of the Pipedream code, so not something I set in Google Cloud Console, no?! Or do you think this can be appended to the URI? https://api.pipedream.com/connect/oauth/oa_G7Ain6/callback

**Comment by dannyroosevelt** [comment]
@ze-finky apologies for the delay and issues with this one -- we're checking into this. I haven't been able to reproduce yet, but it sounds like you're seeing that error roughly after 7 days? And to confirm, the fix is to reconnect your account, then you tend to see the error again roughly 7 days later?

Can you let me know which scopes you've enabled for the auth connection in Pipedream?

Your assumption is correct, that we should be handling the refresh logic for you automatically and that you should not have to sign back in the do anything, so let's get this fixed.

**Comment by dannyroosevelt** [comment]
Sorry, another question -- when you notice the source hasn't been running and you go look at the source logs, you said the auth provision listed in /accounts is green and not red?

**Comment by GustavoHenriqueFerreira** [comment]
> Sorry, another question -- when you notice the source hasn't been running and you go look at the source logs, you said the auth provision listed in /accounts is green and not red?

Hello @dannyroosevelt I'm working with @ze-finky on the case. Basically we're using a ready-made template with a Gmail connection in Pipefy, we don't define specific scopes, we just connect the account. 

Also, we are thinking that it could be an authentication error with the token expiring, but in this case the error occurs every 7 days and not every 60 minutes. Other than that the error that is giving is the 400 and not the 401 of authorization. 

Do you have any idea what it could be? we are thinking of creating a request with code and adding the scopes manually to see if it is resolved.

<img width="760" alt="Sem título" src="https://user-images.githubusercontent.com/82419986/222162022-e563770d-f13e-4076-a4b8-93916f5b6334.png">

![image](https://user-images.githubusercontent.com/82419986/222162881-a9a7d757-2c6e-4e89-a85f-33d58496c828.png)

![image](https://user-images.githubusercontent.com/82419986/222163180-b90541ef-8cbd-4c03-a7b2-c1cfb8acb9a3.png)

**Comment by ze-finky** [comment]
Hi @dannyroosevelt , as @GustavoHenriqueFerreira confirmed, it disconnects every 7 days. The scope is the one from Pipedream tutorial: https://mail.google.com/. Just that.

**Comment by ze-finky** [comment]
Thanks, @dannyroosevelt

**Comment by malexanderlim** [comment]
Hi @ze-finky , can you follow the instructions [here](https://pipedream.com/apps/gmail-custom-oauth#:~:text=integrated%20into%20Pipedream!-,Publish%20your%20custom%20Gmail%20app,-Google%20has%20a) to publish your application; this has been the source of the issue and your credentials should persist once published.
