### ISSUE TITLE
[IMPROVEMENT] Shopify - add metafields prop to Update Product & Update Customer actions

### ISSUE THREAD

**Issue by michelle0927** [PipedreamHQ/pipedream#5521]
Add the ability to update a product's, product variant's, or customer's metafields.
Product - https://shopify.dev/docs/api/admin-rest/2023-01/resources/product#put-products-product-id
Customer - https://shopify.dev/docs/api/admin-rest/2023-01/resources/customer#put-customers-customer-id
Product Variant - https://shopify.dev/docs/api/admin-rest/2023-01/resources/product-variant#put-variants-variant-id

See [Slack conversation](https://pipedream-users.slack.com/archives/CPTJYRY5A/p1676761636892709) and [previous PR](https://github.com/PipedreamHQ/pipedream/pull/5475) for reference.

**Comment by zecul** [comment]
Thanks Michelle. 

Will we be able to:
1. update/create metafield data where none previously existed (replace empty with a value)?
2. update metafield data where the new value is empty (replace empty/value with empty)?
3. send multiple format metafields to API in one call (string, integer, JSON object, whatever list.metafields are made of etc)?

Other things in the Update Product I'd love to be able access:
1. Update a Product's SEO Title and Description 
![image](https://user-images.githubusercontent.com/123815443/219979664-78948e9b-832f-4477-b012-b8e460d3e9fb.png)

I see thinks like pricing are in the Product Variant rather than Product itself so I'll make another post for any ideas I have about that.

I don't have much experience (zero) working with updating customers so I don't feel I have much to offer there at the moment.

**Comment by zecul** [comment]
To clarify metafields are attached to a product only? You can't attach metafields to a product variant?

**Comment by michelle0927** [comment]
> To clarify metafields are attached to a product only? You can't attach metafields to a product variant?

You can attach metafields to product variants. I updated the issue description to include updating the action `update-product-variant`.

I think you could update the metafields of a product variant from the `update-product` action by entering a custom expression for the `variants` prop instead of selecting one of the async options. I'll make sure to test that when I'm working on this to make sure that's possible. I'll also test to make sure your points 1, 2, and 3 above work successfully, and I'll add SEO Title and SEO Description as props. Thanks for your help on this!

**Comment by michelle0927** [comment]
@zecul I created a PR for this issue here https://github.com/PipedreamHQ/pipedream/pull/5531

1. Yes, you can create new metafields or give a value to empty ones. To do that, you want to include key, value, type, and namespace in the metafield object (which can be entered as a string).
`{ “key”: “new”, “value”: “newvalue”: “type”: “single_line_text_field”, “namespace”: “global” } `
If you’re updating a metafield that already has a value, you’ll want to use the metafield id (you can use get-metafields action to find it).
`{ “id”: “1234567”, “value”: “updatedvalue” }`
 
2. Unfortunately, using “” or null for the value doesn’t remove the metafield value or replace it with a blank value, so I created an additional action, Delete Metafield that works for that.

3. Yes, you can update multiple metafields of varying types at the same time. Each metafield will be a separate object in the metafields array.

I also discovered that you CAN update product variant metafields by using the `variants` prop in the Update Product action. Below are examples of what you would enter if it’s a new variant metafield vs. one that’s being updated.

<img width="942" alt="create variant metafield" src="https://user-images.githubusercontent.com/10889229/220208237-71418298-26c4-4317-83ca-ec6d8356dcca.png">

<img width="920" alt="update variant metafield" src="https://user-images.githubusercontent.com/10889229/220208253-83f2918c-150c-4a5c-b68d-650524332dea.png">

**Comment by zecul** [comment]
> 1. If you’re updating a metafield that already has a value, you’ll want to use the metafield id (you can use get-metafields action to find it).

I've been using the "create metafield" to overwrite old values and create new ones where needed. I have a large inventory created over a number of years where some has no data entered and some has bad data entered. "Create metafield" has been able to add and overwrite so I've been using that rather than update. Update was unable to add data where none previously existed. I imagine update is a good method if you don't want to accidentally write data where none previously existed.
Hopefully update product will still allow create metafield to both write to empty and over-write bad data.

**Comment by michelle0927** [comment]
> > 1. If you’re updating a metafield that already has a value, you’ll want to use the metafield id (you can use get-metafields action to find it).
> 
> I've been using the "create metafield" to overwrite old values and create new ones where needed. I have a large inventory created over a number of years where some has no data entered and some has bad data entered. "Create metafield" has been able to add and overwrite so I've been using that rather than update. Update was unable to add data where none previously existed. I imagine update is a good method if you don't want to accidentally write data where none previously existed. Hopefully update product will still allow create metafield to both write to empty and over-write bad data.

I made an update that allows metafields to be updated using the `id` and `value` OR using `key`, `value`, `type`, and `namespace` just like you would when creating a new metafield. If the `key` already exists, it'll find the id and insert it.

@zecul Are you able to test this before it's published using the [Pipedream CLI](https://pipedream.com/docs/cli/reference/#pd-publish) to see if it works for you or if you have any additional comments?

**Comment by zecul** [comment]
> @zecul Are you able to test this before it's published using the [Pipedream CLI]

I've never tried but I can give it a go. The only thing I've done with CLI related things is gitpod. Let me see what I can work out.
