### ISSUE TITLE
[BUG] Pagination bug on integration explorer at pipedream.com

### ISSUE THREAD

**Issue by rpggio** [PipedreamHQ/pipedream#5548]
**Describe the bug**
Blank results when searching integrations. Explore UI needs to reset pagination when search is applied.

**To Reproduce**
1. Go to pipedream.com
2. Scroll down to Explore at bottom of page
3. Paginate forward a couple of times
4. Search for 'email'
5. See empty results, even though email integrations do exist. No pagination buttons either, so can't reset pagination manually.

**Expected behavior**
See the search results

**Comment by vunguyenhung** [comment]
Hello @rpggio, you mean this Explore all apps section right?
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/18277920/220959707-36c0fd40-4ddd-4b6a-b51a-f0e342f801e6.png">

Maybe this behavior is because the search bar only search for the current page. 

Hello @dannyroosevelt, would you advice if this is what we should improve on the Pipedream explore page?

**Comment by rpggio** [comment]
Leo, the same function is also on bottom of home page, as described in the
STR

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
