### ISSUE TITLE
ERPNext to Google Contacts

### ISSUE THREAD

**Issue by charleslcso** [PipedreamHQ/pipedream#5625]
ERPNext to Google Contacts

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Just come across Pipedream.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
We would like to have true "sync" between ERPNext and Google Contacts for each system user. I'm exploring if I can use webhook in ERPNext to talk to Pipedream, and have Pipedream CRUD Google Contacts.

If anyone can help and advise, it will be very very much appreciated.

**Comment by sergioeliot2039** [comment]
Hi there @charleslcso thanks for the request and welcome to Pipedream!

So, ERPNext is an app already integrated: https://pipedream.com/apps/erpnext

Regarding the system user trigger, are you interested in developing this trigger yourself? If so I recommend getting started here: https://pipedream.com/docs/components/quickstart/nodejs/sources/#emit-items-in-an-rss-feed 

As a head ups I see webhook sare available: https://frappeframework.com/docs/v14/user/en/guides/integration/webhooks but this appear to be supported for documents only (see the DocType reference in the previous URL), so it is likely the trigger needs to be API-polled based 

Finally, as of Google Contacts, this app is not authorized by Google yet, we are tracking that on ticket https://github.com/PipedreamHQ/pipedream/issues/3226

Maybe 
1) you can use the existing Google Contacts component's code base and reuse some of it by including it in your workflow code. This is found in Pipedream's Github repository:
https://github.com/PipedreamHQ/pipedream/tree/master/components/google_contacts/actions
![image](https://user-images.githubusercontent.com/25184117/223135821-32702236-26f7-451b-8618-a42e6c0894c2.png)

2. as you can see on the screenshot from issue 3226, the app is just not authorized. i am guessing you could click on "advanced", and then on "use it anyway" or so, you'll have to ask Pipedream support to see if they can activate it for you to use it regardless. in this case i'd suggest you to write them to support at pipedream.com or in real time with PD developers on the slack community, see: https://pipedream.com/support/

**Comment by charleslcso** [comment]
Thank you. 

I’m confused. ERPNext is already integrated to pipedream… and system trigger? What actions are missing in this integration?

Google is not authorising pipedream? What take them so long? If I’m to set up the Google consent screen, that means my request won’t be entertained as well?

can you help me by listing out the parts that are missing, and require work before CRUD between ERPNext and Google Contacts?

**Comment by sergioeliot2039** [comment]
@charleslcso , please see my comments bellow

> I’m confused. ERPNext is already integrated to pipedream… and system trigger? What actions are missing in this integration?

for integrated to pipedream I mean that there is an ERPNext app in the App Store
this is the app store: https://pipedream.com/explore
if you search for ERPNExt in the App Store, you'll find ERPNExt, it links you to this page: https://pipedream.com/apps/erpnext

there are no actions created for ERPNext.

you can use the generic Pipedream trigger meachanism to listen for events https://pipedream.com/docs/workflows/steps/triggers/#triggers they trigger by Http/Webhook, Email, schedule based and so on. you have to connect your app to use this mechanism.

we have app based triggers, this need to be developed. for example, there are triggers that react to a New Event in GOogle Calendar. YOu can see about app based triggers here: https://pipedream.com/docs/workflows/steps/triggers/#app-based-triggers
currently, there are no ERPNext app based triggers, they need to be built yet.

> Google is not authorising pipedream? What take them so long? If I’m to set up the Google consent screen, that means my request won’t be entertained as well?
Google has authorized Pipedream many apps already, such as GMail, Google Calendar, Google Drive. It hasn't authorized Google Contacfts yet.

I don't know why it has taken them so long to authorize the PIpedream app for Google Contacts,

I think you can get your requests entertained regardless, you'll just get a warning if you connect your own Google Contact credentials.

> can you help me by listing out the parts that are missing, and require work before CRUD between ERPNext and Google Contacts?

On the ERPNExt
   * Firgure out if you can use Pipedream triggers to connect to ERPNext
   or
   * Get ERPNExt app based triggers built. If you want yo build this app based triggers, here is a guide: https://pipedream.com/docs/components/#developing-components otherwise let me know and I can pass your request to the Pipedream component development team to build them for you.
  
On the Google Contacts side
   * You can create your own code in Pipedream workflows to do the CRUD on Google Contacts. YOu even could reause the code that is here: https://github.com/PipedreamHQ/pipedream/tree/master/components/google_contacts/actions 
   * Wait until Pipedream app for Google Contacts is approved.

HOpe if thelps. Sorry for the confusion, is there you still have more questions feel free to let me know. I remain attentive to your comments

Thanks

**Comment by charleslcso** [comment]
That will be of tremendous help. You know, it is a two-way traffic/sync. I don’t know anything about pipedream, so your team’s help will enable me to select if pipedream can be part of our solution.

Looking forward to working with your team!

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by malexanderlim** [comment]
Hi @charleslcso , I'm happy to announce that Google Contacts has been integrated and verified by Google, and is now live. You should now be able to connect ERPNext to Google Contacts! Please let me know if you run into any issues here.
