### ISSUE TITLE
[OAUTH SCOPE] Freshbook new scope

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5833]
**Which application needs a scope added?**
Freshbook

**What scope(s) need to be added?**

- user:other_income:read
- user:other_income:write
- user:time_entries:read
- user:time_entries:write

**Please provide a link to the relevant API docs for scopes.**

https://www.freshbooks.com/api/other_income

**Comment by acreconsulting** [comment]
First of all, thank you @vunguyenhung for adding this ticket here. I didn't realize a ticket was needed so I didn't raise one. I thought I was just doing something wrong!

But what you've transcribed here is **going to be insufficient**. There are a total of 38 different scopes (see https://www.freshbooks.com/api/scopes) so if you're going to the trouble of adding one more, what happens when the next person asks for a different one? Can you add all of them, or can you allow the user to select, or something else?

Specifically, in my original request, I need **user:other_income:read** and **user:other_income:write**, not just read. I'm also making another workflow that deals with time tracking, so I need **user:time_entries:read** and **user:time_entries:write** also

**Comment by Mitrajitkamble** [comment]
.

**Comment by vunguyenhung** [comment]
THanks @acreconsulting, I've added more scopes as you requested

**Comment by acreconsulting** [comment]
Can I further request adding the scopes `user:expenses:read` and `user:expenses:write` please?
Reference: https://www.freshbooks.com/api/expenses

**Comment by dannyroosevelt** [comment]
@acreconsulting this is done (including the `user:expenses` scopes). You'll have to reconnect your FreshBooks account for the new scopes to take effect.

**Comment by acreconsulting** [comment]
I tried to create a workflow that uses user:time_entries:write and I'm getting an error:
```
Error
Request failed with status code 500

error:
An internal error has occurred.
DETAILS
    at null.createError (/var/task/node_modules/@lambda-v2/component-runtime/node_modules/axios/lib/core/createError.js:16:15)
    at null.settle (/var/task/node_modules/@lambda-v2/component-runtime/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/task/node_modules/@lambda-v2/component-runtime/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at null.endReadableNT (internal/streams/readable.js:1333:12)
    at process.processTicksAndRejections (internal/process/task_queues.js:82:21)
```
It could be because I'm doing something wrong, but I really have no idea what that error message means.
In the same workflow, I successfully authenticated with Freshbooks and was able to GET /time_entries/ but the error I'm receiving is when I try to POST to /time_entries/ while using the same basic structure.

**Comment by dannyroosevelt** [comment]
@acreconsulting can you enable the workflow to share with Pipedream support then paste the workflow URL here so I can check it out?

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt https://pipedream.com/@acreconsulting/testing-time-tracking-integration-p_n1Cz9jl/build it's just the last step that is throwing the error. Feel free to test/modify as needed.

I added a couple steps at the end of your workflow and got the request working. I think there's a formatting issue in the request body in your original POST, but I didn't spend too much time digging in to what is not working, I just added a code step to build the JSON body, then I separately pass that to FreshBooks.
