### ISSUE TITLE
[BUG] Not able to connect to Twitter API

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5975]
Twitter [has announced new access tiers](https://twitter.com/TwitterDev/status/1641222782594990080) for its API
- As a result, the Twitter API is not currently accessible via Pipedream.
- We are actively working to get access to Twitter back up and running asap, and will post updates to this ticket as we make progress.

**Comment by dannyroosevelt** [comment]
We released an updated integration, which re-enables support for Twitter's API, but requires users create and provide credentials for their own OAuth developer app. More info on how to do this here:
https://pipedream.com/apps/twitter#getting-started

**Comment by NebularNerd** [comment]
Can confirm that I can now post Tweets once again, because I'm not paying for the dev keys I cannot test read support. I'm going to hopefully use IFTTT to pick up a certain tweet another app produces then fire it into Pipedream with a webhook 😎

Big thanks to @dannyroosevelt & the team for getting this resolved. 👏🎉
