### ISSUE TITLE
[Components] MindMeister

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#5991]
### App
MindMeister
https://www.mindmeister.com/

Triggers:
1. Map Created: Triggered when a new mind map is created.
2. Node Updated: Triggered when a node in a mind map is updated or changed.

Actions:
1. Create Map: Create a new mind map with a specified title.
2. Add Node: Add a new node to an existing mind map.
3. Update Node: Modify the content or properties of an existing node within a mind map.

_This list of suggested components was generated using ChatGPT_

**Comment by malexanderlim** [comment]
Closing this issue, as we will focus on MeisterTask for now due to lack of functionality of MindMeister API V2.

Documentation for MindMeister API V2 does not seem to have a good way of listing maps in a meaningful way to engage with them compared to V1, and they deprecated a lot of functionality and methods in the latest version.
https://developers.mindmeister.com/reference/maps

See discussion here:
https://community.meister.co/discussion/588/what-are-future-plans-of-extending-api-v2-to-match-or-surpass-functionality-provided-with-api-v1
