### ISSUE TITLE
[BUG] Salesforce event source returns 400 error on creation

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#626]
Salesforce doesn't allow the programmatic creation of Apex trigger objects directly on a production instance. When creating a Salesforce event source on my production instance, I see the following error:

```json
{
      "message": "Can not create Apex Class on an active organization.",
      "errorCode": "ENTITY_IS_LOCKED",
      "fields": []
}
```

**Comment by jverce** [comment]
Some reference links:
* https://trailblazers.salesforce.com/answers?id=9064S000000D5UzQAK
* https://help.salesforce.com/articleView?id=000324396&type=1&mode=1
* https://salesforce.stackexchange.com/questions/255000/issue-while-creating-apex-class-using-api

**Comment by jverce** [comment]
### Progress so far

* The process and requirements for deploying code in Prod organizations is more involved, and requires for example having tests that provide sufficient coverage. Hence, the changes needed for this bug fix are the following:
  * The Apex code that this component was already sending (i.e. classes and trigger)
  * Tests for the trigger
  * Utility classes for to actually run those tests, like mocks and object factories
* Since most of the content is this component resulted to be very specific to the process of deploying code to Salesforce, I extracted everything Apex-related to a separate [NPM package](https://www.npmjs.com/package/salesforce-webhooks). The strongest reason behind this is that trying to tackle this without the use of templates for the mentioned Apex code became impractical.
* The package mentioned above offers a simple interface to create and delete webhooks in Salesforce, and this component will just focus on handling these webhook events, and getting config options from the user.

### Current focus

The biggest problem here is the fact that in order to test the webhook Apex code we need to create, update and/or delete object instances (e.g. an `Account`, a `Lead`, etc.) but every one of those object types has a specific set of required fields which are not provided via any API. There are some independent efforts to provide something useful for this purpose:
1. https://github.com/mbotos/SmartFactory-for-Force.com: I've tried this options with relative success after doing some fixes. I am doing an exhaustive check right now to verify that this works with all SObject types (e.g. currently it fails to create `Lead` objects for example)
2. https://github.com/apexlarson/SObjectFactory: this is another alternative that I haven't tried but could be considered if the option above cannot be amended

**Comment by jverce** [comment]
A couple of fixes have been merged:
1. #670 provides a timer-based, non-invasive alternative to dealing with Salesforce events, that periodically scans the Salesforce org (using the [`getUpdated`](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_getupdated.htm) and [`getDeleted`](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_getdeleted.htm) API's) and emits events for the objects reported by such API call.
2. #671 uses a similar approach to the previous version, but it creates all the necessary Apex code through the [`compileAndTest`](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/sforce_api_calls_compileandtest.htm) API via a deployment. It creates auxiliary classes that make sure the new code is tested. This logic has been moved to a separate NPM package called [`salesforce-webhooks`](https://www.npmjs.com/package/salesforce-webhooks) which holds a static list of the **supported SObject types** (i.e. the list of supported SObject types is not as extensive as the timer-based solution):
  - ["New object" event](https://github.com/jverce/salesforce-webhooks/blob/master/resources/data/sobjects-new.json)
  - ["Updated object" event](https://github.com/jverce/salesforce-webhooks/blob/master/resources/data/sobjects-updated.json)
  - ["Deleted object" event](https://github.com/jverce/salesforce-webhooks/blob/master/resources/data/sobjects-deleted.json)

**Since Salesforce API's and features sometimes depend on the subscription plan of a particular org, these should be tested in a real "production" paid org (especially the 2nd solution)**

**Comment by dylburger** [comment]
Closing this since we've refactored all Salesforce event sources since this was an issue.
