### ISSUE TITLE
[BUG] Update Page does not support Status type

### ISSUE THREAD

**Issue by jasueh** [PipedreamHQ/pipedream#6310]
**Describe the bug**
When updating a page, status type properties are not updated. 

**To Reproduce**
1. Retrieve Page from Notion, page in database must include at least 2 properties  Status of type status and  Updated type Text . Status should be anything but In Progress
2. Update Page component, set id with the retrieved page
3. Set Properties Types:  ["Status", "Updated"]
4. Set Properties Values:  [ {
  "id": "abcc967b-5135-4217-8677-ba840fd8b008",
  "name": "In progress",
  "color": "blue"
}, "Done"]
5. Test it

**Expected behavior**
The page should have the Status and Updated fields updated with the values mentioned in the steps to reproduce. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version: Version 113.0.5672.63 (Official Build) (64-bit)

**Additional context**
From what I understand, the Status type is an object with 3 properties as per notion documentation: https://developers.notion.com/reference/page-property-values#status

reviewing the source code of the update_page component, led me to the notion page properties common resource: 
https://github.com/PipedreamHQ/pipedream/blob/master/components/notion/common/notion-page-properties.mjs

And it seems that status is not included in the integration.

**Comment by lcaresia** [comment]
Isn't possible to update `stats` type field by API, only from Notion UI.
One solution is change the `Status` field to type `select`

![image](https://github.com/PipedreamHQ/pipedream/assets/12402324/97e50357-008a-4124-95c1-3c259e6c5c57)

https://developers.notion.com/reference/property-object#status

**Comment by jasueh** [comment]
Ahh that explains it...

**Comment by dharrison27** [comment]
Hello @lcaresia , I think this issue was closed because the API limitation text was misunderstood.

The API warning text is specifically telling you what its limitations are:

- You cannot change the `Status` name label, (1) 'Project Phase' in my example.
- You cannot update the `Status` options are, (2) 'do NOW' or 'Meh' in my example

What you **can** do, which is not specifically outlined in the warning:

- You can change what the (2) `Status` is from the list of options that already exist, 'Meh' in our example below.

![image](https://github.com/PipedreamHQ/pipedream/assets/6942985/fb5589ad-189b-4e70-8de8-6baeae556ea3)

Could somebody please consider reopening this and taking another look, please?
