### ISSUE TITLE
[APP] Microsoft SQL Server

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#6408]
Customer request: https://pipe-dream.slack.com/archives/C054V4ZD6BG/p1683761955929139?thread_ts=1683761891.851409&cid=C054V4ZD6BG

**Name of app / service**
Microsoft SQL Server

**Link to developer documentation**
https://learn.microsoft.com/en-us/sql/reporting-services/developer/rest-api?view=sql-server-ver16

**Comment by sergio-eliot-rodriguez** [comment]
@malexanderlim i need some input please.

First off. The app name shown in the GitHub issue is Microsoft SQL Server, this is different than the rest api documentation you are linking. You are linking to MS SQL Server Reporting Services, which is a part of the entire Microsoft SQL Server services, but is not the main database querying related product. Consider the following installations part from MS:

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/a73bf5b6-75b4-493f-965b-6dce37c2560d)


Usually, if a user Microsoft SQL Server, it usually means accessing the database engine to perform queries with TSQL. 

Can you please check which product the user is referring on that Slack space? I think that's a private Pipedream space I don't have access to (I-m on Pipedream-users).

Second. In the case the requirement is to provide a way for PD user to access connec to MS SQL Server instance to query tables, rows and so on, for cases like this we usually use a node.js SDK, this is wat we did for MySQL and for Postgres:

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/b3e3da04-d9e3-4c25-9b44-3449ba32ac67)

![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/ae6df80f-1da9-4a5f-ac8d-006a368d2b8f)


Are you ok to create a similar app integration for MS Sql Server like we did for these other database engines?
I-m asking because the submit an app for does not allow to easily setup SDK code, or does it now with the submit ui?i could prepare a pd workflow using the sdk and once the app would have to be modified after i submit it, when it is being tested and validated.

This is the node.js library for MS SQL Server I found:
If found this on NPM: https://www.npmjs.com/package/mssql
that's what the used if you start here: https://learn.microsoft.com/en-us/sql/?view=sql-server-ver16
and go to Development > [Build an app using SQL Server](https://www.microsoft.com/en-us/sql-server/developer-get-started/)
then go to Nodejs > macOS > Create Node.js application with SQL server
https://www.microsoft.com/en-us/sql-server/developer-get-started/node/mac/step/2.html
Step 2.1 Javacscript
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/cc53d93d-d682-4d09-bce7-9f154cdd9371)


do you want that i go ahead and use this tedious SDK? It's the same that the one I found on NPM.
or keep with Reporting Services?

**Comment by malexanderlim** [comment]
Let me clarify with the customer and get back to you here. Thanks!

**Comment by sergio-eliot-rodriguez** [comment]
> Customer request: https://pipe-dream.slack.com/archives/C054V4ZD6BG/p1683761955929139?thread_ts=1683761891.851409&cid=C054V4ZD6BG
> 
> **Name of app / service** Microsoft SQL Server
> 
> **Link to developer documentation** https://learn.microsoft.com/en-us/sql/reporting-services/developer/rest-api?view=sql-server-ver16

did they clarify on this?
btw i can't access that Slack thread where the customer made the request.
