### ISSUE TITLE
[APP] JOOR

### ISSUE THREAD

**Issue by NathanScheele** [PipedreamHQ/pipedream#6826]
**Name of app / service** JOOR
https://www.joor.com/

**Link to developer documentation** https://api-docs.jooraccess.com/

**Comment by sergio-eliot-rodriguez** [comment]
oauth password grant

requested api access via their integrations email, copied sergio at pk, integrations at pd

**Comment by sergio-eliot-rodriguez** [comment]
hi @NathanScheele 

Shawn from the Joor team reached back from my request. He lmk that they provided to you API credentials:

> Hi Sergio,
> 
> I have provided Nathan Scheele with the API credentials and API documentation. If additional details are needed, can you please have Nathan loop you into our existing conversation?
> 
> Thank you,
> 
> Shawn
> 

wondering if you-d be willing to share API Credentials, so that I can develop a Bring your own kind of OAuth authentication method? Looks like we are not getting an OAuth for Pipedream. if you agree, please send them to sergio at pipekit dot pro
