### ISSUE TITLE
[BUG] Twitter Upload Media always throw authentication error

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6876]
**Describe the bug**
When using Twitter Upload Media action, it always throws error, even when the API is available for Free user
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/446253cb-7a6b-4976-aade-5e72ec408192)

**Expected behavior**
The action should be executed successfully, the media should be uploaded to twitter

**Comment by GTFalcao** [comment]
To complement the original issue title, there were a few issues in this action that have been fixed in the submitted pull request:
- the request URL was wrong (mixing the v1 endpoint with the v2 base URL);
- the Content-Type was not properly identifying the request (as `application/x-www-form-urlencoded`, but it has been adjusted to use `multipart/form-data` instead);
- sending the image encoded as base64 often resulted in a 431 response (request header fields too large), so it was changed to send binary data instead;
- the authentication process was not ignoring the body when generating the OAuth signature, which the Twitter API recommends doing.
