### ISSUE TITLE
[Components] Google My Business

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#6979]
**Is there a specific app this action is for?**
Google My Business

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.google.com/my-business/ref_overview

**Triggers**
- New Review
- New Post

**Actions:**
- List Post
- Create Post
- Create Reply to Review
- Update Reply to Review

**Comment by NebularNerd** [comment]
Looking forward to this, waiting with anticipation 🙂

**Comment by GTFalcao** [comment]
@malexanderlim is this already integrated as an app?

**Comment by GTFalcao** [comment]
Components are finished, but we'll need to wait for some pending authentication requirements which need to be approved by Google - blocking this for now and it will be resumed when that response is received.

**Comment by NebularNerd** [comment]
Looks good, very excited to see this reach completion. I know IFTTT has GMB issues with more complex strings, I can make test posts but anything that uses their filters to build a post fails. I suspect the .json issue may also be what affects their app.

**Comment by GTFalcao** [comment]
@vunguyenhung I'll adjust the object prop you mentioned. Are we expecting to always check for a string value and attempt to parse it as a JSON, for any object prop? If so, we should think about doing this on a global scale, rather than per-component or per-prop scale, as most props that evaluate to `object` will always expect an object and not a string.

**Comment by NebularNerd** [comment]
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/db42e35e-eb07-4396-add2-aaf9cb13c02d)
