### ISSUE TITLE
Web scraping

### ISSUE THREAD

**Issue by vaibhav-1208** [PipedreamHQ/pipedream#715]
Can anyone help me to do web scraping of this site: https://www.agtta.co.in/individuals.php
I want to scrap all the information of individuals present on the site. Please help me its my final project.

**Comment by dylburger** [comment]
Hi @vaibhav-1208 , we are happy to help answer specific questions about Pipedream functionality, but since this isn't a request for a new feature or app integration, I'm closing this. 

Feel free to take a look at [this blog post on using Cheerio to scrape a site with Pipedream](https://medium.com/@dylan.sather/scrape-a-site-with-node-and-cheerio-in-5-minutes-4617daee3384).
