### ISSUE TITLE
[FEATURE] Idempotence for `pd publish` (allow identical re-publish)

### ISSUE THREAD

**Issue by mroy-seedbox** [PipedreamHQ/pipedream#7271]
**Is your feature request related to a problem? Please describe.**
An important concept in CI/CD is idempotence: that an identical operation may be repeated an infinite number of time, always with the exact same result.

Unfortunately, that is not the case with `pd publish`: if we publish the exact same component twice in a row (with the same version), the first time will work, but the second time will return `component create api call responded with status: 409, body: {"error":"already published"}`, which is detected as an error (i.e. someone forgot to increment the version). Effectively, there's no simple way to differentiate between someone who indeed forgot to increment the version (with code changes), or if it's simply an attempt to publish the latest version again (without changes).

**Describe the solution you'd like**
It should be possible to compute a checksum of the component, and if the checksum is the same as the published version, then simply accept the request and respond with `no change` (HTTP status `304 Not Modified` might be appropriate here).

**Do you have a workaround?**
We might be able to track the versions & checksum outside of Pipedream (to make sure a CI/CD pipeline never publishes the same version again), but this is not something that should be implemented on the customer-side.

**Comment by dylburger** [comment]
@mroy-seedbox I talked to the team about this one. For now we're keeping the behavior the same since it mimics npm (which throws a 403 in this case). We want to complain loudly since it normally signals an unexpected state, e.g. the user didn't correctly version the component). You should also be able to maintain idempotency within your CI/CD env by wrapping the logic with a Bash script and handling this case accordingly:

```bash
#!/bin/bash

pd publish component.mjs

if [ $? -eq 0 ]
then
  echo "Successfully published package"
else
  echo "Failed to publish package. Package may already exist with this version"
fi
```

You can also check out [our publication script](https://github.com/PipedreamHQ/pipedream/blob/master/.github/workflows/publish-components.yaml) for global registry components — we only process changed files, and additionally run [a check](https://github.com/PipedreamHQ/pipedream/tree/master/.github/actions/git-diff-on-components) to ensure the version of all components that were touched also had their version modified.

Let me know if that helps.

**Comment by mroy-seedbox** [comment]
Ok, we'll make it work that way as well! 👍 

Thank you. 🙏
