### ISSUE TITLE
[BUG] Undefined environment variables

### ISSUE THREAD

**Issue by spaquettepare** [PipedreamHQ/pipedream#7305]
**Describe the bug**
Every environment variables return `undefined` in Node scripts even when defined in the settings.

**To Reproduce**
1. Create an environment variable (or use existing)
2. Create a Node step in a workflow (new or not)
3. Write `console.log(process.env.NAME_OF_THE_VARIABLE);`
4. Test step 
5. See the `undefined` value in the logs tab of the Results section 

**Expected behavior**
Environment variables should always be available when accessed from `process.env`.

**Screenshots**
We can see that when accessed from the props, the environment variable exist and return the actual value instead of `undefined`.
![image](https://github.com/PipedreamHQ/pipedream/assets/122302935/35f75d66-4f7c-457c-80db-763a9aaa130b)

When the `process.env` variable is logged, there are only 2 variables from Pipedream defined.
![Screen Shot 2023-07-19 at 3 01 23 PM](https://github.com/PipedreamHQ/pipedream/assets/122302935/511ce6ea-fb06-4b06-b99e-61774d8189f1)

**Desktop:**
 - OS: MacOS Ventura
 - Browser: Chrome 114.0.5735.198 (Official Build) (x86_64)

**Additional context**
- Updating existing variables or creating new variables does not fix the problem
- Logging out and back again does not fix the problem

**Comment by spaquettepare** [comment]
Sorry, the steps were a misleading. I initially tested on my side by duplicating the faulty Node step and modifying it. I checked further and found out that the behaviour happens when I try to define an action.

This trigger the behaviour (not having access to the environment variables)
```javascript
export default defineComponent({
  name: 'Talend execute plan',
  version: '0.1.1',
  key: 'talend-execute-plan',
  type: 'action',
  async run({ steps, $ }) {
    console.log(process.env.TALEND_API_KEY);
  },
});
```

While this does not
```javascript
export default defineComponent({
  async run({ steps, $ }) {
    console.log(process.env.TALEND_API_KEY);
  },
});
```

**Comment by dylburger** [comment]
@spaquettepare This is by design. Actions explicitly don't have access to the environment for usability (you can't guarantee a user will have a specific env variable populated) and security reasons (so that an action author cannot exfiltrate env vars) — [see the docs](https://pipedream.com/docs/components/api/#environment-variables) for more detail. I realize that for private actions, these are less of a concern, and we've discussed improving the whole shared, private code model to make this easier. 

For now, you should define props for the input you'd like to receive and pass `{{process.env. TALEND_API_KEY}}` in the input of the step. It looks like our [Talend integration](#7265) is also in progress, so feel free to follow that issue for updates — then it should be easier to connect an account instead of needing to pass the var.

Let me know if that helps!
