### ISSUE TITLE
[FEATURE] Linear New Issue Status Updated (Instant) source: make Team ID prop optional

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7383]
**Is your feature request related to a problem? Please describe.**
Currently user only can create Linear New Issue Status Updated (Instant) source for a single team. In some cases user need the trigger for all teams

**Describe the solution you'd like**
Linear New Issue Status Updated (Instant) source: make Team ID prop optional. The source will emit events **for all teams** if `Team ID` is not set

**Do you have a workaround?**
Create a new trigger for each team

**Additional context**
Requested by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1690359708066979

**Comment by Acren** [comment]
This would be very useful!

An example use case is that we want to know when any issue moves to Done status (or a custom status) regardless of the team.

If this is done it's possible it may need an option to filter the status by name as well, since it looks like the existing filter might be based on status ID which is tied to a single team.
