### ISSUE TITLE
[Components] Zoho People

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#7419]
### App
Zoho People
https://www.zoho.com/people/

**Actions:**
1. Add record 
https://www.zoho.com/people/api/insert-records.html
2. Update record
https://www.zoho.com/people/api/update-records.html
3. Get an attendance entry
https://www.zoho.com/people/api/attendance-shift-details.html
4. Create an attendance entry
https://www.zoho.com/people/api/attendance-checkin-checkout.html

**Comment by vellames** [comment]
@vunguyenhung I fixed the bugs and added `empId` as an async option.
About the update record:
I had to remove the `autofill/default values` because some fields are `read only` and if you fill it, Zoho will return an error message. Unfortunately, via API, I didn't find a way to check if a field is read-only or not.
