### ISSUE TITLE
[FEATURE] Descriptions / notes for steps

### ISSUE THREAD

**Issue by sdotsamuel790** [PipedreamHQ/pipedream#7471]
**Is your feature request related to a problem? Please describe.**
It's not a problem. As I am writing my workflow, I would like to add NOTES to the step. When I revisit the workflow, it takes time to recall what I did and why I did it.

**Describe the solution you'd like**
Each step should have a field called STEP NOTES.

**Do you have a workaround?**
I can work without it.

**Comparable features in other tools?**
I have not seen this with other NO CODE tools.

**Additional context**
N/A

**Comment by mroy-seedbox** [comment]
Zapier added that feature recently ([documented here](https://help.zapier.com/hc/en-us/articles/16791272000525#add-a-note-to-your-zap--0-0)):

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/efb1bc99-3aea-4d2f-9d9d-69a6269e5173)

**Comment by osseonews** [comment]
Yes, please add this. It would be super helpful, otherwise things get too difficult to manage per the comments in the first post here.  You should also allow for a Single Note for the entire workflow. That would actually be a good start and maybe easier to implement quickly on your end. But, having a Note for each step, as described above, would also be amazing.

**Comment by Swieter** [comment]
+1

**Comment by mroy-seedbox** [comment]
Looks like this has been implemented! 😮 🎉 

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/e124ee00-8b16-4ac6-a2a1-382fd4b2a03c)

![image](https://github.com/PipedreamHQ/pipedream/assets/66686238/599cf1d0-ac32-47c9-807d-6bc38e068dcd)

**Comment by dannyroosevelt** [comment]
It sure has! Docs and public announcement coming asap 😄

**Comment by dannyroosevelt** [comment]
Btw markdown is supported there as well 😉

**Comment by dannyroosevelt** [comment]
Here are docs for step notes, which are live for everyone now!
https://pipedream.com/docs/workflows/steps/#step-notes

**Comment by osseonews** [comment]
Thanks for adding this, but why is this closed? you added notes for the steps but not for the actual workflow? Can you please add a note feature for the workflow itself? That is actually the more important feature and easier, I would assume, to implement.

**Comment by mroy-seedbox** [comment]
Notes on triggers could indeed be useful, especially since workflows can have multiple triggers (might be good to explain the purpose of each one).

**Comment by dylburger** [comment]
@osseonews this was closed because the original ask was for step notes, which was implemented. We've tried to implement better GitHub issue grooming on our side to track highly-specific issues, otherwise we ship new features and are still tracking subset of asks on the original issue, which is incredibly hard to track / maintain on our side.

I've opened these two issues to track these two additional features:

* https://github.com/PipedreamHQ/pipedream/issues/8746
* https://github.com/PipedreamHQ/pipedream/issues/8747
