### ISSUE TITLE
[APP] Contentful

### ISSUE THREAD

**Issue by rawkode** [PipedreamHQ/pipedream#751]
**Name of app / service**

Contentful

**Link to developer documentation**

https://www.contentful.com/developers/

**Is lack of support preventing you from building workflows, or do you have a workaround?**

No, I can use an API key stored in env for the time being

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

Authentication storage is mostly what I am after

**Comment by todsac** [comment]
I have the first version of the integration done.  Here is an example - https://pipedream.com/@tod/p_NMC9jlo

Contentful has five APIs so please let me know what is the priority for you.  I started with the Content Management API.

**Comment by rawkode** [comment]
Thanks!

The other two APIs I'd like integrated are, in this order:

- https://www.contentful.com/developers/docs/references/content-management-api/
- https://www.contentful.com/developers/docs/references/graphql/

**Comment by todsac** [comment]
The content management API is working.  Would you be open to testing the Graph QL api?  Contentful says, "Disclaimer: GraphQL Content API is available on all spaces for customers on current pricing plan" and we don't have a paid account.  I am unclear if I am blocked because of my account or there is something unique about the required GraphQL access token.

Here is a workflow to clone and test:
https://pipedream.com/@tod/contentful-api-integration-examples-p_8rCNkzg
