### ISSUE TITLE
[IMPROVEMENT] Docusign - Create a Signature Request: Allow adding multiple recipients per the number of recipient on the template

### ISSUE THREAD

**Issue by sofian-saoudi** [PipedreamHQ/pipedream#7984]
The current DocuSign 'create a signature request' action only allows to map to 1 recipient.

this means that if the template that we want to use to create a document contains two recipients or more, we can't use Pipedream

In Power Automate, it is possible to map as many recipients as there are in the templates.

**Comment by MichaelNey** [comment]
@sofian-saoudi @vunguyenhung 

I'm curious about your opinions on the best UX for this. I just played with this for a bit and was able to get a version working where it would automatically show a name and email input for every role, but it doesn't seem like the most scalable option since I am not able to use a predefined object, or an array of objects to represent those inputs, so each one was it's own input.

One on hand, something like Power Automate has a very granular action for steps like adding a single recipient to an existing envelop, creating an envelop, sending the envelop, etc. On the other, that may be a more complicated user experience compared to a single action that could simply ask for the email/name of each defined role in the Docusign template. Perhaps it may be worth thinking about having more granular actions for the Docusign app, while also enhancing this specific action but making it clear that it is best used for sending an envelop to recipients of an already pre-configured template (Tags already mapped to roles, roles defined, content, etc already all done on Docusign end).

Either way, here is an example of what I could make a PR for right now that works, but may not be the 100% best user experience. I still think having more granular options that could replace this action for those who want a more complex workflow would be the best of both worlds so both basic and advanced use cases can be supported by the platform.

The text highlighted in yellow is dynamic based on the roles pre-configured in your Docusign template.
![image](https://github.com/PipedreamHQ/pipedream/assets/25756024/b084ce26-9bec-4b6c-9e8c-3432f2675ef0)
Docusign role configuration
![image](https://github.com/PipedreamHQ/pipedream/assets/25756024/aa2711ac-d6e7-4185-94f8-d159733fa8e6)

As you can see, I configured my roles, tags mapped to roles, and content all in my template within Docusign before going to Pipedream and using this action to simply say who my recipients for each role were. My only worry is what if someone has a lot of roles for one envelop, like 10. Then there would be 20 inputs (1 for email, 1 for name for each role).

Let me know your thoughts!

**Comment by sofian-saoudi** [comment]
I think this is fantastic, Michael! I wouldn't bother trying to make it
perfect, but here's how you could:

A multi select field (checkbox would be ideal) showing all the recipient
roles available in the template.

Then, based on the recipients selected above, recipient name, email and
data fields would show up so that the user can fill out.

I don't think your worry is something you should worry about. If somebody
has 10 recipients (which is VERY RARE) most have 2 or 3, then your tool is
saving them so much time that they shouldn't complain about having to
mapping 100 fields once!

Let me know if I can help further, I'm impressed by how responsive you were
with this,


Sofian Saoudi

Founder

**Comment by sofian-saoudi** [comment]
Just to confirm, it's not just the name and email field that we're after.
It's also the data fields (text fields, dropdown fields, radio, etc) that
need to be mapped and therefore show up for ALL recipients.

Sofian Saoudi

Founder

**Comment by MichaelNey** [comment]
Here is current functionality with some tabs. For example, I made a dropdown for one recipient, and a checkbox for the other. The action automatically displays these with the configured data label (from Docusign) and the options/values configured in the template you can change before creating the signature request/draft. Is this image below kind of what you are looking for?

![image](https://github.com/PipedreamHQ/pipedream/assets/25756024/143c63e6-43ff-4341-a010-94f9a7155ef7)

**Comment by sofian-saoudi** [comment]
Sorry Michael,

I’m not sure I’m understanding your question,

Can I test this myself?

Or maybe we can do a slack huddle?

Sofian SAOUDI

100% Typo Guarantee:
This email was sent from my iPhone

**Comment by MichaelNey** [comment]
Sorry, I just meant being able to see the custom data inputs you setup in your Docusign template and change their values in the Pipedream action like in that image is ideal correct?

You can test it yourself if you can get the code locally from my pull request, but otherwise the Pipedream team would have to merge my changes.

It is about 3am here now I will be offline for a bit, but otherwise I'd be open to a huddle to learn more about your use case to see if this would cover your bases.

But with my current draft PR it now has functionality for:
- Seeing and setting the value for all Tabs/data values configured on your selected Docusign template
- Setting the name/email for every single Recipient configured on your selected Docusign template

**Comment by malexanderlim** [comment]
Hi @sofian-saoudi , have you had a chance to test this PR? @MichaelNey , if your code is ready for review, let me know and I can have the team review!

**Comment by MichaelNey** [comment]
It looks like this PR was merge a while ago already.

**Comment by malexanderlim** [comment]
Sorry about that - I must have missed that. I will close out this issue given that this has been merged. Thank you for your contribution!
