### ISSUE TITLE
[ACTION] - Lob - Send Letter action

### ISSUE THREAD

**Issue by dschnurbusch** [PipedreamHQ/pipedream#8408]
**Is there a specific app this action is for?**: Lob.com

**Please provide a link to the relevant API docs for the specific service / operation.**: https://docs.lob.com/#tag/Letters

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by sergio-eliot-rodriguez** [comment]
Hi @dschnurbusch 

Thanks for the request.

Dylan's message is automated. So feel free to follow along if you'd like to contribute to the [Pipedream registry,](https://pipedream.com/docs/apps/contributing/) otherwise please just wait and the component development team will get to your request and build the action.

**Comment by malexanderlim** [comment]
Hi @dschnurbusch , tracking development here - I will close this ticket for now.
https://github.com/PipedreamHQ/pipedream/issues/8614

Please follow along the new ticket for status updates. Thanks!
