### ISSUE TITLE
[FEATURE] Create, update, and delete workflows via API

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#8735]
I need to programmatically create, update, and delete workflows via API. 

This feature was previously tracked at #220, and we're breaking it out into separate tickets for tracking.

**Comment by mroy-seedbox** [comment]
For this feature, workflows should support external identifiers, so that we can keep referencing them externally without storing the internal ID created for each workflow by Pipedream.

For example, let's say I have the configuration for these two workflows:
```js
workflow_a = { ... };
workflow_b = { ... };
```

I should be able to use the API to create these two workflows, and then keep referencing them as `workflow_a` and `workflow_b` for other API operations (future updates, deletes, etc.), rather than than referencing them using the Pipedream internal ID (e.g. `p_YyCD1a7`), which would need to be stored somewhere on the client side.

It's possible to work with an API without this feature, but it would require an additional layer of conditional logic everywhere (does the workflow exist already? use `POST` or `PUT`? etc.).

An external identifier would enable the idempotent use of `PUT` for creation or updates.

At the very minimum, we would at least need the option to retrieve workflows by name (if the above is not an option). That way, we can use the workflow name as a kind of external identifier (not quite the same, but it can work).

Worst case scenario, we would have to retrieve the full list of workflows all of the time, and filter it afterwards in order to find a specific workflow.

**Comment by ctrlaltdylan** [comment]
We have released the ability to programmatically create and update workflows by REST API.

Read this end to end guide on how to create workflows programmatically using the REST API: https://pipedream.com/docs/rest-api/workflows

API Documentation: https://pipedream.com/docs/rest-api#workflows
