### ISSUE TITLE
[Components] sms-alert

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8854]
# sms_alert
## URLs
- https://kb.smsalert.co.in/developers-api/
#### Prompt
Creates a new contact within a specified group. 
#### Prompt
Sends a text message directly. 
#### Prompt
Schedules a text message to be sent at a specified time.

**Comment by GTFalcao** [comment]
@vunguyenhung I applied the fixes/improvements.

Sender ID is the prop that is only available to premium accounts, and it is not optional, which is what makes these two actions incomplete. Since the response schema is not documented, the code would likely have to be adjusted after we were able to test the request with a premium account.
