### ISSUE TITLE
[Components] ewebinar

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8865]
# ewebinar
## URLs
https://ewebinar.stoplight.io/
#### Prompt
Emits new event when a registrant submits a completed registration form. 
#### URLs
- https://ewebinar.stoplight.io/docs/ewebinar-developer-rest-api-documentation/a51221bce560b-get-registrant-sessions-across-webinars
#### Prompt
Emits new event when an attendee visits a conversion pixel positioned page, typically post a purchase. 
#### URLs
- https://ewebinar.stoplight.io/docs/ewebinar-developer-rest-api-documentation/207a6e0b9b1d1-register-for-session
#### Prompt
Emits new event immediately after a registrant joins a webinar session or starts a replay.
#### URLs
- https://ewebinar.stoplight.io/docs/ewebinar-developer-rest-api-documentation/a51221bce560b-get-registrant-sessions-across-webinars
#### Prompt
Registers a new attendee for a specific eWebinar event. 
#### URLs
- https://ewebinar.stoplight.io/docs/ewebinar-developer-rest-api-documentation/207a6e0b9b1d1-register-for-session

**Comment by luancazarine** [comment]
HI @vunguyenhung 

 - The Attendee Converted source is not possible to develop because once the registrant is converted, it disappears from the list, making it impossible to access the converted records.

 - The Create Registrant action was not possible to develop because it has returned an error about a field that does not exist in the documentation. I contacted the company via chat, and they responded that some things may not behave as expected because it is an API in the testing phase.
