### ISSUE TITLE
[APP] Learnworlds

### ISSUE THREAD

**Issue by henrywangnl** [PipedreamHQ/pipedream#9187]
**Name of app / service**
Learnworlds

**Link to developer documentation**
https://learnworlds.dev/docs/api/72b66de24898e-welcome-to-the-new-learn-worlds-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**
Would like to use a built-in auth for me to call Learnworlds APIs

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
mainly Auth comonents

**Comment by sergio-eliot-rodriguez** [comment]
Hi @henrywangnl 

Thanks for the request.

We have requested API access to LearnWorlds so that we can get started to build the integration. However, if you can reach out to your LearnWorlds CSM, or LearnWorlds support, tell them you are interested in an integration with Pipedream that would be helpful. When app developers hear from their users wanting to integrate, that can help to expedite granting us access for the development.

**Comment by henrywangnl** [comment]
Hi @sergio-eliot-rodriguez ,

Thanks for the update.
I just requested it from the Learnworlds platform via a support ticket. Hope it helps!

Btw, if we can get the Auth part done that'll be a great help already!
Looking forward to it!
