### ISSUE TITLE
[SOURCE] Facebook

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#925]
**Describe the event source. What app, what event?**
Retrieve leads from FB Lead Ads

**Please provide a link to the relevant API docs for the specific service / operation this trigger is tied to.**
https://developers.facebook.com/docs/permissions/reference/leads_retrieval

**Comment by todsac** [comment]
+1 to Facebook lead ads

**Comment by dannyroosevelt** [comment]
Another +1 from a customer in Slack

**Comment by drakeballew** [comment]
Hey y'all, just want to add some color here. I'm a customer - very limited dev experience but can sling a few lines of spaghetti every now and then. I'm a Pipedream free tier customer and love the product, but for me, I was/am working on validating an idea and needed to use FB ads to do so. 

There are a bunch of types of FB ads, and Lead Ads are just one - they are basically forms. The more important type, imo, is Conversions, because you can use Conversions to build Lookalike audiences, which are arguably Facebook's $300B business. I'm sure you already know this, but just wanted to provide context on-ticket.

Anyway, I just want to call out that you should build *both* of these integrations for customers like me. I'm paying Zapier $30/mo for them right now, and I'd be happy to switch for less money, better experience, whatever. But Zapier is very good. 

For context, my workflows look like:
- Generate FB Lead Ad -> Send to FB Conversions API -> Send to Mailchimp -> Delay -> Send Gmail email
- Webflow form submission -> Send to FB Conversions API -> Send to Mailchimp -> Delay -> Send Gmail email

**Comment by ctrlaltdylan** [comment]
@dannyroosevelt I can see that the scaffolding for a few Facebook apps are complete, are we just waiting on some kind of Facebook side integration approval?

**Comment by dannyroosevelt** [comment]
> @dannyroosevelt I can see that the scaffolding for a few Facebook apps are complete, are we just waiting on some kind of Facebook side integration approval?

Yea I don't have context on this one but I'm working on finding out more.

**Comment by lupionpe** [comment]
@dannyroosevelt any updated here?

**Comment by sergioeliot2039** [comment]
+1 as per issue #4453

Let's use that issue for tracking the app integration, and this one for source building, the user is asking similar functionality i.e being notified of new leads, he is looking at this use case:

> When a user fills in a Facebook form, the details of the form are captured so I can update that information in to a google sheet

**Comment by sergio-eliot-rodriguez** [comment]
We are now tracking all Facebook Leads add components at https://github.com/PipedreamHQ/pipedream/issues/6907 
including trigger on new lead in Facebook Lead Ads of this issue, I'm closing this please follow #6907 currently blocked on Facebook approving the app, development completed.
