### ISSUE TITLE
[BUG] Lightspeed Retail POS app threw 401 error `Token has expired` after connecting for 10 minutes

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#9252]
**Describe the bug**
I connected the Lightspeed Retail POS app successfully via the OAuth popup. But 10 minutes later my source threw 401 error: Token has expired
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/7539ae95-79a0-41de-9fa3-1f94afc516b8)

Then I reconnect the account and it works fine again

**Comment by malexanderlim** [comment]
Hey @vunguyenhung , Michelle brought this up to me last week and I was trying to determine what the root cause is - it looks like some unusual OAuth refresh token behavior, where they are returning the exact same access token upon refresh if it is not expired -- not ideal. 

I've opened up a thread with them here for troubleshooting, thank you for re-flagging:
https://community.lightspeedhq.com/en/discussion/9169/refresh-token-returning-the-same-access-token/p1?new=1

**Comment by malexanderlim** [comment]
Lightspeed will not update their refresh token behavior, and expect the access token to expire before we can request a new one. I've disabled the app for now, as the current setup forces users to re-authenticate every time the access token expires.
