### ISSUE TITLE
[APP] Mezmo

### ISSUE THREAD

**Issue by MichaelHinrichs** [PipedreamHQ/pipedream#9328]
**Name of app / service**
Mezmo

**Link to developer documentation**
https://docs.mezmo.com/log-analysis-api

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**
Trigger on config or settings update. Use API keys. Send alerts to more apps. Send all updates to Slack that the native Slack integration does, to use one less Slack app for the free plan, with a limited amount of apps.

**Comment by sergio-eliot-rodriguez** [comment]
Hi there,

Mezmo has been integrated : https://pipedream.com/apps/mezmo

For componets development, follow https://github.com/PipedreamHQ/pipedream/issues/9363

**Comment by MichaelHinrichs** [comment]
Wow. You guys work fast. Is it really that easy to add a new app integration to Pipedream?

**Comment by malexanderlim** [comment]
Hi @MichaelHinrichs , it really depends on the app - if getting access to the app is straightforward, and they have API Keys or standard OAuth 2.0 for auth, it can be very quick to integrate. However, other apps may take longer due to the time it takes to get an account for development, documentation-related issues, issues with auth, or steps required for a verification process before we can take an app live.
