### ISSUE TITLE
clockify.me [APP]

### ISSUE THREAD

**Issue by tlpriest** [PipedreamHQ/pipedream#957]
**Service**: https://clockify.me

**API docs**: https://clockify.me/developers-api

**Workaround**: yes

**Actions & Triggers**: users can configure their own webhooks at https://clockify.me/webhooks for timer started, stopped and time entry created & updated. I want to connect this to Asana (task complete) to query clockify for all time records for this user on this task to create an invoice in QuickBooks.

**Comment by todsac** [comment]
@tlpriest - can you confirm that this integration works for you?  i don't have a paid account and i am getting the error "Full authentication is required to access this resource."  I thought this may be because it requires a paid account to access the API.

https://pipedream.com/@tod/clockify-api-integration-example-p_YyCoY2Q/

**Comment by tlpriest** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/585000/108776682-f2a0ea00-751f-11eb-91f2-ed7f85f53282.png)
