### ISSUE TITLE
[Components] surveycto

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9636]
# surveycto
## URLs
- https://support.surveycto.com/hc/en-us/articles/360033156894-REST-API-documentation
#### Prompt
Emit new event when new form data is submitted. Required prop is the form name but additional optional props like submission id can also be added.

**Comment by michelle0927** [comment]
@vunguyenhung Apologies, I meant to include this info in the PR and forgot to. To use the API, you have to set the role of the authenticated user to "Allow server API access". Additionally, to be able to submit forms via the Web (instead of Mobile), you need to allow "Anonymous access" for the form.

<img width="764" alt="Screenshot 2024-01-17 at 1 10 01 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/ae45fcb1-6eb4-45a9-aca8-4426669f9472">


<img width="1147" alt="Screenshot 2024-01-18 at 10 48 44 AM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/12b9cfed-6fae-4e33-a2b3-07b6388f1cac">
