### ISSUE TITLE
Active Campaign

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9966]
### App
Active Campaign

### Summary:
Cannot find all custom fields

### Details:
I 'm encountering a problem with the ActiveCampaign premium integration, where not all of my custom text input fields are displayed. I understand that only text input fields should appear in the "create_or_update_contact" action. Despite creating six new text input fields to capture data from a webhook, none of these fields are visible. Could there be a restriction on the number of fields that can be displayed?

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-01-18-at-11.14.35-PM.png?id=Rxjood&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlJ4am9vZCIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcwNTY0MTMwNH0.zIGvDZjRjGkxbt5n-X4gRTFe-LEsntMNkOf6kmLQh4c&signature=4f576e871ca58eb69dd38bf15020f10c88871b1acc027f06396b5f55d7b920f8)

**Comment by versusjl** [comment]
I just identified the issue. you are limiting how many custom fields show up in the integration. I have more custom fields than your platform is allowing to be shown. I know this because i deleted a field that was not super important and the first new field now shows up. 

You can see the new last field that shows is : D-First and that D-First was in the previous screen shot 


![Screenshot 2024-01-18 at 11 21 14 PM](https://github.com/PipedreamHQ/pipedream/assets/59858230/181f2a84-5bab-4a17-9704-e9e9b70b30c0)

**Comment by malexanderlim** [comment]
To component dev who picks this up, can you also please remove any deprecated props from the ActiveCampaign integration? I'm not sure why these were kept if they were deprecated.

<img width="1137" alt="Screenshot 2024-01-19 at 10 53 20 AM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/92b3e46b-8d0b-4003-827b-31cc9b8bd125">

**Comment by versusjl** [comment]
Thank you for updating.
